Repository luanti-org/luanti, pull requests merged in 2018-08, with the labels that each got.

#7567 VoxelManip: Abort if an argument is missing instead of silently doing nothing
  src/script/lua_api/l_vmanip.cpp
Labels: >= Two approvals, @ Script API, Maintenance

#6825 Smooth yaw
  src/content_cao.cpp
  src/content_cao.h
  src/content_sao.cpp
  src/util/numeric.h
Labels: @ Client / Audiovisuals, Feature, One approval

#7599 lua_api.txt: Improve code block format
  doc/lua_api.txt
Labels: >= Two approvals, @ Documentation

#7497 guiFormspecMenu: Allow fraction values for container[]
  src/gui/guiFormSpecMenu.cpp
  src/gui/guiFormSpecMenu.h
Labels: @ Client / Audiovisuals, Bugfix, One approval

#7598 Fix sky objects not rendering with ogles
  src/sky.cpp
Labels: >= Two approvals, @ Client / Audiovisuals, Android, Bugfix

#7279 Replace auth.txt with SQLite auth database
  build/android/jni/Android.mk
  builtin/game/auth.lua
  doc/world_format.txt
  src/database/database-files.cpp
  src/database/database-files.h
  src/database/database-sqlite3.cpp
  src/database/database-sqlite3.h
  src/database/database.h
  src/main.cpp
  src/script/lua_api/CMakeLists.txt
  src/script/lua_api/l_auth.cpp
  src/script/lua_api/l_auth.h
  src/script/scripting_server.cpp
  src/serverenvironment.cpp
  src/serverenvironment.h
  src/unittest/CMakeLists.txt
  src/unittest/test_authdatabase.cpp
  src/unittest/test_utilities.cpp
  src/util/string.h
Labels: >= Two approvals, @ Server / Client / Env., Blocker, Bugfix, Feature, High priority

#7469 Formspecs: Add tooltip element for area
  doc/lua_api.txt
  src/gui/guiFormSpecMenu.cpp
  src/gui/guiFormSpecMenu.h
Labels: @ Script API, Feature, One approval

#7610 Prevent from colliding with own children
  src/clientobject.h
  src/collision.cpp
  src/content_cao.h
  src/content_sao.cpp
  src/content_sao.h
  src/serverobject.h
Labels: @ Server / Client / Env., Bugfix, One approval

#7628 Some minor Fastface optimizations.
  src/client/tile.h
  src/mapblock_mesh.cpp
  src/mapblock_mesh.h
Labels: >= Two approvals, Performance

#7618 feature check for commit ac4884c3d677ef51bcce47f95ccd49d874022692
  builtin/game/features.lua
  doc/lua_api.txt
Labels: @ Script API, One approval, Trivial

#7636 lua_api.txt: Relocate item-def section
  doc/lua_api.txt
Labels: @ Documentation, One approval, Trivial

#7637 texture_packs.txt: Add information for leaves texturing
  doc/texture_packs.txt
Labels: @ Documentation, One approval

#7615 Save debug.txt to build dir for RUN_IN_PLACE build
  src/main.cpp
Labels: @ Startup / Config / Util, One approval, Trivial

#7638 lua_api.txt: Various fixes and improvements
  doc/lua_api.txt
Labels: @ Documentation, One approval

#7648 lua_api.txt: Refine 'Item types' for 4e2eeee
  doc/lua_api.txt
Labels: @ Documentation, One approval, Trivial

#6304 Raycast: export exact pointing location
  doc/lua_api.txt
  src/environment.cpp
  src/script/common/c_content.cpp
  src/script/common/c_content.h
  src/script/cpp_api/s_item.cpp
  src/script/cpp_api/s_item.h
  src/script/lua_api/l_env.cpp
  src/util/pointedthing.cpp
  src/util/pointedthing.h
Labels: >= Two approvals, @ Script API, Feature

#7568 Check node updates whether the blocks are known
  src/clientiface.h
  src/map.h
  src/server.cpp
  src/server.h
Labels: @ Server / Client / Env., Bugfix, One approval

#7641 Mgv5: Change tunnel parameters to those of other mapgens
  builtin/settingtypes.txt
  minetest.conf.example
  src/mapgen/mapgen_v5.cpp
  src/mapgen/mapgen_v5.h
Labels: @ Mapgen, One approval

#7397 World config: Add modpack descriptions and remove dependencies there
  builtin/mainmenu/dlg_config_world.lua
Labels: >= Two approvals, @ Mainmenu, Feature

#7433 Really delete things in fs::RecursiveDelete
  src/filesys.cpp
Labels: Blocker, Bugfix, One approval, Windows

#7659 Lua_api.txt: Update mapgen alias docs, add Singlenode use
  doc/lua_api.txt
Labels: @ Documentation, @ Mapgen, Trivial

#7664 Formspecs: Remove invalid background warning
  src/gui/guiFormSpecMenu.cpp
Labels: @ Client / Audiovisuals, Bugfix, Trivial

#7667 Content tab: Fix clipped text in button
  builtin/mainmenu/tab_content.lua
Labels: @ Mainmenu, Bugfix, One approval

#7399 Damage flash/camera tilt: Make shorter to reduce player blindness
  src/game.cpp
Labels: @ Client / Audiovisuals, One approval

#7592 get_node_drops: Make empty drop return empty table
  builtin/game/item.lua
Labels: @ Builtin, Bugfix
