Repository luanti-org/luanti, pull requests merged in 2018-09, with the labels that each got.

#7703 Fix clipped content tab description
  builtin/mainmenu/tab_content.lua
Labels: @ Client / Audiovisuals, @ Mainmenu, Bugfix, One approval

#7682 Particles: Make collision with objects optional
  doc/lua_api.txt
  src/client/clientevent.h
  src/network/clientpackethandler.cpp
  src/network/networkprotocol.h
  src/particles.cpp
  src/particles.h
  src/script/lua_api/l_particles.cpp
  src/server.cpp
  src/server.h
Labels: @ Client / Audiovisuals, Feature, One approval, Performance

#7711 Inv deSerialize(): Prevent infinite loop, error on failure
  src/inventory.cpp
  src/remoteplayer.cpp
Labels: Bugfix, One approval

#7693 Improve decode_light_f
  src/light.cpp
  src/light.h
  src/util/numeric.h
Labels: >= Two approvals, @ Client / Audiovisuals, Blocker, Bugfix, High priority

#7666 Change OpenGL preference to LEGACY
  README.md
  src/CMakeLists.txt
Labels: @ Client rendering engine, Bugfix

#7741 Fix various code issues highlighted by cppcheck
  src/inventorymanager.cpp
  src/mapgen/dungeongen.h
  src/mapgen/mapgen_singlenode.cpp
  src/mapgen/mapgen_singlenode.h
Labels: Maintenance, One approval

#7737 Builtin//misc_helpers: Various fixes
  builtin/common/misc_helpers.lua
Labels: Bugfix, Maintenance, Trivial

#7753 Fix temporary path crash in TestAuthDatabase
  src/unittest/test_authdatabase.cpp
Labels: Android, Blocker, Bugfix, High priority

#7651 Simpler software inventorycube
  builtin/settingtypes.txt
  doc/README.android
  minetest.conf.example
  src/client/tile.cpp
  src/client/tile.h
  src/defaultsettings.cpp
Labels: >= Two approvals, @ Client / Audiovisuals, Android, Blocker, Bugfix, High priority

#7676 Remove settings properly
  builtin/mainmenu/dlg_settings_advanced.lua
  src/settings.cpp
Labels: @ Startup / Config / Util, Bugfix, One approval
