Repository luanti-org/luanti, pull requests merged in 2018-07, with the labels that each got.

#7357 Make the server status message customizable
  builtin/game/chatcommands.lua
  builtin/game/misc.lua
  builtin/settingtypes.txt
  doc/lua_api.txt
  minetest.conf.example
  src/defaultsettings.cpp
  src/server.cpp
Labels: @ Script API, Feature, One approval

#7491 Log deprecated Lua function calls
  src/script/lua_api/l_base.cpp
  src/script/lua_api/l_base.h
  src/script/lua_api/l_noise.cpp
  src/script/lua_api/l_noise.h
  src/script/lua_api/l_object.cpp
  src/script/lua_api/l_object.h
Labels: @ Script API, Feature, One approval

#7526 Correctly verify client passed zoom at the server.
  src/clientiface.cpp
Labels: @ Server / Client / Env., Blocker, Bugfix, High priority, One approval

#7213 Run code style linter first
  .travis.yml
Labels: >= Two approvals, @ Startup / Config / Util, Maintenance, Trivial

#7533 Lua_api.txt: Improve section titles, clarify sections
  doc/lua_api.txt
Labels: @ Documentation, Maintenance, Trivial

#7534 Lua API formatting and grammar fixes
  doc/lua_api.txt
Labels: @ Documentation, Maintenance, One approval, Trivial

#7539 Revert 6587 - Optimize entity-entity collision
  build/android/jni/Android.mk
  src/content_sao.cpp
  src/irr_aabb3d.h
  src/irr_v3d.h
  src/server/CMakeLists.txt
  src/server/serveractiveobjectmap.cpp
  src/server/serveractiveobjectmap.h
  src/serverenvironment.cpp
  src/serverenvironment.h
  src/unittest/CMakeLists.txt
  src/unittest/test.h
  src/unittest/test_serveractiveobjectmap.cpp
  util/travis/clang-format-whitelist.txt
Labels: >= Two approvals

#7512 Lua templating reading (part 4): s16, v2s16, v2f
  src/script/common/c_converter.cpp
  src/script/common/c_converter.h
  src/script/common/helper.cpp
  src/script/lua_api/l_noise.cpp
  src/script/lua_api/l_object.cpp
Labels: @ Client Script API, @ Script API, One approval

#7540 Minor fixes to builtin/game/misc.lua
  builtin/game/misc.lua
Labels: @ Builtin, One approval, Trivial

#7476 core.spawn_falling_node: Keep metadata
  builtin/game/falling.lua
Labels: @ Builtin, Bugfix, One approval

#7477 Android: Add aux ("use") button
  builtin/settingtypes.txt
  src/defaultsettings.cpp
  src/gui/touchscreengui.cpp
  src/gui/touchscreengui.h
  textures/base/pack/aux_btn.png
Labels: >= Two approvals, @ Client / Controls / Input, Android, Blocker, High priority

#7549 Adjust some settings to modern environments and networks.
  builtin/settingtypes.txt
  src/defaultsettings.cpp
Labels: @ Startup / Config / Util, Maintenance, One approval

#7543 Make player liquid speed independent of FPS
  src/clientenvironment.cpp
Labels: @ Client / Audiovisuals, Bugfix, Testing needed

#7560 Lua_api.txt: Various minor improvements
  doc/lua_api.txt
Labels: @ Documentation, Maintenance, Trivial

#7554 Check if player exists on use of /privs
  builtin/game/chatcommands.lua
Labels: @ Builtin, One approval, Trivial

#7561 Builtin: Replace deprecated function calls
  builtin/game/chatcommands.lua
  builtin/game/falling.lua
  builtin/game/item.lua
  builtin/game/item_entity.lua
  builtin/game/misc.lua
  builtin/game/static_spawn.lua
Labels: @ Builtin, Maintenance, One approval, Trivial

#7532 Mgvalleys: Make river depth variation and humidity drop optional
  builtin/settingtypes.txt
  src/mapgen/mapgen_valleys.cpp
  src/mapgen/mapgen_valleys.h
Labels: @ Mapgen, Feature, One approval

#7547 CSM: Disallow exploitable clientside mod functions by default
  builtin/settingtypes.txt
  src/defaultsettings.cpp
Labels: >= Two approvals, @ Client Script API, High priority

#7572 Update Android defaults for modern H/W.
  src/defaultsettings.cpp
Labels: >= Two approvals, Android, Maintenance

#7353 Add a MSVC / Windows compatible snprintf function
  src/game.cpp
  src/gui/guiConfirmRegistration.cpp
  src/gui/profilergraph.cpp
  src/guiscalingfilter.cpp
  src/map.cpp
  src/mapblock.cpp
  src/porting.cpp
  src/porting.h
  src/script/common/c_internal.cpp
  src/script/cpp_api/s_base.cpp
  src/serverenvironment.cpp
  src/unittest/test.cpp
  src/unittest/test_connection.cpp
Labels: >= Two approvals, @ Startup / Config / Util, Bugfix, Windows

#7544 Allow an optional readonly base database
  doc/world_format.txt
  src/map.cpp
  src/map.h
Labels: @ Server / Client / Env., Feature, One approval

#7580 Settings: Fix indents, chat_message_*. Update translations
  builtin/settingtypes.txt
  minetest.conf.example
  src/settings_translation_file.cpp
Labels: @ Documentation, Maintenance, One approval, Trivial

#7583 Replace apt-get with apt
  README.md
Labels: @ Documentation, One approval, Trivial

#7582 lua_api.txt fixes and format improvements
  doc/lua_api.txt
Labels: @ Documentation, Maintenance, One approval

#7586 Fix build on gcc 5.0
  src/mapgen/mg_ore.cpp
  src/network/connection.cpp
  src/util/srp.cpp
Labels: >= Two approvals, Bugfix

#7589 Log server shutdown using actionstream
  src/server.cpp
Labels: Maintenance, One approval, Trivial

#7351 Allow enter to select items from combobox's list.
  src/gui/guiFormSpecMenu.cpp
Labels: Feature, One approval

#7595 Document default values for general cmake options
  README.md
Labels: @ Documentation, One approval

#7596 Lua_api.txt: Clarify entity 'initial_properties' and related deprecation
  doc/lua_api.txt
Labels: @ Documentation, Maintenance, One approval

#7588 Improve formatting of Player HUD flags documentation
  doc/lua_api.txt
Labels: >= Two approvals, @ Documentation, Maintenance

#7594 Make the primary, flow-advancing action the right-most
  builtin/mainmenu/tab_local.lua
Labels: >= Two approvals, @ Mainmenu, Maintenance
