Repository luanti-org/luanti, pull requests merged in 2018-10, with the labels that each got.

#7748 Night clouds: Boost brightness for a moonlit appearence
  src/sky.cpp
Labels: @ Client / Audiovisuals, One approval

#7756 Fix mgValleys getSpawnLevelAtPoint()
  src/mapgen/mapgen_valleys.cpp
Labels: @ Mapgen, Blocker, Bugfix, High priority, One approval, Trivial

#7714 Dig particles: Use gravity setting and physics override. More velocity to be more visible. More lightweight
  src/particles.cpp
Labels: @ Client / Audiovisuals, Maintenance, One approval, Performance

#7461 F5 debug info: Use full words for NSEW directions for readability
  src/client/gameui.cpp
Labels: @ Client / Audiovisuals, Maintenance, One approval

#7769 Various spelling and grammar improvements
  README.md
  builtin/mainmenu/pkgmgr.lua
  builtin/settingtypes.txt
Labels: @ Documentation, Maintenance, Trivial

#7778 Advanced settings menu: Centre setting edit box
  builtin/mainmenu/dlg_settings_advanced.lua
Labels: @ Mainmenu, Maintenance, Trivial

#7771 Add release information to appdata file
  misc/net.minetest.minetest.appdata.xml
  util/bump_version.sh
Labels: >= Two approvals, @ Build

#7790 Advanced settings tree menu: Resize, fix clipped values
  builtin/mainmenu/dlg_settings_advanced.lua
Labels: @ Mainmenu, Bugfix, Maintenance, Trivial

#7792 Android buttons: Inset 'rare controls', inset and resize 'gear icon'
  src/gui/touchscreengui.cpp
  textures/base/pack/gear_icon.png
Labels: @ Client / Controls / Input, Android, Maintenance, One approval

#7801 Settingtypes.txt: Various language improvements, document stable mapgens
  builtin/settingtypes.txt
Labels: @ Documentation, Maintenance, One approval, Trivial

#7802 Mainmenu: Clean up and improve advanced settings dialogues
  builtin/mainmenu/dlg_settings_advanced.lua
Labels: @ Mainmenu, Blocker, High priority, Maintenance, One approval

#7804 clear_craft: Return false instead of Lua error if recipe not found
  doc/lua_api.txt
  src/script/lua_api/l_craft.cpp
Labels: @ Script API, Maintenance, One approval

#6153 Windows: Cpack wix installer
  CMakeLists.txt
  README.md
  lib/gmp/CMakeLists.txt
  lib/jsoncpp/CMakeLists.txt
  misc/CPACK_WIX_UI_BANNER.BMP
  misc/CPACK_WIX_UI_DIALOG.BMP
  src/CMakeLists.txt
  src/porting.cpp
Labels: >= Two approvals, @ Build, Feature

#7819 Advanced settings: Fix noise parameter flags
  builtin/mainmenu/dlg_settings_advanced.lua
Labels: @ Mainmenu, Bugfix, High priority, Trivial

#7824 Framed glasslike: Fix and document top/base textures feature
  doc/lua_api.txt
  src/content_mapblock.cpp
Labels: @ Client / Audiovisuals, @ Documentation, Bugfix, Trivial

#7826 Framed glasslike: Fix z-fighting, improve codestyle
  src/content_mapblock.cpp
Labels: @ Client / Audiovisuals, Bugfix, Maintenance, Trivial
