Repository luanti-org/luanti, pull requests merged in 2018-06, with the labels that each got.

#7393 Biomemap: Avoid empty biomemap entry to fix failing biome dust
  src/mapgen/mapgen.cpp
Labels: @ Mapgen, Bugfix, Trivial

#7398 Biomemap: Simplify code of recent commit
  src/mapgen/mapgen.cpp
Labels: @ Mapgen, Maintenance, Trivial

#7402 Lua_api.txt: Various improvements
  doc/lua_api.txt
Labels: @ Documentation, Trivial

#7405 Biome dust placement: Improve comments, re-order some lines
  src/mapgen/mapgen.cpp
Labels: @ Documentation, Maintenance, Trivial

#7394 Modernize lua read (part 1): C++ templating insurance
  src/script/lua_api/l_base.cpp
  src/script/lua_api/l_base.h
  src/script/lua_api/l_env.cpp
  src/script/lua_api/l_metadata.cpp
  src/script/lua_api/l_nodetimer.cpp
  src/script/lua_api/l_noise.cpp
  src/script/lua_api/l_object.cpp
  src/script/lua_api/l_server.cpp
  src/script/lua_api/l_util.cpp
Labels: @ Client Script API, @ Script API, Code quality, One approval

#7415 Set ENABLE_GETTEXT to TRUE by default
  src/CMakeLists.txt
Labels: >= Two approvals, @ Build, Maintenance, Trivial

#7368 Fix builtin lua function os.tempfolder
  builtin/mainmenu/common.lua
Labels: @ Mainmenu, Bugfix, One approval, Windows

#7411 CSM/SSM: Add on_mods_loaded callback
  builtin/client/register.lua
  builtin/game/register.lua
  clientmods/preview/init.lua
  doc/client_lua_api.txt
  doc/lua_api.txt
  games/minimal/mods/experimental/init.lua
  src/client.cpp
  src/script/cpp_api/s_client.cpp
  src/script/cpp_api/s_client.h
  src/script/cpp_api/s_server.cpp
  src/script/cpp_api/s_server.h
  src/server/mods.cpp
Labels: @ Client Script API, @ Script API, Feature, One approval

#7417 Stop autoforward on BACKWARD key-press (if autoforward is active)
  builtin/settingtypes.txt
  src/game.cpp
Labels: >= Two approvals, @ Client / Controls / Input, Feature

#7422 Lua_api.txt: Warn of errors possible with use of VoxelArea:index()/indexp()
  doc/lua_api.txt
Labels: @ Documentation, Maintenance, Trivial

#7431 Fix the /shutdown command
  builtin/game/chatcommands.lua
  src/server.cpp
Labels: >= Two approvals, @ Server / Client / Env., Bugfix

#7336 Implemented hasprivs chat-command (Closes #7266)
  builtin/game/chatcommands.lua
Labels: >= Two approvals, @ Server / Client / Env., Feature

#7440 README.md: Remove 'unfinished' section.
  README.md
Labels: >= Two approvals, @ Documentation

#7443 Make os.tempfolder work correctly for MinGW and MSVC
  builtin/mainmenu/common.lua
Labels: Bugfix, One approval, Windows

#7437 Server: move shutdown parts to a specific shutdown state object
  src/game.cpp
  src/main.cpp
  src/network/serverpackethandler.cpp
  src/server.cpp
  src/server.h
  src/unittest/CMakeLists.txt
  src/unittest/test_server_shutdown_state.cpp
Labels: @ Server / Client / Env., Code quality, One approval

#7423 Minimal: Disable disruptive formspec test by default
  games/minimal/mods/experimental/init.lua
Labels: >= Two approvals

#7449 Version scheme change: 0.5.0 -> 5.0.0
  CMakeLists.txt
  README.md
  doc/client_lua_api.txt
  doc/menu_lua_api.txt
Labels: >= Two approvals, Maintenance

#7445 Xorg/net wm pid
  src/client/clientlauncher.cpp
  src/client/renderingengine.cpp
  src/client/renderingengine.h
Labels: >= Two approvals, @ Startup / Config / Util, Feature

#7455 Remove deprecated functions from menu_lua_api.txt
  doc/menu_lua_api.txt
Labels: >= Two approvals, @ Documentation, Maintenance, Trivial

#7459 ContentDB: Update API
  builtin/mainmenu/dlg_contentstore.lua
  src/content/packages.cpp
  src/content/packages.h
  src/script/lua_api/l_mainmenu.cpp
Labels: @ Mainmenu, One approval

#7464 Biome dust: Revert fix that added dust to mod structures
  src/mapgen/mapgen.cpp
Labels: @ Mapgen, Bugfix, Trivial

#7466 Fix incorrect directive in lua_api.txt
  doc/lua_api.txt
Labels: @ Documentation, Bugfix, One approval, Trivial

#7465 README.md: Improve version scheme text
  README.md
Labels: >= Two approvals, @ Documentation, Maintenance

#7470 Biome API: Fix missing water decorations and biome 'dust' in deep water
  src/mapgen/mapgen.cpp
  src/mapgen/mg_biome.cpp
Labels: @ Mapgen, Bugfix, One approval

#7472 README.md: Improve formatting for consistency
  README.md
Labels: >= Two approvals, @ Documentation, Maintenance

#7471 Fix ipv6_server=true not accepting IPv4 connections on Windows
  src/network/socket.cpp
Labels: Bugfix, Windows

#7473 Fix crash caused by Lua error during startup
  src/emerge.cpp
Labels: Bugfix, One approval

#7428 RTT fixes
  src/client.cpp
  src/network/connection.cpp
  src/network/connection.h
  src/network/connectionthreads.cpp
  src/network/peerhandler.h
Labels: >= Two approvals, @ Network, Bugfix

#7463 Use correct name for android temp path
  src/filesys.cpp
Labels: Android, Bugfix, Trivial

#7456 Decoration API: Add lightweight ability to have complete coverage
  doc/lua_api.txt
  src/mapgen/mg_decoration.cpp
Labels: @ Mapgen, @ Script API, Feature, One approval

#7474 lua_api.txt: Update outdated documentation
  doc/lua_api.txt
Labels: @ Documentation, Maintenance, One approval, Trivial

#7482 Fix alignment issues in MurmurHash
  src/util/numeric.cpp
Labels: Android, Bugfix, One approval

#7487 Lua_api.txt: Re-order some sections. Alphabeticise class reference
  doc/lua_api.txt
Labels: @ Documentation, Maintenance, One approval

#7488 Fix libgmp detection
  cmake/Modules/FindGMP.cmake
Labels: @ Build, One approval, Trivial

#7484 Fix buffer overrun in SRP
  src/util/srp.cpp
Labels: Bugfix

#7480 Cavegen: Fix crash when getting biome outside mapchunk
  src/mapgen/cavegen.cpp
Labels: @ Mapgen, Blocker, Bugfix, One approval, Trivial

#7492 Fix small memory leaks in client.
  src/client.cpp
Labels: Bugfix, One approval, Trivial

#7481 Fix mod channels crash
  src/script/lua_api/l_modchannels.cpp
  src/script/lua_api/l_modchannels.h
Labels: >= Two approvals, @ Script API, Bugfix

#7495 Mgvalleys: Fix 'mgvalleys_spflags' setting name
  builtin/settingtypes.txt
Labels: @ Mapgen, Bugfix, Trivial

#7506 Removed '$' symbols from the start of shell commands in the README file
  README.md
Labels: >= Two approvals, @ Documentation

#7503 Log usage of /pulverize
  builtin/game/chatcommands.lua
Labels: @ Builtin, Feature, One approval, Trivial

#7494 Fix world deletion
  src/script/lua_api/l_mainmenu.cpp
Labels: @ Script API, Bugfix, One approval

#7500 Fix memory leaks in mod storage
  src/script/lua_api/l_storage.cpp
  src/script/lua_api/l_storage.h
Labels: >= Two approvals, @ Script API, Maintenance

#7410 Modernize lua read (part 2 & 3): C++ templating assurance
  build/android/jni/Android.mk
  src/script/common/CMakeLists.txt
  src/script/common/c_internal.h
  src/script/common/helper.cpp
  src/script/common/helper.h
  src/script/cpp_api/s_base.cpp
  src/script/cpp_api/s_base.h
  src/script/cpp_api/s_client.cpp
  src/script/cpp_api/s_entity.cpp
  src/script/cpp_api/s_env.cpp
  src/script/cpp_api/s_node.cpp
  src/script/cpp_api/s_player.cpp
  src/script/cpp_api/s_security.cpp
  src/script/cpp_api/s_server.cpp
  src/script/lua_api/l_areastore.cpp
  src/script/lua_api/l_base.cpp
  src/script/lua_api/l_base.h
  src/script/lua_api/l_client.cpp
  src/script/lua_api/l_craft.cpp
  src/script/lua_api/l_env.cpp
  src/script/lua_api/l_http.cpp
  src/script/lua_api/l_inventory.cpp
  src/script/lua_api/l_item.cpp
  src/script/lua_api/l_mainmenu.cpp
  src/script/lua_api/l_mapgen.cpp
  src/script/lua_api/l_metadata.cpp
  src/script/lua_api/l_nodemeta.cpp
  src/script/lua_api/l_object.cpp
  src/script/lua_api/l_particles.cpp
  src/script/lua_api/l_server.cpp
  src/script/lua_api/l_settings.cpp
  src/script/lua_api/l_sound.cpp
  src/script/lua_api/l_storage.cpp
  src/script/lua_api/l_util.cpp
  src/script/lua_api/l_vmanip.cpp
Labels: @ Client Script API, @ Script API, Code quality

#7498 Android: Resize jump and crunch buttons' touch target
  src/gui/touchscreengui.cpp
  textures/base/pack/down.png
  textures/base/pack/jump_btn.png
Labels: >= Two approvals, @ Client / Controls / Input, Android, Blocker, High priority, Maintenance
