Repository luanti-org/luanti, pull requests merged in 2018-04, with the labels that each got.

#6295 LINT: add clang-tidy step
  .clang-tidy
  .travis.yml
  src/gui/guiEditBoxWithScrollbar.cpp
  src/script/cpp_api/s_env.cpp
  util/travis/before_install.sh
  util/travis/clangtidy.sh
  util/travis/run-clang-tidy.py
  util/travis/script.sh
Labels: @ Build, One approval

#5286 Inventory item mousewheel movement
  src/gui/guiFormSpecMenu.cpp
Labels: >= Two approvals, @ Client / Audiovisuals, Feature

#7189 Fix many issues reported by clang-tidy
  src/chat.cpp
  src/chat.h
  src/mapgen/cavegen.cpp
  src/mapgen/dungeongen.cpp
  src/mapgen/mapgen_carpathian.cpp
  src/mapgen/mapgen_fractal.cpp
  src/mapgen/mapgen_v7.cpp
  src/mapgen/mapgen_valleys.cpp
  src/mapgen/mg_ore.cpp
  src/script/lua_api/l_object.cpp
  src/unittest/test_noise.cpp
  src/unittest/test_random.cpp
  src/unittest/test_settings.cpp
  src/unittest/test_utilities.cpp
Labels: Code quality, Maintenance, Trivial

#6520 Selected ItemStack: Reduce black magic
  src/gui/guiFormSpecMenu.cpp
  src/gui/guiFormSpecMenu.h
Labels: @ Mainmenu, Bugfix, One approval

#7193 Optimize a little bit isBlockInSight, adjustDist & collisions
  src/collision.cpp
  src/util/numeric.cpp
Labels: >= Two approvals, Maintenance, Performance

#7195 Huge LBM lookup performance improvement on mapblock loading
  src/serverenvironment.cpp
Labels: Performance

#7194 [clang-tidy] Promote some performance-* as a coding error
  src/content_cao.cpp
  src/game.cpp
  util/travis/clangtidy.sh
Labels: Code quality

#7208 Zoom adjustDist(): Improve variable name
  src/util/numeric.cpp
Labels: Maintenance, Trivial

#7209 Mgcarpathian: Remove insignificant 'base' noise variation
  builtin/settingtypes.txt
  src/mapgen/mapgen_carpathian.cpp
  src/mapgen/mapgen_carpathian.h
Labels: @ Mapgen, Maintenance, Trivial

#7212 Mgcarpathian: Fix spawn level calculation
  src/mapgen/mapgen_carpathian.cpp
Labels: @ Mapgen, Bugfix, Trivial

#7200 Fix SAOM
  src/content_sao.cpp
  src/server/serveractiveobjectmap.cpp
  src/server/serveractiveobjectmap.h
Labels: >= Two approvals, @ Server / Client / Env., Bugfix

#7218 Biome API / dungeons: Add biome-defined dungeon nodes
  doc/lua_api.txt
  src/mapgen/mapgen.cpp
  src/mapgen/mapgen.h
  src/mapgen/mapgen_carpathian.cpp
  src/mapgen/mapgen_flat.cpp
  src/mapgen/mapgen_fractal.cpp
  src/mapgen/mapgen_v5.cpp
  src/mapgen/mapgen_v7.cpp
  src/mapgen/mapgen_valleys.cpp
  src/mapgen/mg_biome.cpp
  src/mapgen/mg_biome.h
  src/script/lua_api/l_mapgen.cpp
Labels: @ Mapgen, @ Script API, Feature, Maintenance, One approval

#7126 Android: Replace movement buttons with joystick
  builtin/settingtypes.txt
  minetest.conf.example
  src/defaultsettings.cpp
  src/gui/touchscreengui.cpp
  src/gui/touchscreengui.h
  textures/base/pack/down_arrow.png
  textures/base/pack/joystick_bg.png
  textures/base/pack/joystick_center.png
  textures/base/pack/joystick_off.png
  textures/base/pack/left_arrow.png
  textures/base/pack/right_arrow.png
  textures/base/pack/up_arrow.png
Labels: >= Two approvals, Android, Feature, High priority

#7234 FOV: Raise lower limit to avoid zoom-loading distant world
  builtin/settingtypes.txt
  src/camera.cpp
  src/clientiface.cpp
  src/content_sao.cpp
  src/content_sao.h
Labels: @ Client / Audiovisuals, @ Server / Client / Env., Bugfix, One approval

#7249 Cavegen: Fix variable typo that broke mgvalleys large cave distribution
  src/mapgen/cavegen.cpp
  src/mapgen/cavegen.h
Labels: @ Mapgen, Bugfix, One approval

#7240 Android: Modify touch screen GUI's buttons
  LICENSE.txt
  src/gui/touchscreengui.cpp
  src/gui/touchscreengui.h
  textures/base/pack/chat_hide_btn.png
  textures/base/pack/chat_show_btn.png
  textures/base/pack/jump_btn.png
  textures/base/pack/minimap_btn.png
  textures/base/pack/zoom.png
Labels: >= Two approvals, @ Client / Controls / Input, Android, Feature, High priority

#7243 PlayerSettings struct for player movement code
  src/localplayer.cpp
  src/player.cpp
  src/player.h
Labels: >= Two approvals, @ Client / Controls / Input, Maintenance, Performance

#7252 Builtin auth handler: Speed up file writing
  builtin/game/auth.lua
Labels: >= Two approvals, @ Script API, Performance

#7255 "#if undefined_constant < number" is always true
  src/cguittfont/irrUString.h
  src/util/cpp11.h
  src/util/cpp11_container.h
Labels: >= Two approvals, @ Build, Bugfix

#7256 Node resolver: Make error on fallback optional, disable for mapgen aliases
  src/mapgen/mg_biome.cpp
  src/nodedef.cpp
  src/nodedef.h
Labels: @ Mapgen, Maintenance, One approval

#7259 Fix i386 build at OpenBSD
  src/unittest/test_serialization.cpp
Labels: >= Two approvals, @ Build

#7257 Cave liquids: Use a more precise point for calculating biome
  src/mapgen/cavegen.cpp
Labels: @ Mapgen, Bugfix, Trivial

#7244 Mgvalleys: Use shared tunnel / cavern code instead of internal
  src/mapgen/mapgen_valleys.cpp
  src/mapgen/mapgen_valleys.h
Labels: @ Mapgen, Bugfix, Maintenance, Trivial

#7116 Formspecs: Allow specifying a certain alpha value for the box[] element
  doc/lua_api.txt
  src/gui/guiFormSpecMenu.cpp
  src/gui/guiFormSpecMenu.h
  src/util/string.cpp
  src/util/string.h
Labels: >= Two approvals, @ Client / Audiovisuals, Feature

#7273 Move ASCII art to std::cerr, to remove it from logs
  src/server.cpp
Labels: @ Startup / Config / Util, One approval, Trivial

#7271 Mgvalleys: Code cleanup
  src/mapgen/mapgen_valleys.cpp
  src/mapgen/mapgen_valleys.h
Labels: @ Mapgen, Maintenance, Trivial

#7275 Mgvalleys: Update settingtypes.txt
  builtin/settingtypes.txt
Labels: @ Mapgen, Maintenance, Trivial

#7267 Dungeons: Mostly fix missing stair nodes
  src/mapgen/dungeongen.cpp
Labels: @ Mapgen, Bugfix, One approval

#7214 MetaDataRef: Add contains() and get()
  doc/lua_api.txt
  games/minimal/mods/test/init.lua
  src/script/lua_api/l_itemstackmeta.cpp
  src/script/lua_api/l_metadata.cpp
  src/script/lua_api/l_metadata.h
  src/script/lua_api/l_nodemeta.cpp
  src/script/lua_api/l_playermeta.cpp
  src/script/lua_api/l_storage.cpp
Labels: >= Two approvals, @ Client Script API, @ Script API, Feature, Low priority

#6786 Allow damage for attached objects, add attach/detach callbacks
  doc/lua_api.txt
  src/content_cao.cpp
  src/content_sao.cpp
  src/content_sao.h
  src/script/cpp_api/s_entity.cpp
  src/script/cpp_api/s_entity.h
  src/script/lua_api/l_object.cpp
  src/server.cpp
  src/serverobject.h
Labels: @ Script API, @ Server / Client / Env., Feature, One approval

#7236 Global new() or grab() to be managed in constuctor only (#7235 partial)
  src/wieldmesh.cpp
Labels: @ Client / Audiovisuals, Bugfix, One approval, Trivial

#7288 Delete two method definition in nodedef.h file.
  src/nodedef.h
Labels: Maintenance, Trivial
