Repository luanti-org/luanti, pull requests merged in 2019-03, with the labels that each got.

#8289 Fix particle spawners not visible since CSM spawner implementation
  src/client/client.h
  src/client/clientevent.h
  src/client/particles.cpp
  src/client/particles.h
  src/network/clientpackethandler.cpp
  src/script/lua_api/l_particles_local.cpp
Labels: Blocker, Bugfix, High priority, One approval, Particles, Testing needed

#8260 README: Remove references to Minecraft and InfiniMiner
  README.md
Labels: >= Two approvals, @ Documentation, One approval, Trivial

#8305 Don't include and link to gettext if gettext is not found
  src/CMakeLists.txt
Labels: @ Build, One approval

#8304 getS16NoEx() returns true unless syntactical error in conf.
  src/emerge.cpp
Labels: @ Mapgen, Bugfix, One approval

#8135 Add referer to remote media requests.
  src/client/clientmedia.cpp
Labels: @ Client / Audiovisuals, @ Server / Client / Env., Feature, One approval

#8255 Hide uninstall package button on unmodifiable paths
  builtin/mainmenu/tab_content.lua
  src/script/lua_api/l_mainmenu.cpp
  src/script/lua_api/l_mainmenu.h
Labels: @ Content/PkgMgr, @ Mainmenu, Bugfix, One approval

#8194 Replace for loop with call to standard library function
  src/gui/mainmenumanager.h
Labels: >= Two approvals, Code quality, Maintenance

#7173 Fix --color command line parameter ignorance
  src/log.h
  src/main.cpp
Labels: @ Startup / Config / Util, Bugfix, One approval

#7719 Add sounds for falling and attached nodes
  builtin/game/falling.lua
  doc/lua_api.txt
Labels: Feature, One approval, Sounds

#8298 Add math.factorial
  builtin/common/misc_helpers.lua
  doc/lua_api.txt
Labels: >= Two approvals, Feature

#8303 Change 'num_emerge_threads' default to 1
  builtin/settingtypes.txt
  minetest.conf.example
  src/defaultsettings.cpp
Labels: One approval

#8333 Fix incorrect string length check after cast
  src/network/networkpacket.cpp
Labels: >= Two approvals, @ Network, Bugfix

#8331 Fix detach inventory serialisation
  src/network/clientpackethandler.cpp
  src/server.cpp
Labels: Blocker, High priority, One approval, Testing needed

#8319 Update a few dependency versions for buildbot
  util/buildbot/buildwin32.sh
  util/buildbot/buildwin64.sh
Labels: @ Build, Maintenance, One approval, Windows

#8193 Optimize interaction distance checker
  src/network/serverpackethandler.cpp
  src/server.h
Labels: Maintenance, Performance, Trivial

#8098 Optimize string handling in path search
  src/content/subgames.cpp
Labels: >= Two approvals, Performance

#7396 World config: Make depends easier to read
  builtin/mainmenu/dlg_config_world.lua
  builtin/mainmenu/pkgmgr.lua
Labels: >= Two approvals, @ Builtin, @ Client / Audiovisuals, @ Mainmenu

#7011 Abort when trying to set a not registered node
  src/mapnode.cpp
  src/mapnode.h
  src/rollback_interface.cpp
  src/script/common/c_content.cpp
Labels: >= Two approvals, @ Script API, Bugfix

#8258 Confirm registration GUI: Remove positional strings to fix Windows bug
  src/gui/guiConfirmRegistration.cpp
Labels: @ Mainmenu, Blocker, Bugfix, One approval

#8321 Display pitch angle in debug menu
  src/client/gameui.cpp
Labels: >= Two approvals, Feature

#8306 Document the `float` special group
  doc/lua_api.txt
Labels: @ Documentation, One approval, Trivial

#8353 Fix serialization of std::time_t by casting to u64 first
  src/network/clientpackethandler.cpp
  src/network/networkpacket.cpp
  src/network/networkpacket.h
  src/server.cpp
Labels: @ Network, Blocker, Bugfix, High priority

#8359 HPChange Reason: Fix push after free, and type being overwritten
  src/content_sao.h
  src/script/cpp_api/s_base.cpp
  src/script/lua_api/l_object.cpp
Labels: @ Script API, Blocker, Bug, High priority, One approval

#8354 Fix cast from const by accessing string data directly
  src/irrlicht_changes/irrUString.h
Labels: @ Startup / Config / Util, Blocker, Bugfix, High priority

#8101 Valleys mapgen code rewrite
  src/mapgen/mapgen_valleys.cpp
  src/mapgen/mapgen_valleys.h
Labels: @ Mapgen, Bugfix, Maintenance, One approval

#8357 num_emerge_threads: Warn of crashes when > 1
  builtin/settingtypes.txt
  minetest.conf.example
Labels: @ Documentation, Blocker, High priority, One approval

#8376 Lua_api.txt: Document blockpos, coordinate conversion, map terminology. Fix and improve LVM 'calc_lighting()' warning
  doc/lua_api.txt
Labels: @ Documentation, Trivial

#7738 Spatial Vectors: Add vector.angle(a, b)
  builtin/common/vector.lua
  doc/lua_api.txt
Labels: >= Two approvals, @ Script API, Feature

#8388 core.after: Improve assertion message
  builtin/common/after.lua
Labels: >= Two approvals, Maintenance

#8213 Add newline before itemstring in item tooltip
  src/gui/guiFormSpecMenu.cpp
Labels: >= Two approvals, @ Client / Audiovisuals

#8392 num_emerge_threads: Fix documentation of automatic selection
  builtin/settingtypes.txt
  minetest.conf.example
Labels: @ Documentation, Trivial

#8396 num_emerge_threads: Initialise value to cope with setting syntax error
  src/emerge.cpp
Labels: Bugfix, Maintenance, One approval

#8399 httpfetch: Disable IPv6 here too if requested by settings
  src/httpfetch.cpp
Labels: @ Network, Low priority, One approval, Trivial

#8401 Fix texture rotation for wallmounted nodeboxes
  src/client/mapblock_mesh.cpp
Labels: @ Client / Audiovisuals, Blocker, Bugfix, High priority, One approval, Trivial

#8404 Document 'highly unstable' mapgens instead of 'stable' mapgens
  builtin/settingtypes.txt
Labels: @ Documentation, @ Mapgen, Trivial

#8420 Prevent multi-line chat messages server-side
  src/server.cpp
Labels: @ Server / Client / Env., Blocker, Bugfix, High priority, One approval, Trivial

#8423 Dungeons: Do not remove nodes that have 'is_ground_content = false'
  doc/lua_api.txt
  src/mapgen/dungeongen.cpp
Labels: @ Mapgen, Bugfix, Trivial

#8418 Require 'waving = 3' in nodedefs to enable liquid waving shader
  builtin/mainmenu/tab_settings.lua
  client/shaders/nodes_shader/opengl_vertex.glsl
  doc/lua_api.txt
  src/client/shader.cpp
  src/client/tile.h
  src/nodedef.cpp
Labels: @ Client / Audiovisuals, @ Script API, Feature, One approval

#8351 Improve core.after in a simple way
  builtin/common/after.lua
Labels: >= Two approvals, @ Builtin, Performance

#8432 Use unordered_map instead of map for craft definitions
  src/craftdef.cpp
Labels: >= Two approvals, One approval
