Repository luanti-org/luanti, pull requests merged in 2019-02, with the labels that each got.

#8156 Move missing translations warnings to verbosestream.
  src/translation.cpp
Labels: Bugfix, One approval, Trivial

#8114 doc: Python check bump to Python 3
  doc/protocol.txt
Labels: @ Documentation, Maintenance, One approval

#8157 Force player save before kicking on player shutdown
  src/server.cpp
  src/serverenvironment.cpp
  src/serverenvironment.h
Labels: Bugfix, One approval

#8159 DragonFly BSD is somewhat identical to FreeBSD
  cmake/Modules/FindGettextLib.cmake
  src/CMakeLists.txt
  src/gui/intlGUIEditBox.cpp
  src/irrlicht_changes/irrUString.h
  src/threading/thread.cpp
  src/util/serialize.h
Labels: @ Build, Bugfix, One approval, Trivial

#8145 Add setting to hide mature content from ContentDB
  builtin/mainmenu/dlg_contentstore.lua
  builtin/settingtypes.txt
  src/defaultsettings.cpp
Labels: @ Content/PkgMgr, Blocker, High priority, One approval

#8169 Update manpage
  doc/minetest.6
Labels: @ Documentation, Maintenance, One approval

#8172 Main menu: Fix cloud color
  src/gui/guiEngine.cpp
Labels: @ Client / Audiovisuals, Bugfix, Trivial

#8174 Main menu: Fix cloud color (again)
  src/client/clientlauncher.cpp
  src/gui/guiEngine.cpp
Labels: @ Client rendering engine, One approval, Trivial

#8019 Use true pitch/yaw/roll rotations without loss of precision by pgimeno
  doc/lua_api.txt
  src/client/content_cao.cpp
  src/client/content_cao.h
  src/irrlichttypes_extrabloated.h
  src/network/networkprotocol.h
  src/unittest/test_utilities.cpp
  src/util/numeric.cpp
  src/util/numeric.h
Labels: >= Two approvals, Blocker, Bugfix, Feature, High priority

#8176 Prevent tooltip_append_itemname to append itemstring when it's not needed
  src/gui/guiFormSpecMenu.cpp
Labels: >= Two approvals, @ Client / Audiovisuals, Bugfix, Trivial

#8206 Remove fgettext("") in builtin
  builtin/mainmenu/tab_online.lua
Labels: One approval, Trivial

#8200 Autojump: Correctly disable in fly mode
  src/client/localplayer.cpp
Labels: @ Client / Controls / Input, Bugfix, One approval, Trivial

#8198 Slippery: Do not apply when swimming
  src/client/localplayer.cpp
Labels: @ Client / Controls / Input, Bugfix, One approval

#8167 Consistent HP and damage types
  src/client/client.cpp
  src/client/client.h
  src/client/clientenvironment.cpp
  src/client/clientenvironment.h
  src/client/content_cao.cpp
  src/client/content_cao.h
  src/client/hud.cpp
  src/content_sao.cpp
  src/content_sao.h
  src/database/database-files.cpp
  src/database/database-postgresql.cpp
  src/database/database-sqlite3.cpp
  src/genericobject.cpp
  src/genericobject.h
  src/network/serverpackethandler.cpp
  src/object_properties.cpp
  src/object_properties.h
  src/remoteplayer.cpp
  src/script/common/c_content.cpp
  src/script/cpp_api/s_entity.cpp
  src/script/cpp_api/s_player.cpp
  src/script/cpp_api/s_player.h
  src/script/lua_api/l_object.cpp
  src/server.cpp
  src/serverobject.h
Labels: @ Network, Blocker, Bugfix, Maintenance, One approval

#8221 Fix extract zip writing lowercase files
  src/script/lua_api/l_mainmenu.cpp
Labels: @ Content/PkgMgr, @ Script API, Blocker, Bugfix, High priority, One approval, Testing needed

#8230 Update minetest.conf.example and settings strings and locale files
  minetest.conf.example
  po/be/minetest.po
  po/ca/minetest.po
  po/cs/minetest.po
  po/da/minetest.po
  po/de/minetest.po
  po/dv/minetest.po
  po/eo/minetest.po
  po/es/minetest.po
  po/et/minetest.po
  po/fr/minetest.po
  po/he/minetest.po
  po/hu/minetest.po
  po/id/minetest.po
  po/it/minetest.po
  po/ja/minetest.po
  po/jbo/minetest.po
  po/kn/minetest.po
  po/ko/minetest.po
  po/ky/minetest.po
  po/lt/minetest.po
  po/minetest.pot
  po/ms/minetest.po
  po/nb/minetest.po
  po/nl/minetest.po
  po/pl/minetest.po
  po/pt/minetest.po
  po/pt_BR/minetest.po
  po/ro/minetest.po
  po/ru/minetest.po
  po/sl/minetest.po
  po/sr_Cyrl/minetest.po
  po/sv/minetest.po
  po/sw/minetest.po
  po/tr/minetest.po
  po/uk/minetest.po
  po/zh_CN/minetest.po
  po/zh_TW/minetest.po
  src/settings_translation_file.cpp
Labels: >= Two approvals, @ Translation, Blocker, High priority

#8218 Don't regain breath while in ignore node
  src/content_sao.cpp
Labels: >= Two approvals, Bugfix

#8181 Fix coloured fog in main menu
  src/gui/guiEngine.cpp
Labels: @ Client / Audiovisuals, Bugfix, One approval

#8187 Revert "RTT fixes (#7428)"
  src/client/client.cpp
  src/network/connection.cpp
  src/network/connection.h
  src/network/connectionthreads.cpp
  src/network/peerhandler.h
Labels: >= Two approvals, Blocker, Bugfix, High priority

#8162 Update credits
  builtin/mainmenu/tab_credits.lua
Labels: Blocker, High priority, Maintenance, One approval

#8239 Fix profiler crash
  builtin/profiler/instrumentation.lua
Labels: >= Two approvals, @ Builtin, Blocker, Bugfix, High priority

#8245 lua_api.txt: Various additions and improvements, for MT 5.0.0
  doc/lua_api.txt
Labels: @ Documentation, Trivial

#8236 Update many things in Lua API docs
  doc/lua_api.txt
Labels: @ Documentation, One approval, Trivial

#8252 lua_api.txt, settingtypes.txt: Various improvements
  builtin/settingtypes.txt
  doc/lua_api.txt
Labels: @ Documentation, Trivial

#8244 Fix content store crash
  builtin/mainmenu/dlg_contentstore.lua
Labels: @ Content/PkgMgr, Blocker, Bugfix, High priority, One approval

#8192 Update gamebar on tab enter
  builtin/mainmenu/init.lua
  builtin/mainmenu/tab_local.lua
Labels: >= Two approvals, @ Mainmenu, Blocker, Bugfix, High priority

#8270 Content store: ignore _game in game names in ID generation
  builtin/mainmenu/dlg_contentstore.lua
Labels: @ Content/PkgMgr, Blocker, Bugfix, High priority, One approval, Trivial

#8272 Fix typo in automatic forward setting
  builtin/settingtypes.txt
  src/client/game.cpp
  src/settings_translation_file.cpp
Labels: @ Documentation, One approval, Trivial

#8276 Attend to LINT sillyness
  src/network/address.cpp
  util/travis/clang-format-whitelist.txt
Labels: Maintenance, Trivial

#8277 Settingtypes.txt: Remove 2 lines missed in a recent commit
  builtin/settingtypes.txt
Labels: @ Documentation, Trivial

#8280 Fix files with CRLF line endings in translations
  src/translation.cpp
Labels: >= Two approvals, @ Client / Audiovisuals, @ Translation, Blocker, Bugfix, Trivial

#8278 Update minetest.conf.example and settings_translation_file.cpp
  builtin/mainmenu/dlg_settings_advanced.lua
  builtin/mainmenu/generate_from_settingtypes.lua
  minetest.conf.example
  src/settings_translation_file.cpp
Labels: @ Documentation, @ Translation, Blocker, High priority, Trivial

#8288 Revert CSM particles commit to fix bug for 5.0.0
  build/android/jni/Android.mk
  doc/client_lua_api.txt
  src/client/client.h
  src/client/particles.h
  src/network/clientpackethandler.cpp
  src/script/lua_api/CMakeLists.txt
  src/script/lua_api/l_particles_local.cpp
  src/script/lua_api/l_particles_local.h
  src/script/scripting_client.cpp
  util/travis/clang-format-whitelist.txt
Labels: @ Client Script API, Blocker, Bugfix, High priority, One approval
