Repository luanti-org/luanti, pull requests merged in 2019-07, with the labels that each got.

#8650 Update biome definition dungeon node documentation
  doc/lua_api.txt
Labels: @ Documentation, @ Mapgen, Trivial

#8659 Document ObjectRef:remove under Lua entity methods
  doc/lua_api.txt
Labels: @ Documentation, Trivial

#8639 Do predict when sneak-place to node with on_rightclick
  src/client/game.cpp
Labels: >= Two approvals, @ Script API, Bugfix

#8653 Move more dungeon parameter selection to mapgens
  src/mapgen/dungeongen.cpp
  src/mapgen/dungeongen.h
  src/mapgen/mapgen.cpp
  src/mapgen/mapgen_v6.cpp
Labels: @ Mapgen, Feature, Maintenance, One approval

#8675 Docs: Clarify where to check for 'protection_bypass'
  builtin/game/item.lua
  doc/lua_api.txt
Labels: @ Documentation, Maintenance, One approval

#8678 Dungeons: Make multiple large rooms possible
  src/mapgen/dungeongen.cpp
  src/mapgen/dungeongen.h
  src/mapgen/mapgen.cpp
  src/mapgen/mapgen_v6.cpp
Labels: @ Mapgen, Feature, One approval

#8692 Document the deprecation of hardcoded cave liquids
  builtin/settingtypes.txt
  src/mapgen/cavegen.cpp
  src/mapgen/cavegen.h
  src/mapgen/mapgen.h
Labels: @ Documentation, @ Mapgen, Trivial

#8693 Improve documentation of mapgen aliases
  doc/lua_api.txt
Labels: @ Documentation, @ Mapgen, Trivial

#8385 Add /help formspec for commands and privileges
  builtin/common/chatcommands.lua
  builtin/common/information_formspecs.lua
  builtin/game/init.lua
Labels: @ Builtin, Feature, One approval

#8700 Update README.md
  README.md
Labels: @ Documentation, Maintenance, One approval, Trivial

#8707 Removed debug.upvaluejoin to prevent leak of insecure environment
  src/script/cpp_api/s_security.cpp
Labels: >= Two approvals, @ Script API, Bugfix, High priority

#8702 Mgfractal: Make non-fractal terrain optional
  builtin/settingtypes.txt
  src/mapgen/mapgen_fractal.cpp
  src/mapgen/mapgen_fractal.h
Labels: @ Mapgen, Feature, One approval

#8705 Re-order mapgens in mainmenu and 'all settings' mapgen selection
  builtin/settingtypes.txt
  src/mapgen/mapgen.cpp
  src/mapgen/mapgen.h
Labels: @ Mainmenu, @ Mapgen, Maintenance, One approval

#8715 Initialise 'seabed_height' to avoid compilation warning
  src/mapgen/mapgen_fractal.cpp
Labels: @ Build, @ Mapgen, Bugfix, Trivial

#8694 Document 'wield_item' entity property
  doc/lua_api.txt
Labels: @ Documentation, One approval, Trivial

#8652 Fix missing item images clipping in formspecs
  src/client/hud.cpp
Labels: >= Two approvals, Bugfix, Formspec

#8711 guiScrollBar: move directly to clicked pos if clicked into tray
  src/gui/guiScrollBar.cpp
  src/gui/guiScrollBar.h
Labels: >= Two approvals, @ Client / Audiovisuals, Feature

#8713 lua_api.txt clarifications regarding mapgen object index IDs and handles.
  doc/lua_api.txt
Labels: >= Two approvals, @ Documentation

#8701 ContentCAO: Fix broken attachments on join
  src/activeobject.h
  src/client/clientenvironment.cpp
  src/client/clientenvironment.h
  src/client/clientobject.h
  src/client/content_cao.cpp
  src/client/content_cao.h
  src/content_sao.cpp
  src/content_sao.h
  src/serverobject.h
Labels: @ Client / Audiovisuals, Bugfix, One approval

#8717 Rename guiScrollBar to GUIScrollBar
  src/gui/guiEditBoxWithScrollbar.cpp
  src/gui/guiEditBoxWithScrollbar.h
  src/gui/guiScrollBar.cpp
  src/gui/guiScrollBar.h
  src/gui/guiTable.cpp
  src/gui/guiTable.h
  src/gui/intlGUIEditBox.cpp
  src/gui/intlGUIEditBox.h
Labels: Code quality, Maintenance, One approval, Trivial

#8699 README: make -j$(nproc)
  README.md
Labels: @ Documentation, One approval, Trivial

#8689 Don't unnecessarily clamp HP and breath to their maximums in set_properties().
  src/content_sao.cpp
  src/script/common/c_content.cpp
  src/script/common/c_content.h
  src/script/cpp_api/s_entity.cpp
  src/script/cpp_api/s_entity.h
  src/script/lua_api/l_object.cpp
Labels: >= Two approvals, @ Script API, Bugfix

#8683 Refactor of moon and sun drawing
  src/client/sky.cpp
  src/client/sky.h
Labels: >= Two approvals, @ Client / Audiovisuals, Maintenance

#8724 Silence invalid clang format warnings in guiScrollBar.cpp
  util/travis/clang-format-whitelist.txt
Labels: @ Build, Maintenance, Trivial

#8723 Allow toolcaps to override the built-in times for dig_immediate
  src/tool.cpp
Labels: @ Script API, Feature, One approval, Trivial
