Repository luanti-org/luanti, pull requests merged in 2019-01, with the labels that each got.

#8041 delete repeated text
  builtin/settingtypes.txt
  minetest.conf.example
Labels: @ Documentation, Trivial

#8000 CSM restrictions: Make 'LOAD_CLIENT_MODS' disable loading of 'builtin'
  builtin/settingtypes.txt
  src/client/client.cpp
  src/client/game.cpp
  src/network/networkprotocol.h
Labels: @ Client Script API, Blocker, Feature, High priority, One approval

#8030 Proselytize the network. Use IEEE F32
  doc/lua_api.txt
  src/client/content_cao.cpp
  src/content_sao.cpp
  src/genericobject.cpp
  src/itemdef.cpp
  src/mapblock.cpp
  src/network/clientpackethandler.cpp
  src/network/networkpacket.cpp
  src/network/networkprotocol.h
  src/nodedef.cpp
  src/nodedef.h
  src/object_properties.cpp
  src/object_properties.h
  src/script/common/c_content.cpp
  src/sound.h
  src/tileanimation.cpp
  src/tool.cpp
  src/unittest/test_serialization.cpp
  src/util/serialize.h
Labels: @ Network, Blocker, High priority, Maintenance, One approval

#8043 Make sqlite3 default auth & player backends for new worlds
  src/serverenvironment.cpp
Labels: >= Two approvals, @ Server / Client / Env., Blocker, High priority

#8047 Drop libgmp on Android and use mini-gmp
  build/android/Makefile
  build/android/jni/Android.mk
  build/android/src/main/java/net.minetest.minetest/MtNativeActivity.java
  src/util/srp.cpp
Labels: Android

#8060 Content store: Disable more details dialog for now
  builtin/mainmenu/dlg_contentstore.lua
Labels: @ Content/PkgMgr, One approval, Trivial

#8070 Fix a crash on Android with Align2Npot2
  src/client/tile.cpp
Labels: Android, Bugfix, One approval

#8066 Settingtypes.txt: Rewrite misleading documentation of 'num_emerge_threads'
  builtin/settingtypes.txt
Labels: @ Documentation, Trivial

#8085 Make sqlite3 the default auth backend for new worlds
  src/content/subgames.cpp
Labels: Blocker, High priority

#8092 Fix fake LINT check success
  util/travis/lint.sh
Labels: Bugfix, Code quality

#8100 Optimize path finalization in pathfinder
  src/pathfinder.cpp
Labels: Performance

#8097 Speed up the craft definition handling
  src/craftdef.cpp
Labels: Performance, Trivial

#8096 Optimize subgames search a little bit
  src/content/subgames.cpp
Labels: Performance

#8086 Remove incorrect feature flag 'chat_send_player_param3' and document versions
  builtin/game/features.lua
  doc/lua_api.txt
Labels: >= Two approvals, @ Documentation, Maintenance

#8062 Fix a couple of typos in builtin and collect some forgotten strings in noise/vector settings dialog
  builtin/mainmenu/dlg_create_world.lua
  builtin/mainmenu/dlg_settings_advanced.lua
  builtin/mainmenu/pkgmgr.lua
  builtin/settingtypes.txt
  minetest.conf.example
Labels: >= Two approvals, @ Documentation, @ Translation, Bugfix, Maintenance

#8091 Fix randomly rejected form field submits
  src/server.cpp
Labels: Bugfix, One approval

#8122 Fix warnings about dungeongen.cpp memcpy() and unused variable in MapBlock::deSerializeNetworkSpecific()
  src/mapblock.cpp
  src/mapgen/dungeongen.cpp
Labels: Maintenance, One approval

#8127 blitToVManip: Check out-of-bounds using node position not index
  src/mapgen/mg_schematic.cpp
Labels: @ Mapgen, Bugfix, One approval

#8113 Fix pkgmgr game install with RUN_IN_PLACE=0
  src/script/lua_api/l_mainmenu.cpp
  src/script/lua_api/l_mainmenu.h
Labels: >= Two approvals, Bugfix

#8131 Rename 'Advanced Settings' button to 'All Settings'
  builtin/mainmenu/tab_settings.lua
Labels: @ Mainmenu, One approval, Trivial

#8054 Content store: Use composite key to track installations
  builtin/mainmenu/dlg_contentstore.lua
Labels: @ Content/PkgMgr, Blocker, Bugfix, Feature, High priority, One approval

#8137 Content store: Fix storage leak by storing screenshots in cache
  builtin/mainmenu/dlg_contentstore.lua
  doc/menu_lua_api.txt
  src/script/lua_api/l_mainmenu.cpp
  src/script/lua_api/l_mainmenu.h
Labels: @ Content/PkgMgr, Blocker, Bugfix, High priority, One approval
