Repository luanti-org/luanti, pull requests merged in 2019-09, with the labels that each got.

#8878 Various fixes to lua_api.txt
  doc/lua_api.txt
Labels: @ Documentation, One approval

#7847 Don't use separate checkbox to disable flag
  builtin/mainmenu/dlg_settings_advanced.lua
  builtin/settingtypes.txt
  src/defaultsettings.cpp
Labels: >= Two approvals, @ Mainmenu, @ Mapgen, Maintenance

#8884 Inventory: Handle removeItem leftovers
  src/inventory.cpp
Labels: Bugfix, One approval

#8895 Fix Inventory::moveItemSomewhere()
  src/inventory.cpp
Labels: @ Server / Client / Env., Bugfix, One approval, Trivial

#8885 Force item entities out of solid nodes (simpler)
  builtin/game/item_entity.lua
Labels: @ Builtin, Feature, One approval

#8822 doc/client_lua_api : clarify how client side api+a mod starts
  doc/client_lua_api.txt
Labels: @ Client Script API, @ Documentation, One approval

#8904 Move debug.txt after it grows too big
  builtin/settingtypes.txt
  src/defaultsettings.cpp
  src/log.cpp
  src/log.h
  src/main.cpp
Labels: >= Two approvals, Feature

#8912 lua_api.txt: Improve privilege definition docs
  doc/lua_api.txt
Labels: @ Documentation, One approval, Trivial

#8914 Lua API documentation: Various fixes:
  doc/client_lua_api.txt
  doc/lua_api.txt
Labels: @ Documentation, One approval

#8897 Dungeons: Remove non-functional 'projecting dungeons' setting
  builtin/settingtypes.txt
  src/defaultsettings.cpp
  src/mapgen/dungeongen.cpp
Labels: @ Mapgen, Maintenance, Trivial

#8918 Dungeons: Clean up parameters, improve structure variety
  src/mapgen/dungeongen.h
  src/mapgen/mapgen.cpp
Labels: @ Mapgen, Feature, Maintenance, One approval

#8716 Fix the bgcolor formspec element
  doc/lua_api.txt
  src/gui/guiFormSpecMenu.cpp
Labels: >= Two approvals, @ Client / Audiovisuals, Formspec

#8945 Inventory: Properly revert client predictions
  src/inventory.cpp
  src/inventory.h
  src/inventorymanager.cpp
Labels: @ Server / Client / Env., Bugfix, One approval

#8799 Fix misuse of AsyncTask
  build/android/src/main/java/net.minetest.minetest/MinetestAssetCopy.java
Labels: Android, Bugfix, One approval

#8869 Also print help commands to chat for server terminal
  builtin/common/chatcommands.lua
  builtin/common/information_formspecs.lua
Labels: @ Builtin, Bugfix, One approval

#8640 Trigger on_place in many situations even if prediction failed
  src/client/game.cpp
Labels: >= Two approvals, @ Script API, Bugfix

#7557 Add support for per-player FOV overrides and multipliers
  doc/lua_api.txt
  src/client/camera.cpp
  src/client/client.h
  src/client/game.cpp
  src/network/clientopcodes.cpp
  src/network/clientpackethandler.cpp
  src/network/networkprotocol.h
  src/network/serveropcodes.cpp
  src/player.h
  src/script/lua_api/l_object.cpp
  src/script/lua_api/l_object.h
  src/server.cpp
  src/server.h
Labels: >= Two approvals, @ Client / Audiovisuals, @ Script API, Feature

#8961 Wieldhand: Specify which ItemStack to use
  doc/lua_api.txt
  src/content_sao.cpp
  src/content_sao.h
  src/network/serverpackethandler.cpp
  src/script/lua_api/l_object.cpp
  src/serverobject.cpp
  src/serverobject.h
Labels: Bugfix, One approval

#8888 Fix AreaStore's IDs persistence
  builtin/game/features.lua
  doc/lua_api.txt
  src/script/lua_api/l_areastore.cpp
  src/unittest/test_areastore.cpp
  src/util/areastore.cpp
  src/util/areastore.h
Labels: @ Script API, Bugfix, One approval

#8959 Punchwear (improved)
  builtin/game/register.lua
  doc/lua_api.txt
  src/content_sao.cpp
  src/content_sao.h
  src/network/serverpackethandler.cpp
  src/script/common/c_content.cpp
  src/script/lua_api/l_object.cpp
  src/serverobject.h
  src/tool.cpp
  src/tool.h
Labels: Feature, One approval

#8960 Move the code for meta formspec into Game::nodePlacement
  src/client/game.cpp
Labels: Feature, One approval

#8971 Rename "private messages" to "direct messages"
  builtin/game/chat.lua
Labels: Bugfix, One approval, Trivial

#8981 Fix some reference counters (memleak)
  src/client/fontengine.cpp
  src/gui/guiFormSpecMenu.cpp
  src/map.cpp
  src/map.h
  src/mapgen/mg_schematic.cpp
  src/mapgen/treegen.cpp
  src/rollback_interface.cpp
  src/script/lua_api/l_env.cpp
  src/script/lua_api/l_nodemeta.cpp
  src/script/lua_api/l_vmanip.cpp
  src/server.cpp
  src/server.h
Labels: Bugfix, Code quality, One approval

#3473 Automatically enable depends of mods when enabling the mods in the world config menu
  builtin/mainmenu/pkgmgr.lua
Labels: >= Two approvals, @ Client / Audiovisuals, @ Startup / Config / Util

#8991 Simple shader fixes.
  client/shaders/nodes_shader/opengl_fragment.glsl
  client/shaders/nodes_shader/opengl_vertex.glsl
  src/client/game.cpp
Labels: Bugfix, One approval, Shaders

#8997 Advanced settings: Count only flags without "no" prefix
  builtin/mainmenu/dlg_settings_advanced.lua
  builtin/settingtypes.txt
Labels: >= Two approvals, Bugfix

#8958 Allow grep-ing for on_grant and on_revoke
  builtin/game/chat.lua
Labels: Maintenance, Trivial

#8922 Fix error message caused by adding new parameter to background
  doc/lua_api.txt
  src/gui/guiFormSpecMenu.cpp
Labels: @ Client / Audiovisuals, Bugfix, Formspec, High priority, One approval, Trivial

#8871 Move Quicktune code to util/
  build/android/jni/Android.mk
  src/CMakeLists.txt
  src/client/game.cpp
  src/main.cpp
  src/util/CMakeLists.txt
  src/util/quicktune.cpp
  src/util/quicktune.h
  src/util/quicktune_shortcutter.h
  util/travis/clang-format-whitelist.txt
Labels: Maintenance, One approval, Trivial

#8974 Textures: Load base pack only as last fallback
  src/client/tile.cpp
  src/client/tile.h
Labels: Bugfix, One approval, Textures

#9009 Document node drop tool filtering as deprecated
  doc/lua_api.txt
Labels: @ Documentation, Trivial
