Repository luanti-org/luanti, pull requests merged in 2019-08, with the labels that each got.

#8682 Make players immortal using immortal=1
  builtin/game/statbars.lua
  doc/lua_api.txt
  src/content_sao.cpp
  src/content_sao.h
  src/server.cpp
Labels: >= Two approvals, Feature

#8733 Correct ServerActiveObject's virtual getArmorGroups() to be const.
  src/serverobject.h
Labels: >= Two approvals, Bugfix

#8754 Update curl dependency in buildbot
  util/buildbot/buildwin32.sh
  util/buildbot/buildwin64.sh
Labels: Bugfix, One approval, Windows

#8756 Mapgen Flat: Fix and improve getSpawnLevelAtPoint()
  src/mapgen/mapgen_flat.cpp
Labels: @ Mapgen, Bugfix, Maintenance, Trivial

#7895 Add luacheck to check builtin
  .luacheckrc
  builtin/client/chatcommands.lua
  builtin/common/filterlist.lua
  builtin/common/information_formspecs.lua
  builtin/common/misc_helpers.lua
  builtin/common/serialize.lua
  builtin/game/chatcommands.lua
  builtin/game/forceloading.lua
  builtin/game/item.lua
  builtin/game/misc.lua
  builtin/game/privileges.lua
  builtin/game/register.lua
  builtin/game/statbars.lua
  builtin/mainmenu/common.lua
  builtin/mainmenu/dlg_contentstore.lua
  builtin/mainmenu/dlg_create_world.lua
  builtin/mainmenu/dlg_settings_advanced.lua
  builtin/mainmenu/pkgmgr.lua
  builtin/mainmenu/tab_local.lua
  builtin/mainmenu/tab_online.lua
  builtin/mainmenu/tab_settings.lua
  builtin/mainmenu/tab_simple_main.lua
  builtin/mainmenu/textures.lua
  builtin/profiler/instrumentation.lua
Labels: @ Mainmenu, Feature, One approval

#8641 Clean up and fix freetype=false crashes
  src/client/fontengine.cpp
  src/client/fontengine.h
  src/gui/guiChatConsole.cpp
  src/irrlicht_changes/static_text.cpp
Labels: Bugfix, Maintenance, One approval

#8751 Do not add group values of zero to group lists.
  src/script/common/c_content.cpp
Labels: >= Two approvals, @ Server / Client / Env., Bugfix

#8759 Optimize usage of TOSERVER_GOTBLOCKS packet
  src/client/client.cpp
  src/client/client.h
Labels: @ Network, Bugfix, One approval, Performance

#8433 Fix/Add inventory_overlay for nodes without inventory_image
  src/client/hud.cpp
Labels: @ Client / Audiovisuals, Bugfix, One approval

#8656 Hide chat when console is open
  src/client/game.cpp
  src/client/gameui.cpp
  src/client/gameui.h
Labels: >= Two approvals, @ Client / Audiovisuals

#8761 guiConfirmRegistration: Automatically set focus to password field
  src/gui/guiConfirmRegistration.cpp
Labels: @ Client / Controls / Input, One approval, Trivial

#8677 Unify wield item handling
  src/client/client.cpp
  src/client/client.h
  src/client/game.cpp
  src/client/render/core.cpp
  src/content_sao.cpp
  src/content_sao.h
  src/network/serverpackethandler.cpp
  src/player.cpp
  src/player.h
  src/script/lua_api/l_client.cpp
  src/script/lua_api/l_object.cpp
  src/serverobject.h
  src/tool.cpp
  src/tool.h
Labels: @ Server / Client / Env., Code quality, Maintenance, One approval

#8762 Fix usage of wrong variable in builtin chat command handling.
  builtin/game/chatcommands.lua
Labels: Bugfix, Trivial

#8728 Avoid crash caused by, and improve, 'findSpawnPos()'
  src/server.cpp
Labels: >= Two approvals, @ Mapgen, Bugfix, Maintenance

#8765 guiVolumeChange: Fix child not being removed
  src/gui/guiVolumeChange.cpp
Labels: Bugfix, Trivial

#8529 Allow customizing chat message format
  builtin/game/chat.lua
  builtin/game/init.lua
  builtin/settingtypes.txt
  doc/lua_api.txt
  minetest.conf.example
  src/defaultsettings.cpp
  src/gettime.h
  src/script/cpp_api/s_server.cpp
  src/script/cpp_api/s_server.h
  src/server.cpp
Labels: >= Two approvals, @ Client / Audiovisuals, Feature, Rebase needed

#8776 Finish getNode cleanup
  src/client/camera.cpp
  src/client/client.cpp
  src/client/clientenvironment.cpp
  src/client/clientmap.cpp
  src/client/content_cao.cpp
  src/client/content_cso.cpp
  src/client/game.cpp
  src/client/gameui.cpp
  src/client/localplayer.cpp
  src/client/particles.cpp
  src/collision.cpp
  src/content_sao.cpp
  src/environment.cpp
  src/map.cpp
  src/map.h
  src/mapblock.cpp
  src/mapnode.cpp
  src/network/serverpackethandler.cpp
  src/pathfinder.cpp
  src/rollback_interface.cpp
  src/script/cpp_api/s_node.cpp
  src/script/cpp_api/s_nodemeta.cpp
  src/script/lua_api/l_env.cpp
  src/server.cpp
  src/serverenvironment.cpp
  src/voxelalgorithms.cpp
Labels: >= Two approvals, @ Server / Client / Env., Code quality

#8712 Fix some issues with minetest.clear_craft
  games/minimal/mods/test/crafting.lua
  games/minimal/mods/test/init.lua
  games/minimal/mods/test/player.lua
  src/craftdef.cpp
  src/craftdef.h
  src/script/lua_api/l_craft.cpp
Labels: @ Script API, Bugfix, One approval

#8774 Fix breakage of non-GLES2 setups
  src/CMakeLists.txt
Labels: >= Two approvals, @ Build, Bugfix, Linux

#8771 Update Gradle to 5.5.1
  .gitignore
  build/android/build.gradle
  build/android/gradle/wrapper/gradle-wrapper.properties
Labels: @ Build, Android, One approval

#4888 Handle multiple deserialization of a block's entities
  src/staticobject.cpp
Labels: @ Server / Client / Env., Bugfix, One approval

#8611 Add support for set_formspec_prepend in main menu
  doc/menu_lua_api.txt
  src/gui/guiEngine.cpp
  src/gui/guiEngine.h
  src/script/lua_api/l_mainmenu.cpp
  src/script/lua_api/l_mainmenu.h
Labels: @ Mainmenu, Feature, Formspec, One approval, Trivial

#8753 Clear old item groups when they are overridden.
  src/nodedef.cpp
  src/nodedef.h
Labels: >= Two approvals, @ Script API, Bugfix

#8789 Fix compare between pointer and 0 in unittests
  src/unittest/test.cpp
Labels: Code quality, One approval, Trivial

#8788 Fix unnecessary exception use in Map::isNodeUnderground
  src/map.cpp
Labels: >= Two approvals, Code quality, Maintenance

#8750 Better F6 profiler
  src/client/activeobjectmgr.cpp
  src/client/client.cpp
  src/client/clientenvironment.cpp
  src/client/clientmap.cpp
  src/client/clientmap.h
  src/client/clouds.cpp
  src/client/game.cpp
  src/client/gameui.cpp
  src/client/mapblock_mesh.cpp
  src/client/mesh_generator_thread.cpp
  src/collision.cpp
  src/emerge.cpp
  src/mapgen/mapgen.cpp
  src/network/connection.cpp
  src/profiler.cpp
  src/profiler.h
  src/server.cpp
  src/server/activeobjectmgr.cpp
  src/serverenvironment.cpp
Labels: @ Client / Audiovisuals, Code quality, One approval

#8792 Fix unnecessary exception use in Map::getSectorXXX
  src/client/clientmap.cpp
  src/map.cpp
  src/map.h
Labels: Code quality, One approval

#8791 Fix unnecessary exception use in 3 more methods
  src/map.cpp
  src/server.cpp
Labels: Code quality, One approval

#7251 Add function `minetest.read_schematic`
  doc/lua_api.txt
  src/script/lua_api/l_mapgen.cpp
  src/script/lua_api/l_mapgen.h
Labels: >= Two approvals, @ Script API, Feature

#8798 Do not make a warning because of global _
  builtin/mainmenu/dlg_create_world.lua
Labels: Code quality, Trivial

#8802 network: Fix crash in ReliablePacketBuffer on mismatching packets
  src/network/connection.cpp
Labels: @ Network, Bugfix, High priority, One approval

#8801 network: Stricter handling of split packets
  src/network/connection.cpp
Labels: @ Network, Bugfix, One approval

#8795 Mapgen v6: Fix mudflow iteration and iterate twice
  src/mapgen/mapgen_v6.cpp
Labels: @ Mapgen, Bugfix, One approval

#8804 Minor code refactoring in connection.cpp
  src/network/connection.cpp
  src/network/connection.h
Labels: @ Network, Maintenance, One approval

#8808 ClientInterface: Use recursive mutex to prevent freeze in on_newplayer()
  src/clientiface.cpp
  src/clientiface.h
Labels: @ Server / Client / Env., Bugfix, One approval

#8814 Find LuaJIT headers on vcpkg
  cmake/Modules/FindLuaJIT.cmake
Labels: Bugfix, One approval, Windows

#8819 Restore intended functionality to minimap markers
  src/client/minimap.cpp
Labels: >= Two approvals, @ Client / Audiovisuals, Bugfix

#8826 lua_api.txt: Add link to Minetest Modding Book
  doc/lua_api.txt
Labels: >= Two approvals, @ Documentation

#8823 Add player sprite textures back into the engine as a fallback
  textures/base/pack/player.png
  textures/base/pack/player_back.png
Labels: Maintenance, One approval, Textures

#8838 Make Mapgen::spreadLight use a queue
  src/mapgen/mapgen.cpp
  src/mapgen/mapgen.h
Labels: >= Two approvals, @ Mapgen, Bugfix, Performance

#8850 Restore approximate occlusion check
  src/map.cpp
  src/map.h
Labels: @ Client / Audiovisuals, Bugfix, One approval

#8844 Improve occlusion culling
  src/map.cpp
  src/map.h
Labels: @ Client / Audiovisuals, Feature, One approval

#8847 Add ItemStack:get_description() to get tooltip
  doc/lua_api.txt
  src/gui/guiFormSpecMenu.cpp
  src/inventory.cpp
  src/inventory.h
  src/script/lua_api/l_item.cpp
  src/script/lua_api/l_item.h
Labels: @ Script API, Feature, One approval

#8742 Inventory: Send dirty lists where appropriate
  src/client/client.cpp
  src/client/client.h
  src/client/game.cpp
  src/inventory.cpp
  src/inventory.h
  src/network/clientpackethandler.cpp
  src/network/networkprotocol.h
  src/network/serverpackethandler.cpp
  src/remoteplayer.h
  src/script/lua_api/l_object.cpp
  src/server.cpp
  src/server.h
  src/unittest/test_inventory.cpp
  src/unittest/test_servermodmanager.cpp
  src/unittest/test_world/do_not_remove.txt
  src/unittest/test_world/world.mt
Labels: Feature, One approval, Performance, Protocol bump

#8805 Mapgen v6: Various mudflow code improvements and bugfixes
  src/mapgen/mapgen_v6.cpp
Labels: @ Mapgen, Maintenance, One approval

#8867 Various settingtypes.txt improvements
  builtin/settingtypes.txt
Labels: @ Documentation, Trivial

#8766 Clarify docs regarding pointed_thing and get_pointed_thing_position.
  doc/lua_api.txt
Labels: @ Documentation, One approval, Trivial

#8864 Document luaent pitch and roll in world format
  doc/world_format.txt
Labels: @ Documentation, One approval, Trivial

#8857 Document world format version 28 (private nodemeta)
  doc/world_format.txt
Labels: @ Documentation, One approval
