Repository luanti-org/luanti, pull requests merged in 2019-12, with the labels that each got.

#9170 Fix android build due to omitted file in src files
  build/android/jni/Android.mk
Labels: Bugfix, Trivial

#8530 Add scrollbaroptions FormSpec element
  doc/lua_api.txt
  src/gui/guiFormSpecMenu.cpp
  src/gui/guiFormSpecMenu.h
  src/gui/guiScrollBar.cpp
  src/gui/guiScrollBar.h
Labels: >= Two approvals, @ Client / Audiovisuals, Feature, Formspec

#9150 Attachments: Fix interpolation from (0,0,0) after detach
  src/client/camera.cpp
  src/client/clientobject.h
  src/client/content_cao.cpp
  src/client/content_cao.h
  src/client/localplayer.cpp
  src/client/localplayer.h
  src/script/lua_api/l_localplayer.cpp
Labels: @ Client / Audiovisuals, Bugfix, One approval

#8813 Clean up craft replacements docs
  doc/lua_api.txt
  src/craftdef.h
  src/inventorymanager.cpp
Labels: @ Documentation, Maintenance, One approval

#8996 Formspec: make bgcolor element less confusing and allow setting fullscreen color
  doc/lua_api.txt
  src/gui/guiFormSpecMenu.cpp
  src/gui/guiFormSpecMenu.h
  src/network/networkprotocol.h
Labels: >= Two approvals, @ Client / Audiovisuals, Feature, Formspec

#9090 Refactor to centralize GUIButton styling/rendering code
  build/android/jni/Android.mk
  doc/lua_api.txt
  games/minimal/mods/test/formspec.lua
  games/minimal/mods/test/textures/test_bg.png
  games/minimal/mods/test/textures/test_bg_hovered.png
  games/minimal/mods/test/textures/test_bg_pressed.png
  src/gui/CMakeLists.txt
  src/gui/StyleSpec.h
  src/gui/guiButton.cpp
  src/gui/guiButton.h
  src/gui/guiButtonImage.cpp
  src/gui/guiButtonImage.h
  src/gui/guiButtonItemImage.cpp
  src/gui/guiButtonItemImage.h
  src/gui/guiFormSpecMenu.cpp
  src/gui/guiItemImage.cpp
  src/irrlicht_changes/static_text.cpp
  util/travis/clang-format-whitelist.txt
Labels: >= Two approvals, Formspec, Maintenance

#9206 Add Alpine build dependencies in README
  README.md
Labels: @ Documentation, One approval, Trivial

#9080 Lua API: Document HP limits
  doc/lua_api.txt
Labels: @ Documentation, Trivial

#9208 Correct documentation around minetest.item_place
  builtin/game/item.lua
  doc/lua_api.txt
Labels: @ Documentation, One approval, Trivial

#8697 Dockerfile: correct `apt clean` + git clone --depth 1 + remove .git
  Dockerfile
Labels: >= Two approvals, @ Documentation

#7713 Make core.item_place_node return position of placed node.
  builtin/game/item.lua
  doc/lua_api.txt
Labels: >= Two approvals, @ Builtin, @ Script API, Feature

#9200 Make dropped items glow
  builtin/game/item_entity.lua
Labels: @ Builtin, Feature, One approval, Trivial

#9224 /privs: Delimit output list of privs with commas
  builtin/game/chat.lua
Labels: One approval, Trivial

#8616 Fix the player information version_string return value
  src/clientiface.h
  src/server.cpp
Labels: @ Server / Client / Env., Bugfix, Trivial

#9236 Document permissible group ratings
  doc/lua_api.txt
Labels: One approval, Trivial

#9239 Fix item eat sound not played if last item
  builtin/game/item.lua
Labels: Bugfix, One approval, Trivial

#9230 Use appropriate locale macro for windows
  src/script/lua_api/l_client.cpp
Labels: @ Build, Bugfix, One approval, Trivial, Windows
