Repository luanti-org/luanti, pull requests merged in 2020-03, with the labels that each got.

#9380 Add multiple element selection to `style` and `style_type`
  doc/lua_api.txt
  games/minimal/mods/test/formspec.lua
  src/gui/guiFormSpecMenu.cpp
Labels: >= Two approvals, Feature, Formspec

#9455 Two fixes
  src/script/lua_api/l_env.cpp
Labels: Bugfix, Trivial

#9369 Fix potential security issue(s), documentation on minetest.deserialize()
  builtin/common/serialize.lua
  builtin/common/tests/serialize_spec.lua
  doc/lua_api.txt
Labels: >= Two approvals, @ Documentation, @ Script API, Bugfix

#9459 Fixes around ServerActiveObject on_punch handling
  doc/lua_api.txt
  src/content_sao.cpp
  src/network/serverpackethandler.cpp
Labels: @ Script API, Bugfix, One approval

#9465 Fix linking failures when compiled with Clang 9
  src/CMakeLists.txt
Labels: @ Build, Bugfix, Linux, One approval

#9466 Fix memory leak in protocol 38 set_sky
  src/network/clientpackethandler.cpp
Labels: Bugfix, Trivial

#9451 Cleanup global namespace pollution in builtin
  builtin/common/misc_helpers.lua
  builtin/mainmenu/pkgmgr.lua
Labels: >= Two approvals, @ Builtin, Maintenance

#9437 GUIHyperText: Fix bug with UTF-8 chars in action name
  src/gui/guiHyperText.cpp
  src/util/string.cpp
  src/util/string.h
Labels: >= Two approvals, Bugfix, Formspec

#9485 Improve arm physics
  src/client/camera.cpp
Labels: Maintenance, One approval

#9477 Fix 2 log messages when player joined to game
  src/server.cpp
Labels: One approval, Trivial

#9500 Remove unnecessary checks before delete
  src/map.cpp
  src/mapgen/mapgen_fractal.cpp
Labels: Code quality, Trivial

#9501 GUIFormSpecMenu: Remove field_close_on_enter warning
  src/gui/guiFormSpecMenu.cpp
Labels: Maintenance, One approval

#9493 Return empty table when minetest.get_connected_players() is called at load time
  src/script/lua_api/l_env.cpp
Labels: @ Script API, Blocker, Bugfix, One approval, Trivial

#9489 Fix memory leak in guihypertext
  src/gui/guiFormSpecMenu.cpp
  src/gui/guiHyperText.cpp
  src/gui/guiHyperText.h
Labels: >= Two approvals, Bugfix, Formspec

#9458 minetest.get_content_id: error on unknown node
  src/script/lua_api/l_item.cpp
Labels: >= Two approvals, @ Script API, Bugfix

#9503 Fix some chatcommands not returning a value
  builtin/common/information_formspecs.lua
  builtin/game/chat.lua
Labels: @ Builtin, Maintenance, One approval, Trivial

#9411 Add starting frame to `animated_image`
  doc/lua_api.txt
  games/minimal/mods/test/formspec.lua
  games/minimal/mods/test/textures/test_animation.jpg
  games/minimal/mods/test/textures/test_animation.png
  src/gui/guiAnimatedImage.cpp
  src/gui/guiAnimatedImage.h
  src/gui/guiFormSpecMenu.cpp
  src/gui/guiFormSpecMenu.h
Labels: >= Two approvals, Blocker, Feature, Formspec

#9519 Fix mouse events sent to wrong GUI elements when dragging
  src/gui/guiFormSpecMenu.cpp
Labels: Bugfix, Formspec, Trivial

#9515 Transform texture UVs with provided tex. matrix (#9481)
  client/shaders/object_shader/opengl_vertex.glsl
Labels: @ Client / Audiovisuals, Blocker, Bugfix, High priority, One approval

#9514 Fix entity lighting
  src/client/content_cao.cpp
  src/client/content_cao.h
Labels: @ Client / Audiovisuals, Blocker, Bugfix, High priority, One approval

#9510 Add comments for translators
  builtin/mainmenu/dlg_settings_advanced.lua
  builtin/mainmenu/tab_online.lua
  src/client/fontengine.cpp
  src/client/game.cpp
  src/client/keycode.cpp
  src/gui/modalMenu.cpp
  src/network/clientpackethandler.cpp
  util/updatepo.sh
Labels: @ Documentation, @ Translation, One approval

#9540 Smaller fix for falling nodes glow in the dark
  src/client/content_cao.cpp
Labels: >= Two approvals, Blocker, Bugfix

#9546 Fix small typos in lua_api.txt
  doc/lua_api.txt
Labels: @ Documentation, Bugfix, Trivial

#9550 Connection: Fix deadlock in debug mode
  src/network/connection.cpp
Labels: Bugfix, One approval

#9548 Fix alignment tags adding unwanted newlines
  src/gui/guiHyperText.cpp
  src/gui/guiHyperText.h
Labels: Blocker, Bugfix, Formspec, One approval

#9555 Improve documentation of minetest.get_node_drops()
  doc/lua_api.txt
Labels: @ Documentation, Trivial

#8749 Ignore near_plane setting on non-Android platforms
  builtin/settingtypes.txt
  minetest.conf.example
  src/client/camera.cpp
  src/defaultsettings.cpp
Labels: >= Two approvals, @ Client / Audiovisuals, @ Startup / Config / Util, Bugfix, High priority

#9559 Mark `hypertext` and markup language as unstable
  doc/lua_api.txt
Labels: @ Documentation, One approval

#9534 Fix GUI element click-through by changing visibility
  src/gui/guiFormSpecMenu.cpp
  src/gui/guiFormSpecMenu.h
Labels: >= Two approvals, Blocker, Bugfix, High priority
