Repository luanti-org/luanti, pull requests merged in 2020-12, with the labels that each got.

#9247 Fix MSAA stripes
  builtin/settingtypes.txt
  client/shaders/nodes_shader/opengl_fragment.glsl
  client/shaders/nodes_shader/opengl_vertex.glsl
  client/shaders/object_shader/opengl_fragment.glsl
  client/shaders/object_shader/opengl_vertex.glsl
Labels: >= Two approvals, Bugfix, Shaders

#10633 Cross-reference the node level manipulation functions
  doc/lua_api.txt
Labels: @ Documentation, One approval, Trivial

#10698 Revert "Increase limit for simultaneous blocks sent per client and the meshgen cache."
  builtin/settingtypes.txt
  src/defaultsettings.cpp
Labels: Bugfix, One approval

#10702 Implement mapblock camera offset correctly
  src/client/clientmap.cpp
  src/client/clientmap.h
  src/client/mapblock_mesh.cpp
  src/client/mapblock_mesh.h
Labels: >= Two approvals, @ Client rendering engine, Bugfix, Maintenance, Performance

#10692 Various documentation fixes
  doc/client_lua_api.txt
  doc/lua_api.txt
  games/devtest/mods/testnodes/nodeboxes.lua
Labels: @ Documentation, One approval

#10721 Revert "GUIFormSpecMenu: Shift+Click listring workaround for MacOS"
  src/gui/guiFormSpecMenu.cpp
Labels: Bug, Bugfix, One approval

#10152 Semi-transparent background for nametags
  games/devtest/mods/testentities/visuals.lua
  src/client/camera.cpp
Labels: >= Two approvals, @ Client / Audiovisuals, Feature

#10697 add mod_orgin to node def in lua_api.txt
  doc/lua_api.txt
Labels: >= Two approvals, @ Documentation

#10679 Formspec: Allow to specify frame loop for model[]
  doc/lua_api.txt
  src/gui/guiFormSpecMenu.cpp
  src/gui/guiScene.cpp
  src/gui/guiScene.h
Labels: >= Two approvals, Feature

#10715 Allow configuring block disk and net compression. Change default disk level.
  builtin/settingtypes.txt
  src/defaultsettings.cpp
  src/map.cpp
  src/map.h
  src/mapblock.cpp
  src/mapblock.h
  src/mapgen/mg_schematic.cpp
  src/mapnode.cpp
  src/mapnode.h
  src/server.cpp
Labels: Feature, One approval, Performance

#10592 Documentation for highest formspec_version[] and changelog
  doc/lua_api.txt
  src/network/networkprotocol.h
Labels: @ Documentation, One approval

#10445 Make installer create its own Minetest folder
  CMakeLists.txt
Labels: >= Two approvals, Maintenance, Windows

#10642 DevTest: Add item to test replace_with_item in item_eat
  games/devtest/mods/testfood/init.lua
  games/devtest/mods/testfood/textures/testfood_replace.png
Labels: >= Two approvals, Devtest game, Trivial

#10579 Add open user data button to main menu
  build/android/app/src/main/java/net/minetest/minetest/GameActivity.java
  builtin/mainmenu/tab_credits.lua
  doc/menu_lua_api.txt
  src/porting.cpp
  src/porting.h
  src/porting_android.cpp
  src/porting_android.h
  src/script/lua_api/l_mainmenu.cpp
  src/script/lua_api/l_mainmenu.h
Labels: @ Mainmenu, Feature, One approval, Testing needed

#10663 Cleanup shader generation code
  client/shaders/nodes_shader/opengl_fragment.glsl
  client/shaders/object_shader/opengl_fragment.glsl
  src/client/clientenvironment.cpp
  src/client/game.cpp
  src/client/hud.cpp
  src/client/minimap.cpp
  src/client/render/interlaced.cpp
  src/client/shader.cpp
  src/client/shader.h
  src/client/sky.cpp
  src/nodedef.cpp
Labels: >= Two approvals, Maintenance

#10363 [MainMenu] Add clear button and icon for search one.
  LICENSE.txt
  builtin/mainmenu/dlg_contentstore.lua
  builtin/mainmenu/tab_online.lua
  textures/base/pack/clear.png
  textures/base/pack/search.png
Labels: >= Two approvals, @ Mainmenu, Textures

#10624 Fix some more joystick issues
  builtin/settingtypes.txt
  minetest.conf.example
  src/client/game.cpp
  src/client/inputhandler.h
  src/client/joystick_controller.cpp
  src/client/joystick_controller.h
  src/defaultsettings.cpp
Labels: >= Two approvals, @ Client / Controls / Input, Bugfix

#10727 Fix GLES shader support after #9247
  client/shaders/nodes_shader/opengl_fragment.glsl
  client/shaders/nodes_shader/opengl_vertex.glsl
  client/shaders/object_shader/opengl_fragment.glsl
  client/shaders/object_shader/opengl_vertex.glsl
Labels: >= Two approvals, Bugfix

#10643 Fix falling node rotation of wallmounted nodebox/mesh
  builtin/game/falling.lua
Labels: >= Two approvals, Bugfix

#9997 Add dependency resolution to ContentDB
  builtin/mainmenu/dlg_contentstore.lua
  builtin/mainmenu/dlg_create_world.lua
  builtin/mainmenu/init.lua
  builtin/settingtypes.txt
Labels: @ Content/PkgMgr, @ Mainmenu, Feature, One approval

#10744 CI: fix build
  .github/workflows/build.yml
  util/ci/common.sh
Labels: Bugfix, One approval

#10734 Minor profiler fixes.
  src/client/clientmap.cpp
  src/profiler.cpp
Labels: >= Two approvals, Bugfix

#10745 Bunch of minor fixes
  CMakeLists.txt
  lib/lua/CMakeLists.txt
  src/CMakeLists.txt
  src/client/content_cao.cpp
  src/client/game.cpp
  src/client/hud.cpp
  src/client/mapblock_mesh.cpp
  src/client/tile.cpp
  src/filesys.cpp
  src/gui/touchscreengui.cpp
  src/irrlicht_changes/CGUITTFont.h
  src/irrlicht_changes/irrUString.h
  src/mapgen/mapgen_v7.cpp
  src/mapgen/treegen.cpp
  src/network/serverpackethandler.cpp
  src/nodedef.cpp
  src/script/cpp_api/s_security.cpp
  src/util/srp.cpp
  src/util/string.cpp
Labels: Bugfix, Code quality, One approval

#10748 Fix minetest.is_nan
  builtin/common/misc_helpers.lua
  src/script/lua_api/l_util.cpp
  src/script/lua_api/l_util.h
Labels: Bugfix, Trivial

#10751 Display Minetest header when menu_last_game value isn't available anymore
  builtin/mainmenu/init.lua
  builtin/mainmenu/tab_local.lua
Labels: Bugfix, One approval, Trivial

#10747 Fix item tooltip background color not working
  src/gui/guiFormSpecMenu.cpp
Labels: Bugfix, One approval

#10668 Add minetest.get_objects_in_area
  doc/lua_api.txt
  src/script/lua_api/l_env.cpp
  src/script/lua_api/l_env.h
  src/server/activeobjectmgr.cpp
  src/server/activeobjectmgr.h
  src/serverenvironment.h
Labels: @ Script API, Feature, One approval
