Repository luanti-org/luanti, pull requests merged in 2020-04, with the labels that each got.

#9561 Fix texture distortion on side-faces of flowing liquid nodes
  src/client/content_mapblock.cpp
Labels: >= Two approvals, @ Client / Audiovisuals, Bugfix

#9578 Add warning to set_sky() docs about unstable dawn and night sky colours
  doc/lua_api.txt
Labels: @ Documentation, @ Script API, Blocker, One approval

#9554 Fix 'the the' typos in comments
  src/mapgen/mapgen_valleys.cpp
  src/script/common/c_internal.cpp
Labels: @ Documentation, Maintenance, One approval, Trivial

#9583 Fix cursor still visible after closing formspec while on HyperText
  src/gui/guiHyperText.cpp
Labels: Bugfix, Formspec, One approval

#9591 Revert collision tweaks #9365 and #9327
  src/collision.cpp
Labels: >= Two approvals, @ Server / Client / Env., Blocker

#9594 Builtin: Make item entities glow less
  builtin/game/item_entity.lua
Labels: Bugfix, One approval, Trivial

#9582 Fix hovercolor not working in global tag
  src/gui/guiHyperText.cpp
Labels: Bugfix, Formspec, One approval

#9461 Some minor Lua API documentation clarifications
  doc/lua_api.txt
Labels: @ Documentation, One approval

#9263 Add allowed_mapgens option in game.conf.
  builtin/mainmenu/dlg_create_world.lua
  doc/lua_api.txt
Labels: >= Two approvals, @ Mapgen, Feature, One approval

#9521 Add tone mapping for entities
  client/shaders/object_shader/opengl_fragment.glsl
Labels: >= Two approvals, @ Client / Audiovisuals, Bugfix, Feature, Shaders

#9122 Allow relative directories for `screenshot_path`, tweak default path
  builtin/settingtypes.txt
  src/client/client.cpp
  src/defaultsettings.cpp
Labels: >= Two approvals, Feature

#9597 Clarify use of minetest.request_insecure_environment()
  doc/lua_api.txt
Labels: @ Documentation, Trivial

#9611 Miscellaneous networking improvements
  src/network/clientopcodes.cpp
  src/network/connection.cpp
  src/network/connection.h
  src/network/connectionthreads.cpp
  src/network/serveropcodes.cpp
Labels: @ Network, Bugfix, Maintenance, One approval

#9598 Overall improvements to log messages
  src/client/client.cpp
  src/client/client.h
  src/client/content_cao.cpp
  src/client/fontengine.cpp
  src/client/game.cpp
  src/client/renderingengine.cpp
  src/client/sound_openal.cpp
  src/client/tile.cpp
  src/content/subgames.cpp
  src/content_sao.cpp
  src/craftdef.cpp
  src/emerge.cpp
  src/itemdef.cpp
  src/main.cpp
  src/map.cpp
  src/network/clientpackethandler.cpp
  src/network/connectionthreads.cpp
  src/nodedef.cpp
  src/script/cpp_api/s_env.cpp
  src/script/lua_api/l_item.cpp
  src/server.cpp
  src/server/mods.cpp
Labels: Bugfix, Maintenance, One approval

#9614 Work around LuaJIT issues on aarch64
  src/CMakeLists.txt
  src/script/common/c_internal.h
  src/script/cpp_api/s_base.cpp
  src/script/cpp_api/s_security.cpp
  src/script/lua_api/l_base.cpp
Labels: @ Script API, Bugfix, One approval

#9604 Allow to select en as language in settings menu
  builtin/settingtypes.txt
Labels: >= Two approvals, @ Startup / Config / Util, @ Translation, Bugfix, Trivial

#9343 Collision various fixes
  src/client/localplayer.h
  src/collision.cpp
  src/collision.h
  src/unittest/test_collision.cpp
Labels: >= Two approvals, @ Server / Client / Env., Bugfix

#9619 Automated build changes
  .gitignore
  .gitlab-ci.yml
  Dockerfile
Labels: @ Build, One approval

#9618 Install the `locale` directory in a standard location without subfolder
  CMakeLists.txt
Labels: >= Two approvals, @ Translation, Bugfix

#9629 Drop genericobject.{cpp,h}
  build/android/jni/Android.mk
  src/CMakeLists.txt
  src/activeobject.h
  src/client/clientenvironment.cpp
  src/client/content_cao.cpp
  src/client/content_cao.h
  src/content_sao.cpp
  src/content_sao.h
  src/genericobject.cpp
  src/genericobject.h
  src/network/networkprotocol.h
  src/server.cpp
  src/serverenvironment.cpp
  src/serverobject.cpp
  src/serverobject.h
  util/travis/clang-format-whitelist.txt
Labels: One approval, Refactoring

#9630 Move clientsimpleobject.h to client folder
  src/client/clientsimpleobject.h
Labels: Refactoring, Trivial

#9579 Print error message if an invalid mapgen alias was detected
  src/mapgen/mapgen.cpp
  src/mapgen/mapgen_v6.cpp
  src/mapgen/treegen.cpp
Labels: >= Two approvals, @ Mapgen

#9639 Use TILE_MATERIAL_ALPHA for use_texture_alpha entity flag
  src/client/content_cao.cpp
Labels: >= Two approvals, Bugfix

#9642 Reduce ServerEnvironment propagation (helps pathfinder to become client side friendly)
  src/mapgen/treegen.cpp
  src/mapgen/treegen.h
  src/pathfinder.cpp
  src/pathfinder.h
  src/script/lua_api/l_env.cpp
  src/script/lua_api/l_nodetimer.cpp
  src/script/lua_api/l_nodetimer.h
Labels: @ Server / Client / Env., One approval, Refactoring

#9586 Implement DPI scaling for Windows
  misc/minetest.exe.manifest
  misc/winresource.rc
  src/CMakeLists.txt
  src/client/renderingengine.cpp
  src/constants.h
Labels: @ Client / Audiovisuals, Bugfix, Feature, One approval, Windows

#9622 Update API site build
  .gitlab-ci.yml
  doc/mkdocs/lua_highlight.patch
Labels: >= Two approvals, @ Documentation, Maintenance

#9378 Formspecs: Add state-selection to style elements
  doc/lua_api.txt
  games/minimal/mods/test/formspec.lua
  src/client/game.cpp
  src/gui/StyleSpec.h
  src/gui/guiButton.cpp
  src/gui/guiButton.h
  src/gui/guiButtonImage.cpp
  src/gui/guiButtonImage.h
  src/gui/guiButtonItemImage.cpp
  src/gui/guiButtonItemImage.h
  src/gui/guiConfirmRegistration.cpp
  src/gui/guiConfirmRegistration.h
  src/gui/guiFormSpecMenu.cpp
  src/gui/guiFormSpecMenu.h
  src/gui/guiKeyChangeMenu.cpp
  src/gui/guiKeyChangeMenu.h
  src/gui/guiPasswordChange.cpp
  src/gui/guiPasswordChange.h
  src/gui/guiVolumeChange.cpp
  src/gui/guiVolumeChange.h
  src/script/lua_api/l_mainmenu.cpp
  src/util/numeric.h
Labels: >= Two approvals, Feature, Formspec

#9480 Improve waypoints and add image variant
  doc/client_lua_api.txt
  doc/lua_api.txt
  src/client/hud.cpp
  src/client/hud.h
  src/hud.cpp
  src/hud.h
  src/script/common/c_content.cpp
Labels: >= Two approvals, @ Client / Audiovisuals, Feature

#9373 Play 'player_jump' when player jumps
  doc/lua_api.txt
  src/client/game.cpp
Labels: >= Two approvals, Feature, Sounds

#9566 Update copyright in README to 2020
  README.md
Labels: @ Documentation, One approval, Trivial

#9226 Dockerfile: use alpine to reduce size
  Dockerfile
Labels: >= Two approvals, @ Build, Maintenance

#9423 GUIFormSpecMenu: Add basic element highlighing debug feature
  src/gui/guiFormSpecMenu.cpp
  src/gui/guiFormSpecMenu.h
Labels: Feature, Formspec, One approval

#9101 Add scroll_container formspec element (redo)
  build/android/jni/Android.mk
  doc/lua_api.txt
  games/minimal/mods/test/formspec.lua
  src/gui/CMakeLists.txt
  src/gui/guiFormSpecMenu.cpp
  src/gui/guiFormSpecMenu.h
  src/gui/guiHyperText.cpp
  src/gui/guiHyperText.h
  src/gui/guiScrollContainer.cpp
  src/gui/guiScrollContainer.h
  src/network/networkprotocol.h
Labels: >= Two approvals, @ Client / Audiovisuals, Feature, Formspec

#8873 Add default stack size setting
  builtin/game/item.lua
  builtin/settingtypes.txt
  doc/lua_api.txt
Labels: >= Two approvals, Feature, User feedback needed

#9069 Remove sound menu and show proper messages if trying to change sound volume when sound if disabled/unsupported
  src/client/game.cpp
Labels: >= Two approvals, Sounds

#9600 Refactor texture overrides and add new features
  doc/texture_packs.txt
  src/CMakeLists.txt
  src/client/client.cpp
  src/itemdef.cpp
  src/itemdef.h
  src/nodedef.cpp
  src/nodedef.h
  src/server.cpp
  src/texture_override.cpp
  src/texture_override.h
  util/travis/clang-format-whitelist.txt
Labels: >= Two approvals, @ Client / Audiovisuals, Feature

#9669 scriptapi: Some small optimizations to value pushing
  src/script/common/c_content.cpp
  src/script/common/c_converter.cpp
  src/script/lua_api/l_env.cpp
  src/script/lua_api/l_mapgen.cpp
  src/script/lua_api/l_noise.cpp
  src/script/lua_api/l_object.cpp
  src/script/lua_api/l_vmanip.cpp
Labels: @ Script API, Maintenance, One approval, Performance

#9621 Update wireshark dissector
  util/wireshark/minetest.lua
Labels: Maintenance, One approval

#9603 Add all src folders to doxygen
  doc/Doxyfile.in
Labels: Bugfix, One approval

#9665 Verify database connection on interval
  src/database/database-postgresql.cpp
  src/database/database-postgresql.h
  src/database/database-sqlite3.cpp
  src/database/database-sqlite3.h
  src/database/database.h
  src/map.cpp
  src/map.h
  src/serverenvironment.cpp
  src/serverenvironment.h
Labels: Bugfix, One approval

#9674 Fix parsing JSON with large integers
  src/script/common/c_content.cpp
Labels: Bugfix, One approval, Trivial

#9671 Optimize get_objects_inside_radius calls
  src/collision.cpp
  src/script/lua_api/l_env.cpp
  src/server/activeobjectmgr.cpp
  src/server/activeobjectmgr.h
  src/serverenvironment.cpp
  src/serverenvironment.h
  src/unittest/test_serveractiveobjectmgr.cpp
Labels: One approval, Performance

#9682 Swap out -ffast-math for a safe subset of optimization flags
  src/CMakeLists.txt
  src/collision.cpp
Labels: @ Build, Bugfix, One approval

#9681 Camera: Fix shooting line offsets
  src/client/camera.cpp
  src/client/camera.h
  src/client/game.cpp
  src/client/localplayer.h
Labels: @ Client / Audiovisuals, Bugfix, One approval

#9685 Android: fix formspec input for AArch64 devices
  src/gui/guiFormSpecMenu.cpp
Labels: Android, Bugfix, One approval

#9676 Drop useless -Wabi flag
  src/CMakeLists.txt
Labels: @ Build, Bugfix, One approval

#9677 Add an option to disable unittest build, & disable them on Docker build
  CMakeLists.txt
  Dockerfile
  README.md
  src/CMakeLists.txt
  src/cmake_config.h.in
  src/main.cpp
Labels: @ Build, @ Unit Test, One approval

#9680 Rename "subgame" to "game" in 2 error messages
  src/main.cpp
Labels: >= Two approvals, Bugfix, Trivial

#9693 Document which noise APIs add world seed to noiseparams seed
  doc/lua_api.txt
Labels: @ Documentation, One approval

#9309 Android: fix handling non-latin characters on older Android devices
  src/server.cpp
  src/util/string.cpp
Labels: >= Two approvals, @ Translation, Android

#9689 serverpackethandler: Reduce pkt->getPeerId() invocations and more
  src/network/serverpackethandler.cpp
  src/server.h
Labels: Maintenance, One approval

#9699 Apply a scrollbar's default value to scroll containers
  games/minimal/mods/test/formspec.lua
  src/gui/guiScrollContainer.h
Labels: Bugfix, Formspec, Trivial

#9700 Formspec: allow lists to change size and existence while the formspec is open
  src/gui/guiFormSpecMenu.cpp
  src/gui/guiInventoryList.cpp
  src/gui/guiInventoryList.h
Labels: @ Client / Audiovisuals, Bugfix, One approval

#9698 script: Move SAO usability check so that it covers all functions
  src/script/lua_api/l_object.cpp
Labels: @ Script API, Bugfix

#9537 Reuse object_shader for "wielditem" and "item" entity drawtypes
  client/shaders/wielded_shader/opengl_fragment.glsl
  client/shaders/wielded_shader/opengl_vertex.glsl
  src/client/camera.cpp
  src/client/content_cao.cpp
  src/client/wieldmesh.cpp
  src/client/wieldmesh.h
Labels: Bugfix, One approval, Testing needed

#9712 Fix alias handling of get_content_id
  src/itemdef.cpp
  src/script/lua_api/l_item.cpp
Labels: Bugfix, One approval

#9641 Replace travis with github actions
  .github/workflows/build.yml
  .github/workflows/cpp_lint.yml
  .github/workflows/lua_lint.yml
  .gitlab-ci.yml
  .travis.yml
  README.md
  util/buildbot/buildwin32.sh
  util/buildbot/buildwin64.sh
  util/ci/build.sh
  util/ci/clang-format-whitelist.txt
  util/ci/clang-tidy.sh
  util/ci/common.sh
  util/ci/lint.sh
  util/ci/run-clang-tidy.py
  util/travis/before_install.sh
  util/travis/clangtidy.sh
  util/travis/script.sh
  util/travis/toolchain_mingw.cmake.in
Labels: @ Build, Maintenance, One approval

#9617 Improve protocol-level receiving code
  src/network/connection.cpp
  src/network/connectionthreads.cpp
  src/network/connectionthreads.h
Labels: @ Network, Maintenance, One approval

#9697 Fix configuration caching in log_deprecated
  src/script/common/c_internal.cpp
  src/script/lua_api/l_util.cpp
  src/script/lua_api/l_util.h
Labels: >= Two approvals, Bugfix

#9722 minetest.serialize: Reversible number serialization
  builtin/common/serialize.lua
  builtin/common/tests/serialize_spec.lua
Labels: @ Script API, Bugfix, One approval

#9715 Android: add OpenGL ES 2 support
  build/android/app/build.gradle
  build/android/build.gradle
  src/client/renderingengine.cpp
Labels: >= Two approvals, Android, Feature

#9730 Camera: Fix shootline line offsets II
  src/client/game.cpp
Labels: @ Client / Audiovisuals, Bugfix, One approval, Trivial

#9476 Add LevelDB auth database.
  src/database/database-leveldb.cpp
  src/database/database-leveldb.h
  src/serverenvironment.cpp
Labels: >= Two approvals, Feature

#9733 Add server side translations capability
  doc/lua_api.txt
  src/client/client.cpp
  src/client/game.cpp
  src/clientiface.h
  src/network/serverpackethandler.cpp
  src/script/lua_api/l_env.cpp
  src/script/lua_api/l_env.h
  src/script/lua_api/l_server.cpp
  src/server.cpp
  src/server.h
  src/translation.cpp
  src/translation.h
  src/util/string.cpp
  src/util/string.h
Labels: >= Two approvals, @ Script API, Feature

#9726 Simplify how parseElement splits element string
  src/gui/guiFormSpecMenu.cpp
Labels: Code quality, One approval

#9742 Fix gray screen on Lua error
  src/client/game.cpp
Labels: @ Server / Client / Env., Bugfix, One approval

#9713 mapblock_mesh: Optimize a few things
  src/client/mapblock_mesh.cpp
Labels: @ Client / Audiovisuals, One approval, Performance

#9724 FormSpec: Add `animated_image` to clickthrough elements
  src/gui/guiFormSpecMenu.cpp
Labels: Bugfix, Formspec, Trivial

#9577 Fix UpdateBonePosition() breaking animations
  src/client/content_cao.cpp
Labels: >= Two approvals, @ Client / Audiovisuals, Bugfix

#9737 Fix mapgen settings in minetest.conf being ignored
  src/map_settings_manager.cpp
Labels: @ Mapgen, Bugfix, One approval

#9584 Create new command 'revokeme <priv>'
  builtin/game/chat.lua
Labels: >= Two approvals, @ Builtin, Feature

#9756 Add PostgreSQL authentication backend
  src/database/database-postgresql.cpp
  src/database/database-postgresql.h
  src/serverenvironment.cpp
Labels: Authentication, Feature, One approval

#9748 Script: Enforce type checks if not nil
  src/script/common/c_content.cpp
  src/script/common/c_converter.cpp
  src/script/common/c_converter.h
  src/script/lua_api/l_inventory.cpp
Labels: @ Script API, Maintenance, One approval

#9762 Forbid object:attach(obj, ...)
  src/script/lua_api/l_object.cpp
Labels: @ Script API, Bugfix, One approval

#9765 Remove /LTCG from when compiling with clang-cl
  src/CMakeLists.txt
Labels: @ Build, One approval, Windows

#9750 cmake: Silence find_package_handle_standard_args warnings
  cmake/Modules/FindGettextLib.cmake
  cmake/Modules/FindJson.cmake
  cmake/Modules/FindLuaJIT.cmake
  cmake/Modules/FindVorbis.cmake
Labels: @ Build, Maintenance, One approval

#8271 Fix breath statbar scaling; defer breath_bar hiding by one second
  builtin/game/constants.lua
  builtin/game/statbars.lua
  src/constants.h
Labels: >= Two approvals, @ Builtin, Bugfix

#9772 Fix gettext detection and locale building (broken since a368e7e)
  src/CMakeLists.txt
Labels: Bugfix, Trivial
