Repository luanti-org/luanti, pull requests merged in 2020-02, with the labels that each got.

#9287 Formspec: create a new class for inventorylists
  build/android/jni/Android.mk
  doc/lua_api.txt
  src/gui/CMakeLists.txt
  src/gui/guiFormSpecMenu.cpp
  src/gui/guiFormSpecMenu.h
  src/gui/guiInventoryList.cpp
  src/gui/guiInventoryList.h
  util/travis/clang-format-whitelist.txt
Labels: >= Two approvals, Feature, Formspec

#6993 Add limit parameter to decompressZlib
  src/serialization.cpp
  src/serialization.h
  src/unittest/test_compression.cpp
Labels: >= Two approvals, Feature

#8299 Add table.shuffle
  builtin/common/misc_helpers.lua
  doc/lua_api.txt
Labels: >= Two approvals, @ Builtin, Feature

#9340 StaticText: reset background on EnrichedString change
  src/client/gameui.cpp
  src/irrlicht_changes/static_text.cpp
Labels: Bugfix, Low priority, One approval, User feedback needed

#9359 Warn of biome ID re-allocation when unregistering or clearing biomes
  doc/lua_api.txt
Labels: @ Documentation, @ Mapgen, Trivial

#9390 Script API: Check that SAOs are still usable before attempting to use them
  src/content_sao.cpp
  src/script/lua_api/l_object.cpp
  src/server.cpp
Labels: @ Script API, Bugfix, One approval

#9388 Update some libraries for buildbot
  util/buildbot/buildwin32.sh
  util/buildbot/buildwin64.sh
Labels: Maintenance, One approval, Windows

#9394 Throw an error when too many noise octaves
  src/noise.cpp
Labels: @ Mapgen, Bugfix, Maintenance, One approval

#9365 Collision detection tweak #2
  src/collision.cpp
Labels: >= Two approvals, @ Server / Client / Env., Bugfix, High priority

#9397 Add missing paramtype2 documentation
  doc/lua_api.txt
Labels: @ Documentation, @ Script API, One approval

#9396 Update embedded mini-gmp to version 6.2.0
  lib/gmp/mini-gmp.c
  lib/gmp/mini-gmp.h
Labels: >= Two approvals, Maintenance

#8282 Key settings: Clear with escape
  src/gui/guiKeyChangeMenu.cpp
  src/gui/guiKeyChangeMenu.h
Labels: @ Client / Controls / Input, Feature, One approval

#9258 GUIFormspecMenu: Add animated_image[] element
  build/android/jni/Android.mk
  doc/lua_api.txt
  games/minimal/mods/test/formspec.lua
  games/minimal/mods/test/textures/test_animation.jpg
  games/minimal/mods/test/textures/test_animation.png
  src/gui/CMakeLists.txt
  src/gui/guiAnimatedImage.cpp
  src/gui/guiAnimatedImage.h
  src/gui/guiFormSpecMenu.cpp
  src/gui/guiFormSpecMenu.h
  util/travis/clang-format-whitelist.txt
Labels: >= Two approvals, Feature, Formspec

#9374 Basic model shading
  client/shaders/object_shader/opengl_fragment.glsl
  client/shaders/object_shader/opengl_vertex.glsl
  src/client/client.cpp
  src/client/client.h
  src/client/clientenvironment.cpp
  src/client/content_cao.cpp
  src/client/content_cao.h
  src/client/shader.cpp
  src/client/shader.h
Labels: >= Two approvals, @ Client / Audiovisuals, Feature

#9404 Settings: Fix game minetest.conf flags overriding defaults
  src/content/subgames.cpp
  src/defaultsettings.cpp
  src/map_settings_manager.cpp
  src/settings.cpp
  src/settings.h
Labels: @ Startup / Config / Util, Bugfix, One approval

#9205 Falling nodes: Add support for facedir, colorfacedirr, wallmounted, colorwallmounted, color, airlike, signlike, torchlike and glow
  builtin/game/falling.lua
Labels: >= Two approvals, @ Builtin, Feature

#9415 Lua_api.txt: Add documentation of VoxelArea 'ystride', 'zstride'
  doc/lua_api.txt
Labels: @ Documentation, @ Mapgen, Trivial

#9431 Fix typo
  doc/lua_api.txt
Labels: @ Documentation, One approval, Trivial

#9271 Allow texture modifiers in hotbar textures.
  src/client/hud.cpp
  src/network/clientpackethandler.cpp
Labels: >= Two approvals, Bugfix, Feature, Textures

#9422 GUIInventoryList: fix dropping items when clicking outside of formspec window
  src/gui/guiInventoryList.cpp
Labels: Bugfix, Formspec, One approval
