Repository luanti-org/luanti, pull requests merged in 2020-08, with the labels that each got.

#10239 Fix GCC class-memaccess warnings
  src/client/mapblock_mesh.cpp
  src/noise.cpp
Labels: >= Two approvals, Code quality

#10256 Fix build for Visual Studio (explicitly cast pointers)
  src/util/md32_common.h
  src/util/sha256.c
Labels: Bugfix, Trivial

#10140 Implement override.txt support for special tiles
  doc/texture_packs.txt
  src/nodedef.cpp
  src/nodedef.h
  src/texture_override.cpp
  src/texture_override.h
  util/ci/lint.sh
Labels: >= Two approvals, Feature, Textures

#9913 Mapgen Flat: Add caverns, disabled by default
  builtin/mainmenu/dlg_create_world.lua
  builtin/settingtypes.txt
  src/mapgen/mapgen_flat.cpp
  src/mapgen/mapgen_flat.h
Labels: @ Mapgen, Feature, One approval

#10263 Change command `last-login`
  builtin/game/chat.lua
Labels: @ Builtin, One approval

#10203 Add font styling options to tables and textlists
  src/gui/guiFormSpecMenu.cpp
  src/gui/guiTable.cpp
  src/gui/guiTable.h
Labels: >= Two approvals, Feature, Formspec

#10186 Fix precision not working in hud_change
  games/devtest/mods/util_commands/init.lua
  src/hud.cpp
  src/script/common/c_content.cpp
Labels: Bugfix, One approval

#10122 Render nodeboxes + meshes with opaque material if possible
  doc/lua_api.txt
  src/nodedef.cpp
  src/nodedef.h
Labels: @ Client / Audiovisuals, One approval, Performance

#7924 Allow binding dig, place actions to keys; remove LMB/RMB hardcoding
  builtin/settingtypes.txt
  doc/client_lua_api.txt
  doc/lua_api.txt
  src/client/client.cpp
  src/client/content_cao.cpp
  src/client/game.cpp
  src/client/inputhandler.cpp
  src/client/inputhandler.h
  src/client/keys.h
  src/defaultsettings.cpp
  src/network/serverpackethandler.cpp
  src/player.h
  src/script/lua_api/l_localplayer.cpp
  src/script/lua_api/l_object.cpp
Labels: >= Two approvals, @ Client / Controls / Input, Feature

#9995 ContentDB: Add Update All and download queuing
  builtin/mainmenu/dlg_contentstore.lua
  builtin/settingtypes.txt
  src/defaultsettings.cpp
Labels: @ Content/PkgMgr, @ Mainmenu, Feature, One approval

#10290 Allow the ABM time budget to be configurable.
  builtin/settingtypes.txt
  src/defaultsettings.cpp
  src/environment.cpp
  src/environment.h
  src/serverenvironment.cpp
Labels: Feature, One approval

#10119 Clean up sound_fade
  doc/lua_api.txt
  src/client/sound_openal.cpp
Labels: >= Two approvals, Code quality, Sounds

#10144 FormSpec: Optimize formspec form size
  src/gui/guiFormSpecMenu.cpp
Labels: Formspec, One approval

#8676 Add gradients and borders to FormSpec boxes
  doc/lua_api.txt
  src/gui/StyleSpec.h
  src/gui/guiBox.cpp
  src/gui/guiBox.h
  src/gui/guiFormSpecMenu.cpp
Labels: Feature, Formspec, One approval

#10296 Fix missing #10286 - Translated strings in hypertext fields are broken if they contain spaces
  src/gui/guiFormSpecMenu.cpp
Labels: @ Client / Audiovisuals, Bugfix, One approval, Trivial

#10302 define environ variable on OpenBSD
  src/porting.cpp
Labels: Bugfix, One approval, Trivial

#9065 Load media from subfolders
  doc/lua_api.txt
  games/devtest/mods/basenodes/textures/dirt_with_grass/default_grass.png
  games/devtest/mods/basenodes/textures/dirt_with_grass/default_grass_side.png
  games/devtest/mods/basenodes/textures/dirt_with_grass/info.txt
  src/server.cpp
  src/server/mods.cpp
  src/unittest/test_servermodmanager.cpp
Labels: >= Two approvals, Feature

#10095 Avoid drawing clipped out formspec elements
  src/gui/guiFormSpecMenu.cpp
  src/gui/guiScrollContainer.cpp
  src/gui/guiScrollContainer.h
Labels: @ Client / Audiovisuals, Formspec, One approval, Performance

#10299 make maintab text readable
  src/gui/guiSkin.cpp
Labels: >= Two approvals, @ Mainmenu

#10314 Properly handle mod-errors in on_shutdown
  src/client/game.cpp
  src/server.cpp
  src/server.h
Labels: >= Two approvals, Bugfix, One approval

#10036 fix transparency on GC7000L where mesa doesn't implement GL_ALPHA_TEST
  client/shaders/nodes_shader/opengl_fragment.glsl
  client/shaders/object_shader/opengl_fragment.glsl
  src/client/shader.cpp
Labels: >= Two approvals, @ Client / Audiovisuals, Bugfix, Shaders

#10308 NetBSD build fix proposal.
  src/noise.h
  src/threading/thread.cpp
Labels: Bugfix, One approval

#10227 Android: drop simple MainMenu
  builtin/mainmenu/init.lua
  builtin/mainmenu/tab_settings.lua
  builtin/mainmenu/tab_simple_main.lua
  builtin/settingtypes.txt
  src/defaultsettings.cpp
Labels: >= Two approvals, @ Mainmenu, Android

#10338 Open get_texture_mod to lua api
  src/script/lua_api/l_object.cpp
Labels: @ Script API, One approval, Trivial

#10339 Add some details in lua_api for set_texture_mod and select_x_by_camera
  doc/lua_api.txt
Labels: >= Two approvals, @ Documentation

#10322 Fix luacheck warnings in builtin/common/tests/
  .luacheckrc
Labels: @ Builtin, Maintenance, One approval, Trivial

#10318 Mapgen: Fix on-by-default flags broken since eca6ee9
  src/map_settings_manager.cpp
Labels: >= Two approvals, @ Mapgen, @ Startup / Config / Util, Bugfix

#10341 Prevent players accessing inventories of other players
  src/network/serverpackethandler.cpp
Labels: >= Two approvals, @ Network, Bugfix, High priority

#9818 Make bgcolor tint button background images
  games/devtest/mods/testformspec/formspec.lua
  src/client/guiscalingfilter.cpp
  src/client/guiscalingfilter.h
  src/gui/guiButton.cpp
  src/gui/guiButton.h
Labels: >= Two approvals, Feature, Formspec

#10321 Add vector.offset
  builtin/common/tests/vector_spec.lua
  builtin/common/vector.lua
  doc/lua_api.txt
Labels: >= Two approvals, @ Builtin, @ Script API, Feature

#10096 Document normalmap textures
  doc/lua_api.txt
Labels: >= Two approvals, @ Documentation

#9312 Add compass HUD element
  doc/lua_api.txt
  src/client/hud.cpp
  src/client/hud.h
  src/hud.cpp
  src/hud.h
Labels: Feature, One approval

#9438 Fix dropped craftitems/tools not using light_source values
  builtin/game/item_entity.lua
  doc/lua_api.txt
Labels: >= Two approvals, Bugfix, Trivial

#10351 Fix game crashing if dropped an item with undefined light_source
  builtin/game/item_entity.lua
Labels: Bugfix, Trivial
