Repository luanti-org/luanti, pull requests merged in 2021-09, with the labels that each got.

#10788 Switch MapBlock compression to zstd
  .github/workflows/build.yml
  .github/workflows/macos.yml
  .gitlab-ci.yml
  Dockerfile
  android/native/jni/Android.mk
  builtin/settingtypes.txt
  cmake/Modules/FindZstd.cmake
  doc/world_format.txt
  misc/debpkg-control
  src/CMakeLists.txt
  src/defaultsettings.cpp
  src/main.cpp
  src/mapblock.cpp
  src/mapblock.h
  src/mapgen/mg_schematic.cpp
  src/mapgen/mg_schematic.h
  src/mapnode.cpp
  src/mapnode.h
  src/serialization.cpp
  src/serialization.h
  src/unittest/test_compression.cpp
  util/buildbot/buildwin32.sh
  util/buildbot/buildwin64.sh
  util/ci/common.sh
Labels: Performance, >= Two approvals, Feature

#11581 Build message information on how to build with in-tree Irrlicht
  CMakeLists.txt
Labels: Trivial, >= Two approvals

#11592 Fix movement in random_input mode
  src/client/inputhandler.cpp
  src/client/inputhandler.h
Labels: >= Two approvals, Bugfix

#11596 Add missing zstd-libs to final Docker image
  .github/workflows/build.yml
  Dockerfile
Labels: Trivial, Bugfix

#11550 Dynamic_Add_Media v2
  builtin/game/misc.lua
  doc/lua_api.txt
  src/client/client.cpp
  src/client/client.h
  src/client/clientmedia.cpp
  src/client/clientmedia.h
  src/filesys.cpp
  src/filesys.h
  src/network/clientopcodes.cpp
  src/network/clientpackethandler.cpp
  src/network/networkprotocol.h
  src/network/serveropcodes.cpp
  src/network/serverpackethandler.cpp
  src/script/cpp_api/s_server.cpp
  src/script/cpp_api/s_server.h
  src/script/lua_api/l_server.cpp
  src/script/lua_api/l_server.h
  src/server.cpp
  src/server.h
Labels: @ Script API, @ Client / Audiovisuals, One approval, Feature

#10324 Split vector.new into 3 constructors
  builtin/common/tests/vector_spec.lua
  builtin/common/vector.lua
  doc/lua_api.txt
Labels: @ Script API, >= Two approvals, @ Builtin

#11597 Send to clients node metadata that changed to become empty
  src/nodemetadata.cpp
  src/nodemetadata.h
  src/server.cpp
Labels: Trivial, One approval, Bugfix

#11594 Clean up/improve some scriptapi error handling code
  src/client/client.h
  src/emerge.cpp
  src/script/common/c_internal.cpp
  src/script/common/c_internal.h
  src/script/cpp_api/s_base.h
  src/script/cpp_api/s_client.cpp
  src/script/cpp_api/s_env.cpp
  src/script/cpp_api/s_item.cpp
  src/script/cpp_api/s_nodemeta.cpp
  src/server.cpp
  src/server.h
Labels: @ Script API, One approval, Code quality

#11604 Make sure relevant std::stringstreams are set to binary
  src/client/client.cpp
  src/client/game.cpp
  src/database/database-leveldb.cpp
  src/database/database-postgresql.cpp
  src/database/database-redis.cpp
  src/database/database-sqlite3.cpp
  src/gui/guiChatConsole.cpp
  src/gui/guiFormSpecMenu.cpp
  src/inventory.cpp
  src/itemstackmetadata.cpp
  src/network/clientpackethandler.cpp
  src/script/common/c_converter.cpp
  src/script/lua_api/l_mapgen.cpp
  src/script/lua_api/l_util.cpp
  src/settings.cpp
  src/unittest/test_areastore.cpp
  src/util/serialize.cpp
Labels: Maintenance, One approval, Code quality

#11618 Add Windows-specific CreateTempFile() implementation
  src/filesys.cpp
Labels: Trivial, One approval, Bugfix

#10796 Chop game background
  games/devtest/menu/background.png
  src/gui/guiEngine.cpp
Labels: @ Client / Audiovisuals, Roadmap, >= Two approvals, Bugfix, @ Mainmenu

#11598 Readd TGA to the list of valid texture formats.
  src/client/tile.cpp
  src/server.cpp
Labels: Trivial, >= Two approvals, Bugfix

#9464 Hide Wself-assign-overloaded and Wself-move unittest compilation warnings
  src/unittest/test_irrptr.cpp
Labels: Maintenance, Low priority, Trivial, One approval

#11605 Fix GLES2 discard behaviour (texture transparency)
  client/shaders/nodes_shader/opengl_fragment.glsl
  client/shaders/object_shader/opengl_fragment.glsl
  src/client/shader.cpp
Labels: @ Client / Audiovisuals, Trivial, Bugfix, Shaders

#11607 Shave off buffer copies in networking code
  src/network/connection.cpp
  src/network/connection.h
  src/network/connectionthreads.cpp
  src/network/networkpacket.cpp
  src/network/networkpacket.h
  src/unittest/test_connection.cpp
  src/util/container.h
  src/util/pointer.h
Labels: @ Network, Maintenance, Performance, One approval, Bugfix

#11616 Add preprocessor check for weird (incorrect) build configurations
  src/main.cpp
Labels: Maintenance, Trivial

#11638 Add feature table entry for new dynamic media API
  builtin/game/features.lua
  doc/lua_api.txt
Labels: @ Script API, Trivial, One approval

#10795 Fix HUD multiline text alignment
  src/client/hud.cpp
Labels: @ Client / Audiovisuals, Roadmap, >= Two approvals, Bugfix

#11612 Fix client-side performance of chat UI
  src/chat.cpp
  src/chat.h
  src/client/game.cpp
  src/client/gameui.cpp
  src/client/gameui.h
Labels: Performance, >= Two approvals, Bugfix

#11637 Fix src/util/string.cpp on NetBSD
  src/util/string.cpp
Labels: Trivial, One approval, Bugfix

#10729 Allow Enabling The Touch UI In A Desktop Build
  README.md
  builtin/settingtypes.txt
  src/CMakeLists.txt
  src/client/clientlauncher.cpp
  src/client/game.cpp
  src/client/renderingengine.cpp
  src/defaultsettings.cpp
  src/gui/CMakeLists.txt
  src/gui/guiConfirmRegistration.cpp
  src/gui/guiFormSpecMenu.cpp
  src/gui/guiPasswordChange.cpp
  src/gui/guiTable.cpp
  src/gui/modalMenu.cpp
  src/gui/modalMenu.h
  src/gui/touchscreengui.cpp
  src/gui/touchscreengui.h
Labels: >= Two approvals, Feature, @ Client / Controls / Input

#11623 Fix several typos in settingtypes.txt
  builtin/settingtypes.txt
Labels: @ Documentation, One approval

#11650 Update builtin locale files
  builtin/locale/__builtin.de.tr
  builtin/locale/__builtin.it.tr
  builtin/locale/template.txt
Labels: Maintenance, @ Translation, Trivial

#11659 Various code improvements
  src/client/camera.cpp
  src/client/client.h
  src/client/gameui.h
  src/gui/guiFormSpecMenu.h
  src/inventory.cpp
  src/inventory.h
  src/network/connection.cpp
  src/network/connection.h
  src/network/networkpacket.h
  src/remoteplayer.cpp
  src/remoteplayer.h
Labels: Maintenance, Low priority, >= Two approvals

#11651 Order drawlist by distance to the camera when rendering
  src/client/clientmap.cpp
  src/client/clientmap.h
  src/client/game.cpp
Labels: >= Two approvals, Bugfix, @ Client rendering engine
