Repository luanti-org/luanti, pull requests merged in 2021-05, with the labels that each got.

#11245 fix: extractZipFile is not part of Client but more generic.
  src/client/client.cpp
  src/client/client.h
  src/filesys.cpp
  src/filesys.h
  src/script/lua_api/l_mainmenu.cpp
Labels: Bugfix, One approval

#11158 Improve liquid documentation
  doc/lua_api.txt
Labels: >= Two approvals, @ Documentation

#11246 Fix build for newer versions of GCC
  src/clientiface.h
Labels: Bugfix, Trivial

#11263 Use --image-base instead of -Ttext-segment for lld linker on FreeBSD
  src/CMakeLists.txt
Labels: @ Build, Bugfix, One approval, Trivial

#11268 Fix list of libraries included in AppImage
  .gitlab-ci.yml
  AppImageBuilder.yml
Labels: @ Build, Bugfix, Trivial

#11271 Fix curl_timeout being ignored for Lua HTTP fetches
  src/script/lua_api/l_http.cpp
Labels: Bugfix, One approval, Trivial

#11282 GUIEditBox: Allow selecting and copying read-only texts
  src/gui/guiEditBox.cpp
Labels: @ Client / Controls / Input, Bugfix, One approval, Trivial

#11286 Fix client crash
  src/client/clientlauncher.cpp
Labels: >= Two approvals, Bugfix

#11290 Fix cloud fog being broken for high clouds (maybe)
  src/client/clouds.cpp
Labels: @ Client / Audiovisuals, Bugfix, One approval, Trivial

#11281 UnitSAO: Prevent circular attachments
  doc/lua_api.txt
  src/server/unit_sao.cpp
Labels: Bugfix, One approval

#11031 Fix misleading builtin command syntax of /shutdown
  builtin/game/chat.lua
  builtin/locale/template.txt
Labels: @ Builtin, Bugfix, One approval

#10515 Fix base64 validation and add unittests
  doc/client_lua_api.txt
  doc/lua_api.txt
  src/unittest/test_utilities.cpp
  src/util/base64.cpp
Labels: >= Two approvals, Bugfix

#11247 Add core.compare_block_status function
  doc/lua_api.txt
  src/emerge.cpp
  src/emerge.h
  src/map.cpp
  src/map.h
  src/mapblock.h
  src/script/lua_api/l_env.cpp
  src/script/lua_api/l_env.h
  src/serverenvironment.cpp
  src/serverenvironment.h
Labels: @ Script API, Feature, One approval
