Repository luanti-org/luanti, pull requests merged in 2021-04, with the labels that each got.

#10803 Add `math.round`; fix `vector.round`
  .luacheckrc
  builtin/common/misc_helpers.lua
  builtin/common/vector.lua
  doc/lua_api.txt
Labels: @ Script API, Feature, One approval

#11135 Sort out cURL timeouts and increase default
  builtin/settingtypes.txt
  doc/lua_api.txt
  src/client/clientmedia.cpp
  src/client/clientmedia.h
  src/convert_json.cpp
  src/convert_json.h
  src/defaultsettings.cpp
  src/httpfetch.cpp
Labels: @ Script API, Maintenance, One approval

#11136 CGUITTFont optimizations
  src/gui/guiChatConsole.cpp
  src/irrlicht_changes/CGUITTFont.cpp
  src/irrlicht_changes/CGUITTFont.h
  src/irrlicht_changes/static_text.cpp
Labels: @ Client / Audiovisuals, One approval, Performance

#11160 Devtest: Remove testnodes_show_fallback_image
  games/devtest/mods/testnodes/drawtypes.lua
  games/devtest/mods/testnodes/settingtypes.txt
  games/devtest/settingtypes.txt
Labels: Maintenance, One approval, Trivial

#11161 Reserve vectors before pushing and other code quality changes
  src/client/clientmap.cpp
  src/client/clouds.cpp
  src/client/hud.cpp
  src/client/sky.cpp
  src/client/sky.h
  src/clientiface.cpp
  src/gui/guiButtonItemImage.cpp
  src/gui/guiButtonItemImage.h
  src/inventory.cpp
  src/nodedef.cpp
  src/nodedef.h
  src/nodemetadata.cpp
  src/pathfinder.cpp
  src/settings.cpp
  src/util/areastore.cpp
  src/util/container.h
  src/util/enriched_string.cpp
  src/util/enriched_string.h
  src/voxelalgorithms.cpp
  src/voxelalgorithms.h
Labels: Code quality, One approval, Performance

#11165 Game: Scale damage flash to max HP
  src/client/content_cao.h
  src/client/game.cpp
Labels: Bugfix, Trivial

#10323 Add vector.to_string and vector.from_string
  builtin/common/tests/vector_spec.lua
  builtin/common/vector.lua
  doc/lua_api.txt
Labels: >= Two approvals, @ Builtin, @ Script API

#11156 Make edit boxes respond to string input (IME)
  src/gui/guiChatConsole.cpp
  src/gui/guiChatConsole.h
  src/gui/guiEditBox.cpp
  src/gui/guiEditBox.h
Labels: >= Two approvals, @ Client / Controls / Input, Feature

#11167 Don't reseed stars when changing star count
  src/client/sky.cpp
Labels: One approval, Trivial

#11152 Fix server favorites not saving when client/serverlist/ doesn't exist already
  builtin/mainmenu/serverlistmgr.lua
  src/script/lua_api/l_mainmenu.cpp
  src/script/lua_api/l_mainmenu.h
Labels: @ Mainmenu, Bugfix, Trivial

#11080 Modifying fall damage via armor group
  doc/lua_api.txt
  src/client/clientenvironment.cpp
Labels: >= Two approvals, @ Client / Audiovisuals, Feature

#11180 Buildbot changes to allow out-of-tree builds
  src/CMakeLists.txt
  util/buildbot/buildwin32.sh
  util/buildbot/buildwin64.sh
Labels: @ Build, Maintenance, One approval

#11181 Attachments: Avoid data loss caused by set_attach() in callbacks
  src/server/unit_sao.cpp
Labels: Bugfix, One approval

#11184 Also return the ObjectRef from minetest.spawn_falling_node()
  builtin/game/falling.lua
  doc/lua_api.txt
Labels: >= Two approvals, Feature, Trivial

#11133 Isolate library tables between sandbox and insecure env
  src/script/cpp_api/s_security.cpp
Labels: @ Script API, Bugfix, One approval

#11205 GLES fixes
  src/client/renderingengine.cpp
  src/client/shader.cpp
Labels: @ Client rendering engine, Bugfix, One approval, Trivial

#11172 Add a key to toggle map block bounds
  src/client/game.cpp
  src/client/hud.cpp
  src/client/hud.h
  src/client/inputhandler.cpp
  src/client/keys.h
  src/client/render/core.cpp
  src/defaultsettings.cpp
  src/gui/guiKeyChangeMenu.cpp
Labels: >= Two approvals, Feature

#11074 Put torchlike/signlike node on floor if paramtype2="none"
  builtin/game/falling.lua
  doc/lua_api.txt
  games/devtest/mods/testnodes/drawtypes.lua
  src/client/wieldmesh.cpp
  src/mapnode.cpp
Labels: One approval

#11145 Enable cleanTransparent filter for mipmapping and improve its' algorithm
  builtin/settingtypes.txt
  src/client/guiscalingfilter.cpp
  src/client/imagefilters.cpp
  src/client/imagefilters.h
  src/client/minimap.cpp
  src/client/tile.cpp
Labels: @ Client / Audiovisuals, Bugfix, Feature, One approval

#11215 Look for PostgreSQL library properly and fix CI
  README.md
  src/CMakeLists.txt
  util/ci/common.sh
Labels: @ Build, Maintenance, Trivial

#10425 Add `minetest.colorspec_to_colorstring`
  doc/client_lua_api.txt
  doc/lua_api.txt
  src/script/lua_api/l_util.cpp
  src/script/lua_api/l_util.h
  src/util/string.cpp
Labels: >= Two approvals, @ Script API, Bugfix, Feature, Maintenance

#11163 Rename “Irrlicht” to “IrrlichtMt” in documentation
  CMakeLists.txt
  LICENSE.txt
  README.md
  builtin/settingtypes.txt
  minetest.conf.example
Labels: >= Two approvals, @ Build, @ Documentation

#11229 Update library versions in buildbot
  util/buildbot/buildwin32.sh
  util/buildbot/buildwin64.sh
Labels: @ Build, Maintenance, One approval, Windows

#11232 Add helpful error messages if Irrlicht library or include dir are set incorrectly
  cmake/Modules/FindIrrlicht.cmake
Labels: Maintenance, One approval

#11159 Fix rotation for falling mesh degrotate nodes
  builtin/game/falling.lua
  games/devtest/mods/experimental/commands.lua
  games/devtest/mods/testnodes/drawtypes.lua
Labels: @ Builtin, Bugfix, One approval
