Repository luanti-org/luanti, pull requests merged in 2022-02, with the labels that each got.

#11979 Add more documentation for the list[] fs element
  doc/lua_api.txt
Labels: @ Documentation, One approval, Formspec

#12039 Clean up ClientInterface locking
  src/clientiface.h
  src/network/serverpackethandler.cpp
  src/server.cpp
Labels: One approval, Code quality

#12025 Fix types of get_mapgen_setting_noiseparams
  builtin/mainmenu/dlg_settings_advanced.lua
  src/script/common/c_content.cpp
  src/script/common/c_converter.cpp
  src/script/common/c_converter.h
Labels: @ Script API, >= Two approvals, Bugfix

#12046 Fix broken server startup if ENABLE_CURL=0
  src/script/lua_api/l_http.cpp
  src/script/lua_api/l_http.h
Labels: One approval, Bugfix

#12037 Send HUD flags only if changed
  src/server.cpp
Labels: @ Script API, >= Two approvals

#12052 Noise params serialization fixup
  builtin/mainmenu/dlg_settings_advanced.lua
Labels: Trivial, Bugfix

#12055 Increase max objects per block defaults
  builtin/settingtypes.txt
  minetest.conf.example
  src/defaultsettings.cpp
Labels: One approval

#8448 Allow to set the displayed item count and its alignment via meta
  doc/lua_api.txt
  games/devtest/mods/util_commands/init.lua
  src/client/hud.cpp
Labels: @ Script API, @ Client / Audiovisuals, >= Two approvals, Feature

#12061 Correct world_format.txt specification
  doc/world_format.txt
Labels: @ Documentation, Trivial, One approval

#12023 Add support for 'seed' in disallow_mapgen_settings
  builtin/mainmenu/dlg_create_world.lua
  doc/lua_api.txt
Labels: >= Two approvals, Feature, @ Mainmenu, Supported by core dev

#12018 Apply texture pack main menu textures immediately
  builtin/mainmenu/tab_content.lua
Labels: @ Client / Audiovisuals, >= Two approvals, Feature, Supported by core dev

#11969 Use absolute value for bouncy in collision
  games/devtest/mods/testnodes/properties.lua
  src/collision.cpp
  src/nodedef.cpp
Labels: >= Two approvals, Bugfix

#12074 Clean up ClientReady packet handling
  src/network/serverpackethandler.cpp
  src/remoteplayer.h
  src/server.cpp
Labels: One approval, Bugfix, Code quality

#12075 Lua API: Consistently use double vs. single quotes
  doc/lua_api.txt
Labels: @ Documentation, Trivial, >= Two approvals

#11978 Add TGA test nodes to devtest
  games/devtest/mods/testnodes/textures.lua
  games/devtest/mods/testnodes/textures/testnodes_tga_type10_32bpp_bt.tga
  games/devtest/mods/testnodes/textures/testnodes_tga_type10_32bpp_tb.tga
  games/devtest/mods/testnodes/textures/testnodes_tga_type1_24bpp_bt.tga
  games/devtest/mods/testnodes/textures/testnodes_tga_type1_24bpp_tb.tga
  games/devtest/mods/testnodes/textures/testnodes_tga_type2_16bpp_bt.tga
  games/devtest/mods/testnodes/textures/testnodes_tga_type2_16bpp_tb.tga
  games/devtest/mods/testnodes/textures/testnodes_tga_type2_32bpp_bt.tga
  games/devtest/mods/testnodes/textures/testnodes_tga_type2_32bpp_tb.tga
  games/devtest/mods/testnodes/textures/testnodes_tga_type3_16bpp_bt.tga
  games/devtest/mods/testnodes/textures/testnodes_tga_type3_16bpp_tb.tga
Labels: >= Two approvals

#9517 FormspecMenu: make drawing of backgrounds less hacky
  games/devtest/mods/testformspec/formspec.lua
  src/gui/guiBackgroundImage.cpp
  src/gui/guiFormSpecMenu.cpp
  src/gui/guiFormSpecMenu.h
Labels: Maintenance, Low priority, Roadmap, >= Two approvals, Formspec

#12059 Lua API documentation: Various fixes (2)
  doc/lua_api.txt
  doc/world_format.txt
  src/script/lua_api/l_areastore.cpp
Labels: @ Documentation, >= Two approvals

#12093 Fix broken dependency enabling due to missing `enabled` field
  builtin/mainmenu/pkgmgr.lua
Labels: One approval, Bugfix, @ Content/PkgMgr

#12095 Move the codebase to C++14
  CMakeLists.txt
  android/native/jni/Application.mk
  src/CMakeLists.txt
  src/modchannels.cpp
  src/server.cpp
  src/unittest/test_address.cpp
  src/unittest/test_eventmanager.cpp
  src/unittest/test_server_shutdown_state.cpp
  src/util/metricsbackend.cpp
Labels: Maintenance, One approval
