Repository luanti-org/luanti, pull requests merged in 2022-07, with the labels that each got.

#12484 Fix error when `item` isn't provided to core.hud_replace_builtin
  builtin/game/statbars.lua
Labels: @ Script API, Trivial, Bugfix

#11663 Allow to set maximum star opacity at daytime
  doc/lua_api.txt
  src/client/game.cpp
  src/client/sky.cpp
  src/client/sky.h
  src/network/clientpackethandler.cpp
  src/network/networkprotocol.h
  src/script/lua_api/l_object.cpp
  src/server.cpp
  src/skyparams.h
Labels: @ Script API, @ Client / Audiovisuals, >= Two approvals, Feature, Supported by core dev

#12307 DevTest: Add item meta editor
  games/devtest/mods/testtools/README.md
  games/devtest/mods/testtools/init.lua
  games/devtest/mods/testtools/textures/testtools_item_meta_editor.png
Labels: >= Two approvals, Feature, Supported by core dev, @ Devtest Game

#12495 Optimize strict.lua
  builtin/common/strict.lua
Labels: Maintenance, >= Two approvals, @ Builtin, Code quality

#12496 Serialization spec: Fix number fuzzing
  builtin/common/tests/serialize_spec.lua
Labels: Maintenance, >= Two approvals, @ Builtin

#12453 FormSpec: 9-slice images, animated_images, and fgimg_middle
  doc/lua_api.txt
  games/devtest/mods/testformspec/formspec.lua
  games/devtest/mods/testformspec/textures/testformspec_9slice.png
  src/client/guiscalingfilter.cpp
  src/client/guiscalingfilter.h
  src/gui/StyleSpec.h
  src/gui/guiAnimatedImage.cpp
  src/gui/guiAnimatedImage.h
  src/gui/guiBackgroundImage.cpp
  src/gui/guiButton.cpp
  src/gui/guiButtonImage.cpp
  src/gui/guiButtonImage.h
  src/gui/guiFormSpecMenu.cpp
  src/gui/guiFormSpecMenu.h
  src/network/networkprotocol.h
Labels: @ Client / Audiovisuals, Roadmap, >= Two approvals, Feature, Formspec

#12504 Fixed spelling inconsistency
  doc/lua_api.txt
Labels: @ Documentation, Trivial, One approval

#12458 Add missing item alias metatables to async environment
  builtin/async/game.lua
  builtin/game/register.lua
  games/devtest/mods/unittests/async_env.lua
  games/devtest/mods/unittests/init.lua
  games/devtest/mods/unittests/inside_async_env.lua
  games/devtest/mods/unittests/misc.lua
Labels: @ Script API, One approval, Bugfix

#12441 Add utility script to stress-test mapgen
  util/helper_mod/init.lua
  util/helper_mod/mod.conf
  util/stress_mapgen.sh
  util/test_multiplayer.sh
Labels: One approval, Feature

#12516 Replace deprecated use of `vector.new` with `copy`
  builtin/game/item.lua
Labels: Maintenance, Trivial

#12497 Release shadow mapping resources when not needed
  src/client/clientmap.cpp
  src/client/content_cao.cpp
  src/client/shadows/dynamicshadowsrender.cpp
  src/client/shadows/dynamicshadowsrender.h
  src/client/wieldmesh.cpp
Labels: @ Client / Audiovisuals, Roadmap, Performance, One approval

#12450 Enforce limits of settings that could cause buggy behaviour
  builtin/mainmenu/dlg_contentstore.lua
  builtin/settingtypes.txt
  src/client/camera.cpp
  src/client/client.cpp
  src/client/client.h
  src/client/clouds.cpp
  src/client/fontengine.cpp
  src/client/game.cpp
  src/client/gameui.cpp
  src/client/hud.cpp
  src/client/joystick_controller.cpp
  src/client/render/stereo.cpp
  src/client/renderingengine.cpp
  src/client/tile.cpp
  src/emerge.cpp
  src/gui/guiChatConsole.cpp
  src/gui/guiFormSpecMenu.cpp
  src/gui/guiTable.cpp
  src/gui/modalMenu.cpp
  src/gui/touchscreengui.cpp
  src/map.cpp
  src/map.h
  src/mapgen/mapgen.cpp
  src/mapgen/mapgen_fractal.cpp
  src/nodedef.cpp
  src/server.cpp
  src/settings.cpp
  src/settings.h
Labels: Maintenance, One approval, Bugfix

#12486 Sounds: Various little improvements
  src/client/sound.h
  src/client/sound_openal.cpp
  src/gui/guiFormSpecMenu.cpp
  src/network/clientpackethandler.cpp
  src/script/common/c_content.cpp
  src/script/lua_api/l_client.cpp
  src/server.cpp
  src/server.h
  src/sound.h
Labels: Maintenance, One approval, Sounds

#12521 Make `VoxelArea:position()` return a vector with metatable
  builtin/game/voxelarea.lua
Labels: One approval, Bugfix

#11545 Animated particlespawners
  builtin/game/features.lua
  doc/lua_api.txt
  src/client/particles.cpp
  src/client/particles.h
  src/network/clientpackethandler.cpp
  src/network/networkprotocol.h
  src/particles.cpp
  src/particles.h
  src/script/common/c_content.cpp
  src/script/common/c_converter.h
  src/script/lua_api/l_particleparams.h
  src/script/lua_api/l_particles.cpp
  src/script/lua_api/l_particles_local.cpp
  src/server.cpp
  src/util/numeric.cpp
  src/util/numeric.h
  src/util/pointer.h
Labels: @ Script API, @ Client / Audiovisuals, >= Two approvals, Feature, Supported by core dev

#12519 Deserialization: Restore backwards compat
  builtin/common/serialize.lua
Labels: @ Script API, >= Two approvals, Bugfix

#12527 GUIFormSpecMenu: Fix multiline translation
  src/gui/guiFormSpecMenu.cpp
Labels: @ Translation, One approval, Bugfix, Formspec

#12539 Fix regression & replace more occurrences of vector.new with vector.copy
  builtin/game/falling.lua
  builtin/game/item.lua
  games/devtest/mods/unittests/misc.lua
Labels: >= Two approvals, Bugfix, @ Builtin

#12505 More corrections to lua_api.txt
  doc/lua_api.txt
Labels: @ Documentation, One approval

#12541 Deprecate loading a world with unresolved dependencies
  src/server.cpp
Labels: @ Server / Client / Env., One approval, UI/UX

#12354 Enable the gamebar on Android
  builtin/mainmenu/common.lua
  builtin/mainmenu/dlg_create_world.lua
  builtin/mainmenu/tab_local.lua
Labels: Android, Roadmap, >= Two approvals, @ Mainmenu, UI/UX

#12460 Remove workaround for normals not matching winding order
  src/client/mesh.cpp
Labels: @ Client / Audiovisuals, >= Two approvals, Bugfix

#12392 Fix automatic rotate for attached entities
  src/client/content_cao.cpp
Labels: @ Script API, >= Two approvals, Bugfix

#12558 Offset cuboid origin after scaling the cuboid.
  src/client/content_mapblock.cpp
Labels: @ Client / Audiovisuals, One approval, Bugfix

#12560 Restore flags texture to fix interlaced stereo mode
  src/client/game.cpp
Labels: @ Client / Audiovisuals, One approval, Bugfix, Shaders

#12572 Let core.get_mod_storage be called multiple times
  builtin/client/init.lua
  builtin/common/mod_storage.lua
  builtin/game/init.lua
  src/script/lua_api/l_storage.cpp
Labels: >= Two approvals, Bugfix

#12584 Fix lua_api typo: animated_images
  doc/lua_api.txt
Labels: @ Documentation, Trivial, One approval, Bugfix

#12599 Allow direction keys with autoforward again
  src/client/game.cpp
Labels: Trivial, One approval, Bugfix

#12602 Fix media overriding regression
  src/server/mods.cpp
  src/unittest/test_servermodmanager.cpp
Labels: >= Two approvals, Bugfix, Textures

#12615 Fix some warnings
  src/client/game.cpp
  src/client/mapblock_mesh.cpp
  src/client/particles.h
  src/emerge.cpp
  src/network/serverpackethandler.cpp
  src/particles.h
  src/script/common/c_packer.cpp
  src/script/lua_api/l_particleparams.h
  src/server/mods.cpp
Labels: Maintenance, One approval, Code quality

#12604 Fix Android blank screen
  src/client/renderingengine.cpp
Labels: @ Client / Audiovisuals, Android, >= Two approvals, Bugfix

#12618 Apply NetBSD string conversion workaround to OpenBSD as well
  src/util/string.cpp
Labels: >= Two approvals, Bugfix

#12587 Fix rotation of falling facedir nodes in some cases
  builtin/game/falling.lua
  games/devtest/mods/testnodes/properties.lua
Labels: >= Two approvals, Bugfix

#12608 Use legacy image implementation when not using 9-slice image
  src/gui/guiFormSpecMenu.cpp
Labels: @ Client / Audiovisuals, One approval, Bugfix
