Repository luanti-org/luanti, pull requests merged in 2023-07, with the labels that each got.

#13448 Allow the server to control fog_distance and fog_start via the sky-api
  client/shaders/nodes_shader/opengl_fragment.glsl
  client/shaders/object_shader/opengl_fragment.glsl
  doc/lua_api.md
  src/client/game.cpp
  src/client/shader.cpp
  src/client/sky.cpp
  src/client/sky.h
  src/network/clientpackethandler.cpp
  src/script/lua_api/l_object.cpp
  src/server.cpp
  src/skyparams.h
Labels: @ Script API, @ Client / Audiovisuals, One approval, Feature, Supported by core dev

#13521 Android: Reliably showing an IME for text input dialog
  android/app/src/main/java/net/minetest/minetest/CustomEditText.java
  android/app/src/main/java/net/minetest/minetest/GameActivity.java
Labels: Android, One approval, Bugfix, UI/UX

#13638 Fix local animations not resetting
  src/client/content_cao.cpp
  src/client/localplayer.h
  src/network/clientpackethandler.cpp
Labels: Trivial, One approval, Bugfix

#13641 Fix texture paths for system-installed builds
  src/client/clientlauncher.cpp
  src/client/renderingengine.cpp
Labels: Trivial, >= Two approvals, Bugfix

#13635 Don't crash if a Lua error occurs inside get_staticdata
  src/client/game.cpp
  src/server.cpp
  src/server.h
  src/serverenvironment.cpp
Labels: >= Two approvals, Bugfix

#13643 Server enforcement for fog_distance (#13448) to block cheating
  src/clientiface.cpp
Labels: One approval, Feature

#13624 guiScalingFilter: prevent infinite loop caused by negative background9[] size
  src/client/guiscalingfilter.cpp
Labels: One approval, Bugfix, Formspec

#13493 Fix max_formspec_size not taking gui_scaling into account
  src/client/game.cpp
  src/clientdynamicinfo.h
  src/script/lua_api/l_mainmenu.cpp
Labels: @ Client / Audiovisuals, >= Two approvals, Bugfix, Formspec

#13369 Reverse eye-offset Z-coordinate in 3rd person front view
  src/client/camera.cpp
Labels: @ Client / Audiovisuals, Trivial, Supported by core dev

#13647 Improve messages when changing viewing range and exceeding server-set limit
  src/client/game.cpp
Labels: >= Two approvals, UI/UX

#13661 Fix sound manager not being stepped by GUIEngine
  src/gui/guiEngine.cpp
Labels: One approval, Bugfix, Sounds, @ Mainmenu

#13607 Decrease sneak margin to combat phasing through thin walls
  src/client/localplayer.cpp
Labels: >= Two approvals, @ Client / Controls / Input

#13636 Add irrlicht device info to the mainmenu About tab
  .github/ISSUE_TEMPLATE/bug_report.md
  builtin/mainmenu/tab_about.lua
  doc/menu_lua_api.md
  src/script/lua_api/l_mainmenu.cpp
  src/script/lua_api/l_mainmenu.h
Labels: Maintenance, >= Two approvals, @ Mainmenu

#13649 Fix that transparent text still draws a text shadow
  src/irrlicht_changes/CGUITTFont.cpp
Labels: @ Client / Audiovisuals, >= Two approvals, Bugfix

#13648 Fix string conversion for FreeBSD
  src/util/string.cpp
Labels: Trivial, One approval, Bugfix, BSD

#13666 GUI: Automatic scaling of checkboxes and scrollbars
  src/client/clientlauncher.cpp
Labels: @ Client / Audiovisuals, One approval, Bugfix

#13445 Introduce and start using microsecond sleep on Linux
  src/client/game.cpp
  src/porting.h
Labels: Trivial, One approval, Bugfix

#13669 Fix incorrect rounding in GUIInventoryList::getItemIndexAtPos
  src/gui/guiInventoryList.cpp
Labels: One approval, Bugfix, Formspec

#13606 Increase the resolution of the logo shown on the about tab
  textures/base/pack/logo.png
Labels: Trivial, One approval, Textures, @ Mainmenu, Supported by core dev

#13590 Android: Remove Migration Code
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/net/minetest/minetest/MainActivity.java
  android/app/src/main/java/net/minetest/minetest/UnzipService.java
  android/app/src/main/res/values/strings.xml
Labels: Maintenance, Android, >= Two approvals

#13695 Minor additions to the VoxelManip docs
  doc/lua_api.md
Labels: @ Documentation, >= Two approvals

#13161 Add performance test nodes, using complex meshes.
  games/devtest/mods/testnodes/init.lua
  games/devtest/mods/testnodes/models/testnodes_marble_glass.obj
  games/devtest/mods/testnodes/models/testnodes_marble_metal.obj
  games/devtest/mods/testnodes/performance_test_nodes.lua
  games/devtest/mods/testnodes/textures/testnodes_marble_glass.png
  games/devtest/mods/testnodes/textures/testnodes_marble_metal.png
  games/devtest/mods/testnodes/textures/testnodes_marble_metal_overlay.png
  games/devtest/mods/testnodes/textures/testnodes_palette_metal.png
Labels: >= Two approvals, Feature, Supported by core dev, @ Devtest Game

#13697 Fix `decode_base64` to return `nil` on failure instead of nothing
  src/script/lua_api/l_util.cpp
Labels: @ Script API, Trivial, >= Two approvals, Bugfix

#13239 Improve object documentation in lua_api.txt
  doc/lua_api.md
Labels: @ Documentation, >= Two approvals

#13678 Update guiEditBoxWithScrollbar.cpp
  src/gui/guiEditBoxWithScrollbar.cpp
Labels: >= Two approvals, Bugfix, Formspec

#13693 Add Void Linux specifics to build documentation
  doc/compiling/linux.md
Labels: @ Build, @ Documentation, >= Two approvals

#13573 Add dev stage to docker image
  Dockerfile
  README.md
  doc/developing/docker.md
Labels: @ Build, >= Two approvals, Feature, Supported by core dev
