Repository luanti-org/luanti, pull requests merged in 2023-06, with the labels that each got.

#13472 Cavegen y biome check
  src/mapgen/cavegen.cpp
  src/mapgen/cavegen.h
  src/mapgen/mapgen.cpp
  src/mapgen/mg_biome.cpp
  src/mapgen/mg_biome.h
Labels: @ Mapgen, One approval, Bugfix

#13555 Fix various cases of double-escaped error messages
  builtin/fstk/ui.lua
  builtin/mainmenu/dlg_contentstore.lua
  builtin/mainmenu/dlg_create_world.lua
  builtin/mainmenu/dlg_delete_content.lua
  builtin/mainmenu/pkgmgr.lua
  builtin/mainmenu/tab_local.lua
  builtin/mainmenu/tests/pkgmgr_spec.lua
Labels: Trivial, One approval, Bugfix, @ Mainmenu

#13146 Inventory mouse shortcut improvements
  src/client/client.cpp
  src/client/client.h
  src/gui/guiFormSpecMenu.cpp
  src/gui/guiFormSpecMenu.h
  src/gui/guiInventoryList.h
  src/inventory.cpp
  src/inventory.h
Labels: Roadmap, >= Two approvals, Feature, @ Client / Controls / Input, Formspec

#13532 Remove a misleading MutexAutoLock in l_to_table
  src/script/lua_api/l_settings.cpp
Labels: Maintenance, Trivial, >= Two approvals

#13561 Auto-detect locale on Android
  android/app/src/main/java/net/minetest/minetest/GameActivity.java
  src/gettext.cpp
  src/porting_android.cpp
  src/porting_android.h
Labels: Android, @ Translation, >= Two approvals, Feature

#13562 Extend roadmap approval time from one week to one month
  .github/CONTRIBUTING.md
  doc/direction.md
Labels: @ Documentation, Roadmap, >= Two approvals

#13564 Fix some memleaks from GUIButtonImage
  src/gui/guiButtonImage.cpp
  src/gui/guiButtonImage.h
Labels: Maintenance, One approval, Bugfix

#13348 Move the platform-dependent stuff in renderingengine.cpp to irrlicht
  src/CMakeLists.txt
  src/client/clientlauncher.cpp
  src/client/renderingengine.cpp
  src/client/renderingengine.h
Labels: Maintenance, >= Two approvals

#13523 [Rebase] Implement check_offset for decorations
  doc/lua_api.md
  src/mapgen/mg_decoration.cpp
  src/mapgen/mg_decoration.h
  src/script/lua_api/l_mapgen.cpp
Labels: @ Script API, >= Two approvals, Feature, Supported by core dev

#13567 TouchScreenGUI: Read coordinates directly for virtual joystick
  src/client/inputhandler.h
  src/gui/touchscreengui.cpp
  src/gui/touchscreengui.h
Labels: Android, One approval, Feature, @ Client / Controls / Input, Supported by core dev

#12764 Sound refactor and improvements
  LICENSE.txt
  builtin/client/misc.lua
  builtin/mainmenu/init.lua
  builtin/mainmenu/misc.lua
  doc/client_lua_api.md
  doc/lua_api.md
  doc/menu_lua_api.md
  games/devtest/mods/soundstuff/init.lua
  games/devtest/mods/soundstuff/jukebox.lua
  games/devtest/mods/soundstuff/racecar.lua
  games/devtest/mods/soundstuff/sounds/soundstuff_sinus.ogg
  games/devtest/mods/soundstuff/textures/soundstuff_racecar.png
  src/client/CMakeLists.txt
  src/client/camera.cpp
  src/client/client.cpp
  src/client/client.h
  src/client/clientobject.h
  src/client/content_cao.cpp
  src/client/content_cao.h
  src/client/game.cpp
  src/client/sound.cpp
  src/client/sound.h
  src/client/sound_openal.cpp
  src/client/sound_openal.h
  src/client/sound_openal_internal.cpp
  src/client/sound_openal_internal.h
  src/gui/guiEngine.cpp
  src/gui/guiEngine.h
  src/gui/guiFormSpecMenu.cpp
  src/itemdef.cpp
  src/itemdef.h
  src/network/clientpackethandler.cpp
  src/network/networkprotocol.h
  src/nodedef.cpp
  src/nodedef.h
  src/player.h
  src/script/common/c_content.cpp
  src/script/common/c_content.h
  src/script/lua_api/CMakeLists.txt
  src/script/lua_api/l_client.cpp
  src/script/lua_api/l_client.h
  src/script/lua_api/l_client_sound.cpp
  src/script/lua_api/l_client_sound.h
  src/script/lua_api/l_mainmenu_sound.cpp
  src/script/lua_api/l_mainmenu_sound.h
  src/script/lua_api/l_server.cpp
  src/script/lua_api/l_sound.cpp
  src/script/scripting_client.cpp
  src/script/scripting_mainmenu.cpp
  src/server.cpp
  src/server.h
  src/sound.h
Labels: @ Script API, Roadmap, >= Two approvals, Bugfix, Sounds, Feature, Code quality

#13594 Cull liquid back face on liquid-glasslike interface
  src/client/content_mapblock.cpp
Labels: >= Two approvals, Bugfix, @ Client rendering

#13314 Instrument touchMapBlocks and block loading/deserialization.
  src/client/clientmap.cpp
  src/map.cpp
Labels: Trivial, Roadmap, One approval

#13614 OpenALSoundManager: Fix a buffer overflow
  src/client/sound_openal_internal.cpp
Labels: Trivial, Bugfix

#13617 Use absolute URL for the roadmap
  .github/PULL_REQUEST_TEMPLATE.md
Labels: @ Documentation, Trivial, >= Two approvals

#13599 [NOSQUASH] Remove trigonometry from liquid drawing
  src/client/content_mapblock.cpp
Labels: Performance, >= Two approvals, @ Client rendering

#13608 remove unsupported media formats from client.cpp
  src/client/client.cpp
Labels: @ Client / Audiovisuals, Maintenance, Trivial, One approval

#13625 Fix compiler errors on MSVC with ENABLE_TOUCH=TRUE
  src/gui/touchscreengui.cpp
  src/gui/touchscreengui.h
Labels: @ Build, Trivial, Bugfix

#13602 Adding gettext in the compilation dependency packages list
  doc/compiling/linux.md
  doc/compiling/macos.md
  doc/compiling/windows.md
Labels: @ Documentation, Trivial, One approval

#13629 Fix MSVC action
  .github/workflows/build.yml
Labels: Trivial, One approval

#13284 Try all known video drivers if the requested one fails to initialize
  src/client/renderingengine.cpp
Labels: @ Client / Audiovisuals, Roadmap, >= Two approvals

#13627 Allow running individual tests
  src/main.cpp
  src/unittest/test.cpp
  src/unittest/test.h
Labels: >= Two approvals

#13631 Add unit tests for isBlockInSight()
  src/clientiface.cpp
  src/unittest/test_utilities.cpp
Labels: Maintenance, One approval

#13634 Fix `.clang-format` file config values
  .clang-format
Labels: Maintenance, Trivial
