Repository luanti-org/luanti, pull requests merged in 2023-03, with the labels that each got.

#13243 Drop dependency on IrrCompileConfig
  src/client/clientlauncher.cpp
  src/client/game.cpp
  src/client/tile.cpp
  src/defaultsettings.cpp
  src/gui/guiButton.h
  src/gui/guiChatConsole.cpp
  src/gui/guiEditBox.cpp
  src/gui/guiSkin.cpp
  src/gui/guiSkin.h
  src/irrlicht_changes/static_text.cpp
  src/irrlicht_changes/static_text.h
Labels: Maintenance, >= Two approvals, Code quality

#13265 Document that item_image_button[] name is non-optional
  doc/lua_api.txt
Labels: @ Documentation, Trivial, One approval

#13249 Add git installation steps for Arch/Alpine to README
  README.md
Labels: @ Documentation, Trivial

#13242 Enable connected glass by default
  builtin/settingtypes.txt
  minetest.conf.example
  src/defaultsettings.cpp
Labels: @ Client / Audiovisuals, >= Two approvals

#13271 Tile: Fix segfault caused by invalid PNG data
  src/client/tile.cpp
Labels: One approval, Bugfix

#12391 Minor adjustments now that OpenGLES 2 is the default driver on Android
  android/app/src/main/AndroidManifest.xml
  builtin/settingtypes.txt
  src/defaultsettings.cpp
Labels: Android, Roadmap, Performance, >= Two approvals, @ Client rendering engine, Shaders

#13263 Kubernetes: Deployments are stable since v1.16
  misc/kubernetes.yml
Labels: @ Build, Trivial

#13260 Reduce server CPU consumed by occlusion culling.
  src/clientiface.cpp
  src/clientiface.h
Labels: @ Server / Client / Env., Performance, >= Two approvals

#13291 Fix missing shadows when sun tilt is zero
  client/shaders/nodes_shader/opengl_fragment.glsl
  client/shaders/nodes_shader/opengl_vertex.glsl
  client/shaders/object_shader/opengl_fragment.glsl
  client/shaders/object_shader/opengl_vertex.glsl
Labels: @ Client / Audiovisuals, Trivial, >= Two approvals, Bugfix

#13250 Scale culler steps proportionally to the mesh sizes
  builtin/settingtypes.txt
  src/client/client.cpp
  src/client/clientmap.cpp
  src/client/clientmap.h
  src/client/mapblock_mesh.cpp
  src/client/mapblock_mesh.h
  src/client/mesh_generator_thread.h
  src/util/numeric.h
Labels: Blocker, @ Client / Audiovisuals, Performance, >= Two approvals, Bugfix

#13305 Fix ChatPrompt crash in very narrow windows
  src/chat.cpp
Labels: >= Two approvals, Bugfix

#13225 Fix infinite viewing_range
  src/client/clientmap.cpp
  src/mapsector.cpp
Labels: Blocker, One approval, Bugfix

#13313 Fix rendertarget size being saved as screensize
  src/client/game.cpp
Labels: @ Client / Audiovisuals, >= Two approvals, Bugfix, Regression

#13308 Update nodes in LBM loop
  src/serverenvironment.cpp
Labels: One approval, Bugfix

#13299 Fix occasional black screen on startup
  src/client/render/pipeline.cpp
Labels: @ Client / Audiovisuals, >= Two approvals, Bugfix

#13323 Fix empty port assertion error in 'Join Game' menu.
  builtin/mainmenu/tab_online.lua
Labels: Trivial, >= Two approvals, Bugfix

#13319 Remove default keybind for pitchmove
  README.md
  builtin/settingtypes.txt
  src/defaultsettings.cpp
Labels: >= Two approvals, @ Client / Controls / Input

#13341 Remove obsolete rendering core init code.
  src/client/render/core.cpp
  src/client/render/core.h
  src/client/renderingengine.cpp
Labels: Maintenance, Performance, >= Two approvals, @ Client rendering engine

#13332 Fix server-side formspec state keeping issue
  src/server.cpp
Labels: @ Server / Client / Env., Trivial, >= Two approvals, Bugfix

#13240 Various smaller lua_api documentation updates
  doc/lua_api.txt
Labels: @ Documentation, >= Two approvals

#13181 Clarify documentation of inventory actions
  doc/lua_api.txt
Labels: @ Documentation, >= Two approvals

#13338 Move drawing of wield tool into a dedicated step of the pipeline
  src/client/camera.cpp
  src/client/render/anaglyph.cpp
  src/client/render/interlaced.cpp
  src/client/render/plain.cpp
  src/client/render/plain.h
  src/client/render/sidebyside.cpp
Labels: @ Client / Audiovisuals, >= Two approvals, Bugfix

#13339 Move rendering engine reset after deletion of game objects
  src/client/game.cpp
Labels: Trivial, One approval, Bugfix, @ Client rendering engine

#13340 Return shadow_sky_body_orbit_tilt setting
  builtin/settingtypes.txt
  doc/lua_api.txt
  minetest.conf.example
  src/client/sky.cpp
  src/client/sky.h
  src/defaultsettings.cpp
  src/script/lua_api/l_object.cpp
  src/skyparams.h
Labels: @ Client / Audiovisuals, >= Two approvals, Bugfix

#13316 Add Malay translation of builtin
  builtin/locale/__builtin.ms.tr
Labels: @ Translation, One approval

#13309 Add Indonesian translation of builtin
  builtin/locale/__builtin.id.tr
Labels: @ Translation, One approval

#13310 Fix safeLoadFile() skipping 2 chars too much from the shebang
  src/script/cpp_api/s_security.cpp
Labels: @ Script API, One approval, Bugfix

#13286 Fix core.item_eat for same-item replace_with_item and split stacks before dropping
  builtin/game/item.lua
  doc/lua_api.txt
Labels: One approval, Bugfix, @ Builtin

#13330 Update credits for 5.7.0
  .mailmap
  builtin/mainmenu/tab_about.lua
Labels: Blocker, Maintenance, One approval, @ Mainmenu

#13352 Return 'loops' occlusion culler under a setting
  builtin/settingtypes.txt
  minetest.conf.example
  src/client/clientmap.cpp
  src/client/clientmap.h
  src/defaultsettings.cpp
Labels: One approval, Bugfix, @ Client rendering engine

#13277 Restart map-send cycle if visible blocks are soon to be unloaded.
  src/clientiface.cpp
Labels: @ Network, Performance, One approval
