Repository luanti-org/luanti, pull requests merged in 2023-01, with the labels that each got.

#13113 Document mod storage psql settings in world_format.txt
  doc/world_format.txt
Labels: @ Documentation, Trivial, One approval

#13117 Use consistent optimization flags for *BSD
  src/CMakeLists.txt
Labels: @ Build, Maintenance, Trivial, One approval

#13104 Occlusion culling algorithm based on recursive descend
  builtin/settingtypes.txt
  src/client/client.cpp
  src/client/clientmap.cpp
  src/client/clientmap.h
  src/client/game.cpp
  src/client/mapblock_mesh.cpp
  src/client/mapblock_mesh.h
  src/client/mesh_generator_thread.cpp
  src/client/mesh_generator_thread.h
  src/defaultsettings.cpp
  src/mapblock.h
Labels: @ Client / Audiovisuals, Roadmap, Performance, >= Two approvals, Feature

#13082 Remove old rollback migration code
  src/rollback.cpp
  src/rollback.h
Labels: Maintenance, >= Two approvals

#13119 Replace minetest_game with "Minetest Game" where appropriate
  README.md
Labels: @ Documentation, Trivial, One approval

#13105 Report collisionMoveSimple for client and server.
  src/collision.cpp
Labels: Trivial, One approval, Bugfix

#13098 Clamp player wieldindex when processing hotbar item selection
  src/client/game.cpp
Labels: @ Client / Audiovisuals, >= Two approvals, Bugfix

#13123 Fix crash on Android with IrrlichtMt9
  src/client/clientlauncher.cpp
  src/client/game.cpp
Labels: Android, >= Two approvals, Bugfix

#13081 Don't install Development Test
  .github/workflows/macos.yml
  CMakeLists.txt
  README.md
Labels: >= Two approvals, @ Mainmenu, Supported by core dev

#13131 Always set globals in `__newindex` in strict.lua
  builtin/common/strict.lua
Labels: @ Script API, Trivial, One approval, Bugfix

#13124 Remove mapblock cache for mesh generation.
  src/client/client.cpp
  src/client/mesh_generator_thread.cpp
  src/client/mesh_generator_thread.h
  src/network/clientpackethandler.cpp
Labels: @ Client / Audiovisuals, Performance, >= Two approvals

#13064 DevTest: `chest_of_everything` mod: Add search, bag, improve formspec
  games/devtest/mods/chest_of_everything/init.lua
  games/devtest/mods/chest_of_everything/mod.conf
  games/devtest/mods/chest_of_everything/textures/chest_of_everything_bag.png
  games/devtest/mods/give_initial_stuff/init.lua
Labels: >= Two approvals, Feature, @ Devtest Game

#13132 Error when `string.split` is given empty separator
  builtin/common/misc_helpers.lua
  builtin/common/tests/misc_helpers_spec.lua
  doc/lua_api.txt
Labels: @ Script API, Trivial, One approval, Bugfix

#13136 Break long lines of option help
  src/main.cpp
Labels: @ Startup / Config / Util, Trivial, One approval, Bugfix

#13141 Increase `ftos` precision
  src/unittest/test_settings.cpp
  src/util/string.h
Labels: @ Server / Client / Env., One approval, Bugfix

#13130 Improve `MetaDataRef:{get,set}_float` precision
  games/devtest/mods/unittests/metadata.lua
  src/script/lua_api/l_metadata.cpp
Labels: @ Script API, One approval, Bugfix

#13144 Disable Prometheus in singleplayer mode
  src/server.cpp
Labels: Trivial, Bugfix

#12975 Improve chat history
  src/chat.cpp
  src/chat.h
Labels: One approval, Feature, @ Client / Controls / Input, Supported by core dev, UI/UX

#12997 Fix Enter key after creating a new world
  builtin/mainmenu/dlg_create_world.lua
  builtin/mainmenu/tab_local.lua
Labels: >= Two approvals, Bugfix, @ Mainmenu, Formspec

#13126 Revisit F6 statistics formatting
  src/client/gameui.cpp
  src/collision.cpp
  src/profiler.cpp
Labels: Maintenance, >= Two approvals

#13147 Change DevTest header (new font: "undefined medium")
  games/devtest/menu/header.png
Labels: Maintenance, >= Two approvals, Bugfix

#13150 Fix concurrency in texture source
  src/client/tile.cpp
Labels: @ Client / Audiovisuals, >= Two approvals, Bugfix

#13162 fixed a README mistake on option SPATIAL_LIBRARY
  README.md
Labels: @ Documentation, Trivial, One approval

#13163 Use default values from cpp_api/s_env.cpp for register_abm in lua_api.txt
  doc/lua_api.txt
Labels: @ Documentation, Trivial, One approval

#13151 Clear exposure compensation textures on creation.
  src/client/render/pipeline.cpp
  src/client/render/pipeline.h
  src/client/render/secondstage.cpp
Labels: @ Client / Audiovisuals, >= Two approvals, Bugfix

#13157 Implement --debugger option to improve UX when debugging crashes
  src/filesys.cpp
  src/filesys.h
  src/gettext.cpp
  src/main.cpp
  src/porting.cpp
  src/porting.h
  util/test_multiplayer.sh
Labels: @ Startup / Config / Util, >= Two approvals, Feature

#13165 Decrease minimum for repeat_place_time
  builtin/settingtypes.txt
  src/client/game.cpp
Labels: >= Two approvals, @ Client / Controls / Input

#13169 Remove the 'loops' occlusion culler
  builtin/settingtypes.txt
  src/client/clientmap.cpp
  src/defaultsettings.cpp
Labels: @ Client / Audiovisuals, Maintenance, >= Two approvals

#13155 Display whole profiler numbers up to 999999 without scientific notation.
  src/profiler.cpp
Labels: Trivial, One approval

#13133 8x block meshes
  src/client/client.cpp
  src/client/clientmap.cpp
  src/client/clientmap.h
  src/client/content_mapblock.cpp
  src/client/mapblock_mesh.cpp
  src/client/mapblock_mesh.h
  src/client/mesh_generator_thread.cpp
  src/client/mesh_generator_thread.h
  src/client/meshgen/collector.cpp
  src/client/meshgen/collector.h
  src/client/wieldmesh.cpp
  src/map.cpp
  src/util/directiontables.cpp
  src/util/directiontables.h
Labels: @ Client / Audiovisuals, Roadmap, Performance, >= Two approvals, Feature

#13168 Improve the documentation for chat command definition in lua_api.txt.
  doc/lua_api.txt
Labels: @ Documentation, >= Two approvals
