Repository luanti-org/luanti, pull requests merged in 2024-08, with the labels that each got.

#14892 Android SDK 34
  .github/workflows/android.yml
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/net/minetest/minetest/MainActivity.java
  android/app/src/main/java/net/minetest/minetest/UnzipService.java
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  android/native/build.gradle
  android/native/src/main/AndroidManifest.xml
Labels: Maintenance, Android, One approval ✅ ◻️

#14895 Rename `minetest.register_async_metatable` to `minetest.register_portable_metatable`
  builtin/common/metatable.lua
  doc/lua_api.md
  games/devtest/mods/unittests/async_env.lua
  games/devtest/mods/unittests/inside_async_env.lua
Labels: @ Script API, Maintenance, >= Two approvals ✅ ✅

#14917 Add version to override_item_remove_fields feature flag doc
  doc/lua_api.md
Labels: @ Documentation, Trivial, Bugfix 🐛

#14915 Avoid infinite recursion with unhandled second touch
  src/gui/modalMenu.cpp
Labels: Android, One approval ✅ ◻️, Bugfix 🐛, @ Client / Controls / Input

#14904 Take screenshot from back buffer when using double buffering
  irr/src/COpenGLDriver.cpp
Labels: >= Two approvals ✅ ✅, Bugfix 🐛, @ Client rendering

#14921 typo: anoter_key -> another_key
  doc/client_lua_api.md
  doc/lua_api.md
Labels: @ Documentation, Trivial

#14937 Revert macOS workflow to run on x86
  .github/workflows/macos.yml
Labels: @ Build, macOS, One approval ✅ ◻️

#14929 Update credits for 5.9.0
  builtin/mainmenu/tab_about.lua
  util/gather_git_credits.py
Labels: Maintenance, One approval ✅ ◻️

#14944 Disable SDL2 for 5.9.0
  .github/workflows/windows.yml
  android/native/build.gradle
  doc/compiling/linux.md
  doc/compiling/windows.md
  irr/README.md
  irr/src/CMakeLists.txt
  util/buildbot/buildwin32.sh
  util/buildbot/buildwin64.sh
  util/buildbot/common.sh
  util/buildbot/sha256sums.txt
  util/ci/common.sh
Labels: @ Build, Maintenance

#14920 Add builtin French localization
  builtin/locale/__builtin.fr.tr
Labels: @ Translation, One approval ✅ ◻️, @ Builtin

#14902 docs(locale): pt_BR localization to builtin
  builtin/locale/__builtin.pt_BR.tr
Labels: @ Translation, One approval ✅ ◻️, @ Builtin

#14955 Fix empty tables / text lists emitting row events
  src/gui/guiFormSpecMenu.cpp
Labels: One approval ✅ ◻️, Bugfix 🐛, @ Mainmenu, Formspec

#14959 Revert "Disable SDL2 for 5.9.0 (#14944)"
  .github/workflows/windows.yml
  android/native/build.gradle
  doc/compiling/linux.md
  doc/compiling/windows.md
  irr/README.md
  irr/src/CMakeLists.txt
  util/buildbot/buildwin32.sh
  util/buildbot/buildwin64.sh
  util/buildbot/common.sh
  util/buildbot/sha256sums.txt
  util/ci/common.sh
Labels: Maintenance, One approval ✅ ◻️

#14877 Improve fs::PathStartsWith to handle empty strings
  src/filesys.cpp
  src/unittest/test_filesys.cpp
Labels: Maintenance, >= Two approvals ✅ ✅, Bugfix 🐛

#14820 Optionally hide player names on the serverlist
  builtin/settingtypes.txt
  src/defaultsettings.cpp
  src/server/serverlist.cpp
Labels: @ Server / Client / Env., >= Two approvals ✅ ✅, Feature ✨, Supported by core dev

#14948 Lua API: fix OOB array access in find_nodes_near
  src/script/lua_api/l_env.cpp
Labels: @ Script API, Trivial, One approval ✅ ◻️, Bugfix 🐛

#14927 DOCS: explain how to create and remove inventory lists
  doc/lua_api.md
Labels: @ Documentation, Trivial, One approval ✅ ◻️, Bugfix 🐛

#14823 dev: add shell.nix
  .gitignore
  shell.nix
Labels: @ Build, One approval ✅ ◻️, Feature ✨, Supported by core dev

#14825 Rework object attachment handling to fix bugs
  doc/lua_api.md
  games/devtest/mods/unittests/entity.lua
  src/activeobject.h
  src/client/clientenvironment.cpp
  src/client/clientobject.h
  src/client/content_cao.cpp
  src/client/content_cao.h
  src/script/lua_api/l_object.cpp
  src/server.cpp
  src/server/clientiface.cpp
  src/server/luaentity_sao.cpp
  src/server/luaentity_sao.h
  src/server/player_sao.cpp
  src/server/serveractiveobject.h
  src/server/unit_sao.cpp
  src/server/unit_sao.h
  src/util/numeric.h
Labels: @ Server / Client / Env., @ Script API, One approval ✅ ◻️, Bugfix 🐛, Breaking Change

#14806 Fix warning about getVertexTypeDescription reaching its end
  irr/src/OpenGL/Driver.cpp
  irr/src/os.h
Labels: @ Build, One approval ✅ ◻️, Code quality, 1 approval rule testing

#14942 Show IME candidate list in Windows
  irr/src/CIrrDeviceSDL.cpp
Labels: Windows, One approval ✅ ◻️, Bugfix 🐛, 1 approval rule testing

#14918 TouchScreenGUI: Replace buttonbars with grid menu
  android/icons/gear_icon.svg
  android/icons/overflow_btn.svg
  doc/texture_packs.md
  src/gui/guiKeyChangeMenu.cpp
  src/gui/touchscreengui.cpp
  src/gui/touchscreengui.h
  textures/base/pack/gear_icon.png
  textures/base/pack/overflow_btn.png
  textures/base/pack/rare_controls.png
Labels: Android, Roadmap, >= Two approvals ✅ ✅, Feature ✨, @ Client / Controls / Input

#14897 Render clouds as flat when thickness is zero
  doc/lua_api.md
  src/client/clouds.cpp
  src/client/clouds.h
Labels: @ Script API, @ Client / Audiovisuals, One approval ✅ ◻️, Feature ✨

#14869 Clamp hotbar selection to slots that exist
  doc/lua_api.md
  games/devtest/mods/unittests/player.lua
  src/client/game.cpp
  src/client/hud.cpp
  src/network/serverpackethandler.cpp
  src/player.cpp
  src/player.h
  src/script/lua_api/l_object.cpp
Labels: One approval ✅ ◻️, Bugfix 🐛, @ Client / Controls / Input

#14793 refacto: rework the GUI element handler function
  src/gui/guiFormSpecMenu.cpp
  src/gui/guiFormSpecMenu.h
Labels: One approval ✅ ◻️, Code quality, Supported by core dev

#14784 Add vector.random_direction()
  builtin/common/vector.lua
  doc/lua_api.md
Labels: @ Script API, >= Two approvals ✅ ✅, Feature ✨, Supported by core dev

#14850 Add setting to disable smooth scrolling
  builtin/settingtypes.txt
  src/defaultsettings.cpp
  src/gui/guiScrollBar.cpp
  src/gui/guiScrollBar.h
Labels: @ Startup / Config / Util, >= Two approvals ✅ ✅, Feature ✨, UI/UX

#14962 Include unistd.h for getpid()
  irr/src/CIrrDeviceLinux.cpp
Labels: Trivial, >= Two approvals ✅ ✅, Bugfix 🐛

#14910 [#14906 2/2] Add table.keyof()
  .luacheckrc
  builtin/common/misc_helpers.lua
  builtin/common/tests/misc_helpers_spec.lua
  doc/lua_api.md
Labels: >= Two approvals ✅ ✅, Feature ✨

#14945 DOCS: state that `initial_properties` are shared between entity instances
  doc/lua_api.md
Labels: @ Documentation, >= Two approvals ✅ ✅, Bugfix 🐛

#14974 Fix chance/probability wording in lua_doc.md
  doc/lua_api.md
Labels: @ Documentation, One approval ✅ ◻️, Bugfix 🐛

#14883 Fix comment and alpha test node oopsies from #14852
  games/devtest/mods/testnodes/textures.lua
  games/devtest/mods/testnodes/textures/testnodes_alpha_compositing_bottom.png
  src/client/imagesource.cpp
Labels: Trivial, One approval ✅ ◻️, Bugfix 🐛, @ Devtest Game

#14997 DOCS: clarify rotation of `model` formspec element
  doc/lua_api.md
Labels: @ Documentation, Trivial, Bugfix 🐛

#14956 Use JSON file for credits
  builtin/mainmenu/credits.json
  builtin/mainmenu/tab_about.lua
Labels: @ Documentation, One approval ✅ ◻️, Feature ✨, Supported by core dev

#14905 Add shared mods path to get_modpaths
  src/script/lua_api/l_mainmenu.cpp
Labels: One approval ✅ ◻️, Bugfix 🐛, @ Mainmenu

#14842 Translate access denied strings
  src/network/clientpackethandler.cpp
  src/network/networkprotocol.h
Labels: @ Translation, >= Two approvals ✅ ✅, Bugfix 🐛, @ Mainmenu

#14977 Irrlicht cleanups (mostly getting rid of `core::array`)
  irr/include/CMeshBuffer.h
  irr/include/IAttributes.h
  irr/include/IFileSystem.h
  irr/include/ISceneNode.h
  irr/include/IVideoDriver.h
  irr/include/SAnimatedMesh.h
  irr/include/SMaterial.h
  irr/include/SMesh.h
  irr/include/SOverrideMaterial.h
  irr/include/SSkinMeshBuffer.h
  irr/include/irrArray.h
  irr/src/CAttributeImpl.h
  irr/src/CAttributes.cpp
  irr/src/CAttributes.h
  irr/src/CB3DMeshFileLoader.cpp
  irr/src/CBillboardSceneNode.cpp
  irr/src/CFileSystem.cpp
  irr/src/CFileSystem.h
  irr/src/CMeshManipulator.cpp
  irr/src/CNullDriver.cpp
  irr/src/CNullDriver.h
  irr/src/COGLESDriver.cpp
  irr/src/COGLESDriver.h
  irr/src/COGLESExtensionHandler.cpp
  irr/src/COGLESExtensionHandler.h
  irr/src/COpenGLCoreTexture.h
  irr/src/COpenGLDriver.cpp
  irr/src/COpenGLDriver.h
  irr/src/COpenGLExtensionHandler.cpp
  irr/src/COpenGLExtensionHandler.h
  irr/src/CSceneManager.cpp
  irr/src/CSceneManager.h
  irr/src/CXMeshFileLoader.cpp
  irr/src/CZipReader.cpp
  irr/src/CZipReader.h
  irr/src/IAttribute.h
  irr/src/OpenGL/Driver.cpp
  irr/src/OpenGL/Driver.h
  irr/src/OpenGL/MaterialRenderer.cpp
  irr/src/OpenGL/MaterialRenderer.h
  src/client/clouds.cpp
  src/client/hud.cpp
  src/client/mapblock_mesh.cpp
  src/client/minimap.cpp
  src/client/sky.cpp
Labels: Maintenance, One approval ✅ ◻️, Code quality

#14998 Remove SAO::onAttach() and SAO::onDetach()
  src/server/serveractiveobject.h
Labels: Maintenance, Trivial

#15006 [no sq] Move shaders & remove dead Irrlicht tests
  client/shaders/Irrlicht
  client/shaders/Irrlicht/OneTextureBlend.fsh
  client/shaders/Irrlicht/Renderer2D.fsh
  client/shaders/Irrlicht/Renderer2D.vsh
  client/shaders/Irrlicht/Renderer2D_noTex.fsh
  client/shaders/Irrlicht/Solid.fsh
  client/shaders/Irrlicht/Solid.vsh
  client/shaders/Irrlicht/TransparentAlphaChannel.fsh
  client/shaders/Irrlicht/TransparentAlphaChannelRef.fsh
  client/shaders/Irrlicht/TransparentVertexAlpha.fsh
  irr/.github/workflows/build.yml
  irr/CMakeLists.txt
  irr/examples/AutomatedTest/main.cpp
  irr/examples/AutomatedTest/test_array.cpp
  irr/examples/AutomatedTest/test_helper.h
  irr/examples/AutomatedTest/test_string.cpp
  irr/examples/CMakeLists.txt
  irr/media/coolguy_opt.x
  irr/media/cooltexture.png
  irr/scripts/ci-build-android.sh
  irr/scripts/ci-build-mingw.sh
  irr/scripts/ci-get-mingw.sh
  irr/scripts/sha256sums.txt
  irr/test/CMakeLists.txt
  irr/test/data/sample_16bpp_v3.bmp
  irr/test/data/sample_16bpp_v7.bmp
  irr/test/data/sample_24bpp.png
  irr/test/data/sample_24bpp_down.tga
  irr/test/data/sample_24bpp_rle_down.tga
  irr/test/data/sample_24bpp_rle_up.tga
  irr/test/data/sample_24bpp_up.tga
  irr/test/data/sample_24bpp_v3.bmp
  irr/test/data/sample_24bpp_v7.bmp
  irr/test/data/sample_4bpp_v3.bmp
  irr/test/data/sample_8bpp.png
  irr/test/data/sample_8bpp_down.tga
  irr/test/data/sample_8bpp_rle_down.tga
  irr/test/data/sample_8bpp_rle_up.tga
  irr/test/data/sample_8bpp_up.tga
  irr/test/data/sample_8bpp_v3.bmp
  irr/test/data/sample_8bpp_v3_rle.bmp
  irr/test/data/sample_8bpp_v7.bmp
  irr/test/data/sample_8bpp_v7_rle.bmp
  irr/test/image_loader_test.cpp
Labels: Maintenance, One approval ✅ ◻️, Bugfix 🐛, @ Engine Core

#15019 Make SecureRandom non-failable
  doc/lua_api.md
  src/script/lua_api/l_noise.cpp
Labels: @ Script API, >= Two approvals ✅ ✅

#15013 Remove empty form name deprecation warnings
  doc/lua_api.md
  src/script/lua_api/l_server.cpp
Labels: Trivial, >= Two approvals ✅ ✅, Bugfix 🐛

#15003 Fix Windows enabling touch controls due to existence of touchscreen
  src/defaultsettings.cpp
Labels: Windows, High priority, Trivial, One approval ✅ ◻️, Bugfix 🐛, @ Client / Controls / Input

#14179 Add possibility to easier override HP and breath engine logic by Lua
  doc/lua_api.md
  src/script/common/c_content.cpp
  src/script/lua_api/l_object.cpp
  src/script/lua_api/l_object.h
  src/server/player_sao.cpp
  src/server/player_sao.h
Labels: @ Script API, >= Two approvals ✅ ✅, Feature ✨, Concept approved

#14873 Refactor tool.cpp
  src/tool.cpp
  src/tool.h
Labels: Maintenance, Low priority, >= Two approvals ✅ ✅, Code quality

#14963 Generate Android versionCode from Major.Minor.Patch
  android/app/build.gradle
  android/build.gradle
  android/native/build.gradle
  util/bump_version.sh
Labels: @ Build, Maintenance, Android, >= Two approvals ✅ ✅

#15023 Sort clients in `minetest.get_server_status` and privs in `minetest.privs_to_string`
  builtin/common/misc_helpers.lua
  builtin/game/chat.lua
  src/server.cpp
Labels: >= Two approvals ✅ ✅, Bugfix 🐛

#15024 Fix mods folder being read read twice with RUN_IN_PLACE=1
  doc/menu_lua_api.md
  src/script/lua_api/l_mainmenu.cpp
Labels: Trivial, >= Two approvals ✅ ✅, Bugfix 🐛, @ Content / PkgMgr

#14878 Sanitize formspec fields server-side
  doc/lua_api.md
  src/network/serverpackethandler.cpp
  src/unittest/test_utilities.cpp
  src/util/string.cpp
  src/util/string.h
Labels: @ Script API, One approval ✅ ◻️, Security

#15018 Move network protocol implementation behind an interface
  src/client/client.cpp
  src/client/client.h
  src/network/CMakeLists.txt
  src/network/connection.cpp
  src/network/connection.h
  src/network/mtp/impl.cpp
  src/network/mtp/impl.h
  src/network/mtp/internal.h
  src/network/mtp/threads.cpp
  src/network/mtp/threads.h
  src/network/networkexceptions.h
  src/network/networkprotocol.h
  src/network/peerhandler.h
  src/server.cpp
  src/server.h
  src/server/clientiface.cpp
  src/server/clientiface.h
  src/unittest/test_connection.cpp
Labels: Maintenance, One approval ✅ ◻️

#15034 Fix CSM help formspec's "/" instead of "." mistake
  builtin/common/information_formspecs.lua
Labels: Trivial, Bugfix 🐛, @ Client Script API

#15049 Reword CMake message for LuaJIT detection
  cmake/Modules/FindLua.cmake
Labels: @ Build, Trivial, One approval ✅ ◻️

#15052 Meshgen: Don't get lights for not drawn solid faces
  src/client/content_mapblock.cpp
Labels: Trivial, Performance, One approval ✅ ◻️, @ Client rendering

#15044 zstd: Fix minetest.decompress lockup when data ends too early
  src/serialization.cpp
Labels: @ Script API, One approval ✅ ◻️, Bugfix 🐛

#15007 Make getting bone overrides return the "same" euler angles
  games/devtest/mods/unittests/entity.lua
  src/activeobject.h
  src/script/lua_api/l_object.cpp
Labels: @ Script API, >= Two approvals ✅ ✅, Bugfix 🐛

#15015 LocalPlayer: Restore 2u height sneak jump
  src/client/localplayer.cpp
  src/collision.cpp
  src/collision.h
Labels: One approval ✅ ◻️, Bugfix 🐛, @ Client / Controls / Input

#15066 Fix incorrect documentation of new-style particlespawner size property
  doc/lua_api.md
Labels: @ Documentation, Trivial

#15072 Menu docs: clarify that images must be escaped to correctly render on Windows
  doc/menu_lua_api.md
Labels: @ Documentation, Trivial, One approval ✅ ◻️, Bugfix 🐛

#15067 Delete OpenGL ES 1.0 driver
  builtin/settingtypes.txt
  irr/README.md
  irr/include/EDriverTypes.h
  irr/src/CEGLManager.cpp
  irr/src/CIrrDeviceLinux.cpp
  irr/src/CIrrDeviceOSX.mm
  irr/src/CIrrDeviceSDL.cpp
  irr/src/CIrrDeviceWin32.cpp
  irr/src/CMakeLists.txt
  irr/src/COGLESCommon.h
  irr/src/COGLESDriver.cpp
  irr/src/COGLESDriver.h
  irr/src/COGLESExtensionHandler.cpp
  irr/src/COGLESExtensionHandler.h
  irr/src/COGLESMaterialRenderer.h
  irr/src/COpenGLCoreCacheHandler.h
  irr/src/COpenGLCoreTexture.h
  irr/src/Irrlicht.cpp
  src/client/renderingengine.cpp
Labels: Maintenance, >= Two approvals ✅ ✅, @ Client rendering

#15064 Main menu formspec escape world name
  builtin/mainmenu/dlg_config_world.lua
Labels: Trivial, >= Two approvals ✅ ✅, Bugfix 🐛, @ Mainmenu

#14807 Add new vector utils (ceil, sign, abs, random_in_area)
  .luacheckrc
  builtin/common/math.lua
  builtin/common/misc_helpers.lua
  builtin/common/tests/after_spec.lua
  builtin/common/tests/math_spec.lua
  builtin/common/tests/misc_helpers_spec.lua
  builtin/common/tests/vector_spec.lua
  builtin/common/vector.lua
  builtin/init.lua
  doc/lua_api.md
Labels: @ Script API, >= Two approvals ✅ ✅, Feature ✨, Supported by core dev

#15080 Debloat IVideoDriver and IrrlichtDevice includes
  irr/include/EVideoTypes.h
  irr/include/IVideoDriver.h
  irr/include/IrrlichtDevice.h
  irr/include/SViewFrustum.h
  irr/src/CIrrDeviceLinux.cpp
  irr/src/CIrrDeviceSDL.cpp
  irr/src/CIrrDeviceStub.cpp
  irr/src/CIrrDeviceWin32.cpp
  irr/src/CSceneCollisionManager.cpp
  src/client/camera.cpp
  src/client/clientmap.cpp
  src/client/clientmap.h
  src/client/imagefilters.cpp
  src/client/render/anaglyph.cpp
  src/client/render/core.h
  src/client/render/pipeline.h
  src/client/renderingengine.h
  src/client/shadows/dynamicshadows.cpp
  src/client/shadows/dynamicshadowsrender.cpp
  src/client/shadows/dynamicshadowsrender.h
  src/client/shadows/shadowsScreenQuad.cpp
  src/gui/guiAnimatedImage.cpp
  src/gui/guiBox.cpp
  src/gui/guiFormSpecMenu.h
  src/gui/guiInventoryList.cpp
  src/gui/guiKeyChangeMenu.cpp
  src/gui/guiOpenURL.cpp
  src/gui/guiPasswordChange.cpp
  src/gui/guiScene.cpp
  src/gui/guiVolumeChange.cpp
  src/gui/profilergraph.cpp
  src/gui/profilergraph.h
  src/gui/touchcontrols.cpp
  src/gui/touchcontrols.h
  src/irrlichttypes_extrabloated.h
Labels: Maintenance, Trivial, One approval ✅ ◻️

#14321 Add hotbar Lua HUD element and replace hardcoded hotbar
  builtin/game/features.lua
  builtin/game/hud.lua
  doc/lua_api.md
  games/devtest/mods/testhud/init.lua
  src/client/hud.cpp
  src/client/hud.h
  src/client/render/plain.cpp
  src/hud.cpp
  src/hud.h
  src/network/networkprotocol.h
  src/script/common/c_content.cpp
Labels: @ Script API, Roadmap, >= Two approvals ✅ ✅, Feature ✨, @ Client rendering

#15022 Restore proportional minimap scaling
  builtin/game/hud.lua
  doc/lua_api.md
  src/client/hud.cpp
  src/network/networkprotocol.h
Labels: @ Client / Audiovisuals, One approval ✅ ◻️, Bugfix 🐛

#15090 TouchControls: Fix outdated player controls in TOSERVER_INTERACT
  src/client/game.cpp
Labels: Android, One approval ✅ ◻️, Bugfix 🐛, @ Client / Controls / Input, Regression

#15089 Basic unittest for HP change calculation
  games/devtest/mods/unittests/player.lua
Labels: Maintenance, One approval ✅ ◻️

#15094 Fix uninitialized SkyboxParams::fog_color
  src/skyparams.h
Labels: One approval ✅ ◻️, Bugfix 🐛, @ Client rendering, Regression

#15077 Disable CRT security warnings in MSVC.
  irr/src/CMakeLists.txt
  lib/lua/CMakeLists.txt
  src/CMakeLists.txt
Labels: @ Build, Maintenance, >= Two approvals ✅ ✅
