Repository luanti-org/luanti, pull requests merged in 2024-07, with the labels that each got.

#14794 Log node/ore name when detecting deprecated fields
  src/script/common/c_content.cpp
  src/script/common/c_converter.h
  src/script/lua_api/l_mapgen.cpp
Labels: Maintenance, >= Two approvals ✅ ✅

#14760 Fix new texture properties not being sent for minetest.add_particle
  doc/lua_api.md
  src/particles.cpp
  src/particles.h
Labels: @ Network, One approval ✅ ◻️, Bugfix 🐛

#14791 More missing newlines
  doc/lua_api.md
Labels: @ Documentation, Trivial, One approval ✅ ◻️

#14769 Help modders deal with object invalidation
  builtin/game/misc.lua
  doc/lua_api.md
  games/devtest/mods/unittests/entity.lua
  src/script/lua_api/l_env.cpp
  src/script/lua_api/l_object.cpp
  src/script/lua_api/l_object.h
Labels: @ Script API, Maintenance, One approval ✅ ◻️, Bugfix 🐛

#14709 GUITable: Scale images with display density / row height
  doc/lua_api.md
  games/devtest/mods/testformspec/formspec.lua
  src/gui/guiTable.cpp
  src/gui/guiTable.h
Labels: @ Client / Audiovisuals, One approval ✅ ◻️, Bugfix 🐛, Formspec, UI/UX

#14804 Particle(spawner) documentation fixes & improvements
  doc/lua_api.md
  src/network/networkprotocol.h
Labels: @ Documentation, One approval ✅ ◻️, Bugfix 🐛

#14837 Set ContentDB updates detection cache time to 24 hours
  builtin/mainmenu/content/update_detector.lua
Labels: Maintenance, One approval ✅ ◻️, @ Content / PkgMgr

#14833 Fix path traversal in mainmenu's extract_zip
  src/filesys.cpp
Labels: >= Two approvals ✅ ✅, Bugfix 🐛, @ Mainmenu

#14849 Un-deprecate redis database backend
  src/database/database-redis.cpp
Labels: @ Server / Client / Env., Maintenance, >= Two approvals ✅ ✅

#14841 Allow main menu gamebar scroll to loop
  builtin/fstk/buttonbar.lua
Labels: >= Two approvals ✅ ✅, Feature ✨, @ Mainmenu, UI/UX

#14648 Better AppStream metadata
  CMakeLists.txt
  misc/net.minetest.minetest.appdata.xml
  misc/net.minetest.minetest.desktop
  misc/net.minetest.minetest.metainfo.xml
  util/bump_version.sh
Labels: @ Build, Maintenance, One approval ✅ ◻️, 1 approval rule testing

#14862 Set SDL_HINT_APP_NAME to Minetest
  irr/src/CIrrDeviceSDL.cpp
Labels: @ Startup / Config / Util, @ Build, >= Two approvals ✅ ✅, Bugfix 🐛

#14845 Warn contributors about not to run updatepo.sh manually
  .github/CONTRIBUTING.md
Labels: @ Documentation, Trivial, One approval ✅ ◻️

#14851 Minimize data sent in the default user agent
  src/httpfetch.cpp
  src/porting.cpp
  src/porting.h
Labels: One approval ✅ ◻️, Bugfix 🐛, @ Engine Core

#14871 Fix blockseed for on_generated in mapgen env
  src/emerge.cpp
  src/emerge.h
  src/mapgen/mapgen.h
  src/script/cpp_api/s_mapgen.cpp
  src/script/cpp_api/s_mapgen.h
Labels: @ Script API, Trivial, One approval ✅ ◻️, Bugfix 🐛

#14864 Fix `The variable 'irrevent' is being used without being initialized` error in Debug build from MSVS
  irr/src/CIrrDeviceSDL.cpp
Labels: @ Startup / Config / Util, One approval ✅ ◻️, Bugfix 🐛

#14852 Restore buggy texture overlay modifier
  doc/lua_api.md
  src/client/imagesource.cpp
Labels: @ Script API, One approval ✅ ◻️, Bugfix 🐛, Textures, @ Client rendering

#14827 Add setting to disable Content tab update indicator
  builtin/mainmenu/tab_content.lua
  builtin/settingtypes.txt
  src/defaultsettings.cpp
Labels: One approval ✅ ◻️, @ Content / PkgMgr

#14661 Fix inventory items unresponsive after tab interaction until LMB click on formspec
  src/gui/guiFormSpecMenu.cpp
Labels: >= Two approvals ✅ ✅, Bugfix 🐛, @ Client / Controls / Input

#14865 Remove mod_translation_updater.py and move it to minetest/modtools
  doc/lua_api.md
  util/README_mod_translation_updater.md
  util/mod_translation_updater.py
Labels: @ Translation, Trivial, One approval ✅ ◻️, Concept approved

#14872 Clean up MSVC warnings in CIrrDeviceSDL.{h,cc}
  irr/src/CIrrDeviceSDL.cpp
  irr/src/CIrrDeviceSDL.h
Labels: Maintenance, >= Two approvals ✅ ✅, Code quality

#14896 Restore ability to enable flags in settings
  builtin/mainmenu/settings/components.lua
Labels: >= Two approvals ✅ ✅, Bugfix 🐛, @ Mainmenu

#14891 Hide enable_touch setting on Android
  builtin/settingtypes.txt
Labels: Trivial, >= Two approvals ✅ ✅

#14889 Sounds: Partial revert of #14436 and #14341
  doc/lua_api.md
  src/network/clientpackethandler.cpp
  src/server.cpp
  src/server.h
Labels: Bug, @ Server / Client / Env., One approval ✅ ◻️, Bugfix 🐛
