Repository luanti-org/luanti, pull requests merged in 2024-05, with the labels that each got.

#14600 Warn at unknown CMAKE_BUILD_TYPE values
  src/CMakeLists.txt
Labels: @ Build, Trivial, One approval ✅ ◻️

#14603 Chat console: Prevent input loss on double open
  src/gui/guiChatConsole.cpp
  src/gui/mainmenumanager.h
Labels: One approval ✅ ◻️, Bugfix 🐛, @ Client / Controls / Input

#14606 TouchScreenGUI: Fix shootline not being updated if press and release happen in the same step
  src/gui/touchscreengui.cpp
  src/gui/touchscreengui.h
Labels: Android, Trivial, One approval ✅ ◻️, Bugfix 🐛, @ Client / Controls / Input

#14608 Add object's own position for each collision to moveresult
  builtin/game/features.lua
  builtin/game/misc_s.lua
  doc/lua_api.md
  src/collision.cpp
  src/collision.h
  src/script/common/c_content.cpp
Labels: @ Script API, One approval ✅ ◻️, Feature ✨, Supported by core dev

#14539 Gate disabling of fog or camera update behind 'debug' priv
  builtin/settingtypes.txt
  src/client/game.cpp
  src/defaultsettings.cpp
Labels: @ Client / Audiovisuals, One approval ✅ ◻️, Bugfix 🐛

#14550 Allow quoting hypertext attribute values
  doc/lua_api.md
  games/devtest/mods/testformspec/formspec.lua
  src/gui/guiHyperText.cpp
Labels: @ Script API, @ Client / Audiovisuals, One approval ✅ ◻️, Bugfix 🐛, Formspec

#14560 Add unit tests for MapBlock (de)serialization
  src/unittest/CMakeLists.txt
  src/unittest/test_mapblock.cpp
Labels: Maintenance, @ Engine Core, 1 approval rule testing

#14624 Add forgotten opensuse dependency
  doc/compiling/linux.md
Labels: @ Documentation, Trivial

#14615 Fix curl compatibility issues with colorize_url
  src/gui/guiOpenURL.cpp
  src/unittest/test_utilities.cpp
  src/util/colorize.cpp
  src/util/colorize.h
Labels: One approval ✅ ◻️, Bugfix 🐛

#14626 Cleanup Removed Java 17 Options
  android/gradle.properties
Labels: @ Build, Android, Trivial

#14616 Add benchmarks for server::ActiveObjectMgr
  src/benchmark/CMakeLists.txt
  src/benchmark/benchmark_activeobjectmgr.cpp
  src/server/serveractiveobject.h
Labels: @ Server / Client / Env., Maintenance, 1 approval rule testing

#14584 Android CI: Additionally make an AAB for uploading to the Play Store
  .github/workflows/android.yml
Labels: Maintenance, One approval ✅ ◻️

#14605 Close formspecs with a single tap outside
  src/gui/guiFormSpecMenu.cpp
  src/gui/modalMenu.cpp
  src/gui/modalMenu.h
Labels: Android, One approval ✅ ◻️, Feature ✨, @ Client / Controls / Input, Formspec, UI/UX

#14621 Dockerfile: Use the default branch when cloning libspatialindex repository
  Dockerfile
Labels: @ Build, Trivial, >= Two approvals ✅ ✅, Bugfix 🐛

#14630 Close buttonbars when hiding TouchScreenGUI
  src/gui/touchscreengui.cpp
Labels: Android, Trivial, One approval ✅ ◻️, @ Client / Controls / Input

#14636 Fix crash if zip file cannot be opened
  builtin/mainmenu/content/contentdb.lua
  src/filesys.cpp
Labels: One approval ✅ ◻️, Bugfix 🐛, @ Content / PkgMgr

#14637 Add option for random mod load order
  builtin/settingtypes.txt
  src/content/mod_configuration.cpp
  src/defaultsettings.cpp
Labels: @ Script API, >= Two approvals ✅ ✅, Feature ✨, Supported by core dev

#14641 [no sq] GL fixes
  irr/src/OpenGL/ExtensionHandler.cpp
  irr/src/OpenGL/ExtensionHandler.h
  irr/src/OpenGL3/Driver.cpp
  irr/src/OpenGLES2/Driver.cpp
Labels: One approval ✅ ◻️, Bugfix 🐛

#14653 Do not bother to assert that a u8 is >= 0
  src/mapblock.h
Labels: Trivial, One approval ✅ ◻️

#14634 Reenable fog toggle unless server restricts fog distance
  builtin/settingtypes.txt
  doc/lua_api.md
  src/client/game.cpp
  src/defaultsettings.cpp
Labels: @ Client / Audiovisuals, >= Two approvals ✅ ✅, Feature ✨

#14627 Introduce proper error handling for file streams
  src/client/client.cpp
  src/client/filecache.cpp
  src/client/shader.cpp
  src/client/shadows/dynamicshadowsrender.cpp
  src/content/content.cpp
  src/database/database-files.cpp
  src/filesys.cpp
  src/filesys.h
  src/gettext.cpp
  src/gui/guiEngine.cpp
  src/log.cpp
  src/map_settings_manager.cpp
  src/mapgen/mg_schematic.cpp
  src/porting.cpp
  src/porting.h
  src/script/lua_api/l_areastore.cpp
  src/server.cpp
  src/server/ban.cpp
  src/settings.cpp
  src/texture_override.cpp
  src/unittest/test.cpp
  src/unittest/test_ban.cpp
  src/unittest/test_filesys.cpp
Labels: Maintenance, Bugfix 🐛, @ Engine Core, 1 approval rule testing

#14654 Fix some clang compiler warnings
  irr/src/COSOperator.cpp
  irr/src/OpenGL/Driver.cpp
  irr/src/OpenGL/Driver.h
  irr/src/OpenGL/MaterialRenderer.h
  src/client/mapblock_mesh.cpp
  src/client/shadows/dynamicshadows.cpp
  src/collision.cpp
  src/gui/guiTable.cpp
  src/irrlicht_changes/static_text.cpp
  src/network/connection_internal.h
Labels: Maintenance, One approval ✅ ◻️

#14639 Don't bundle Development Test on macOS
  .github/workflows/macos.yml
Labels: @ Build, Trivial, One approval ✅ ◻️, Bugfix 🐛

#14638 Fixes to Docker GitHub Actions workflow
  .github/workflows/docker_image.yml
Labels: @ Build, One approval ✅ ◻️, Bugfix 🐛, 1 approval rule testing

#14677 Enable RTTI for Irrlicht on MSVC
  irr/src/CMakeLists.txt
Labels: @ Build, Windows, Trivial, One approval ✅ ◻️, Bugfix 🐛

#14663 Restore vector type check
  src/script/common/c_converter.cpp
Labels: @ Script API, >= Two approvals ✅ ✅, Bugfix 🐛

#14675 Allow removal of item definition fields
  builtin/game/register.lua
  doc/lua_api.md
Labels: Trivial, Feature ✨

#14678 Update SDL for mingw builds
  util/buildbot/common.sh
  util/buildbot/sha256sums.txt
Labels: @ Build, Maintenance, Windows, One approval ✅ ◻️

#14597 Display background & moving progress bar on shutdown screen
  src/client/game.cpp
  src/client/renderingengine.cpp
  src/client/renderingengine.h
Labels: @ Startup / Config / Util, >= Two approvals ✅ ✅, Feature ✨, UI/UX, Supported by core dev

#14657 Fix inventory: Quickly picking up item and placing it again no longer works
  src/gui/guiFormSpecMenu.cpp
Labels: >= Two approvals ✅ ✅, Bugfix 🐛, @ Client / Controls / Input

#14332 Fix glitch through celiing with Sneak Glitch
  src/client/localplayer.cpp
  src/collision.cpp
  src/collision.h
Labels: >= Two approvals ✅ ✅, Bugfix 🐛, @ Client / Controls / Input

#14660 Flip "opaque_water" setting to "translucent_liquids"
  builtin/settingtypes.txt
  src/defaultsettings.cpp
  src/main.cpp
  src/migratesettings.h
  src/nodedef.cpp
  src/nodedef.h
Labels: @ Startup / Config / Util, >= Two approvals ✅ ✅

#14565 Upgrade client active object mgr tests to Catch2
  CMakeLists.txt
  lib/catch2/CMakeLists.txt
  src/CMakeLists.txt
  src/activeobjectmgr.h
  src/unittest/test.cpp
  src/unittest/test_clientactiveobjectmgr.cpp
Labels: Roadmap, >= Two approvals ✅ ✅, Feature ✨, Code quality

#14684 Enable "FULL" debug info for Android build
  android/native/build.gradle
Labels: @ Build, Maintenance, Android, One approval ✅ ◻️

#14688 Fix artifacts with bloom + tonemapping on ogles2
  client/shaders/second_stage/opengl_fragment.glsl
Labels: Android, One approval ✅ ◻️, Bugfix 🐛, @ Client rendering

#14689 Consistent width for internal scrollbars of formspec elements
  src/client/clientlauncher.cpp
  src/gui/guiScrollBar.cpp
  src/gui/guiTable.cpp
Labels: Maintenance, One approval ✅ ◻️, @ Client / Controls / Input, Formspec, UI/UX

#14690 Scale C++ menus down to fit the window
  src/gui/guiKeyChangeMenu.cpp
  src/gui/guiOpenURL.cpp
  src/gui/guiPasswordChange.cpp
  src/gui/guiVolumeChange.cpp
  src/gui/modalMenu.cpp
  src/gui/modalMenu.h
Labels: @ Client / Audiovisuals, Android, One approval ✅ ◻️, Bugfix 🐛, Formspec

#13935 Add documentation for IDE developer setup
  .gitignore
  .vscode/extensions.json
  CMakePresets.json
  doc/ides/images/jetbrains_cmake_profiles.png
  doc/ides/images/jetbrains_ide.png
  doc/ides/images/jetbrains_notification_profiles.png
  doc/ides/images/jetbrains_open_project_wizard_profiles.png
  doc/ides/images/jetbrains_open_project_wizard_windows_cmake.png
  doc/ides/images/jetbrains_open_project_wizard_windows_compiler.png
  doc/ides/images/jetbrains_vcpkg.png
  doc/ides/images/vscode_cmake_preset_selection.png
  doc/ides/images/vscode_toolbar.png
  doc/ides/jetbrains.md
  doc/ides/visual_studio.md
  doc/ides/vscode.md
Labels: @ Documentation, One approval ✅ ◻️, Feature ✨, Supported by core dev

#14574 Translation updater: Add support for function call without parantheses
  util/mod_translation_updater.py
Labels: @ Startup / Config / Util, One approval ✅ ◻️, Feature ✨, Supported by core dev

#14679 Mark Redis database backend as deprecated
  src/database/database-redis.cpp
Labels: @ Server / Client / Env., Discussion

#14683 Android: Don't crash if there is no web browser installed
  android/app/src/main/java/net/minetest/minetest/GameActivity.java
  android/app/src/main/res/values/strings.xml
Labels: @ Startup / Config / Util, Android, One approval ✅ ◻️, Bugfix 🐛

#14529 [nosq] Sound loading: Fix issues where ov_read skips samples, and better error handling
  src/client/sound/ogg_file.cpp
Labels: @ Client / Audiovisuals, One approval ✅ ◻️, Bugfix 🐛, Sounds

#14695 Update no games message to give more context
  builtin/mainmenu/tab_local.lua
Labels: @ Documentation, >= Two approvals ✅ ✅, @ Mainmenu, UI/UX
