Repository luanti-org/luanti, pull requests merged in 2024-12, with the labels that each got.

#15491 Add Minetest keyword to desktop file for backwards compatibility
  misc/net.minetest.minetest.desktop
Labels: @ Build, Trivial, One approval ✅ ◻️

#15496 Cleanup ban
  src/server/ban.cpp
  src/server/ban.h
Labels: @ Startup / Config / Util, Maintenance, >= Two approvals ✅ ✅

#15481 Fix script security path normalization in presence of links
  src/filesys.cpp
  src/filesys.h
  src/porting.cpp
  src/porting.h
  src/script/cpp_api/s_security.cpp
  src/script/scripting_mainmenu.cpp
  src/unittest/test_filesys.cpp
Labels: High priority, One approval ✅ ◻️, Bugfix 🐛

#15489 Use `add_compile_options` where appropriate
  src/CMakeLists.txt
Labels: @ Build, Maintenance, Trivial

#15493 Less explicit memory management in irrlicht image writer classes
  irr/src/CImageWriterJPG.cpp
  irr/src/CImageWriterPNG.cpp
Labels: >= Two approvals ✅ ✅, Code quality, @ Engine Core

#15509 Fix false positive compiler warning
  irr/src/CGLTFMeshFileLoader.cpp
Labels: Maintenance, Trivial

#15438 Make string to v3f parsing consistent, replace `core.setting_get_pos()` by `core.settings:get_pos()`
  builtin/game/misc_s.lua
  builtin/game/static_spawn.lua
  doc/lua_api.md
  src/client/hud.cpp
  src/database/database-files.cpp
  src/gui/guiChatConsole.cpp
  src/gui/guiFormSpecMenu.cpp
  src/inventory.cpp
  src/mapgen/mapgen_fractal.cpp
  src/script/lua_api/l_settings.cpp
  src/script/lua_api/l_settings.h
  src/server.cpp
  src/settings.cpp
  src/settings.h
  src/unittest/test_settings.cpp
  src/util/string.cpp
  src/util/string.h
Labels: @ Script API, Maintenance, >= Two approvals ✅ ✅, @ Engine Core

#15511 Refactor: Merge `ISkinnedMesh` and `CSkinnedMesh` into `SkinnedMesh`
  irr/include/IBoneSceneNode.h
  irr/include/ISceneManager.h
  irr/include/ISkinnedMesh.h
  irr/include/SkinnedMesh.h
  irr/src/CAnimatedMeshSceneNode.cpp
  irr/src/CB3DMeshFileLoader.cpp
  irr/src/CB3DMeshFileLoader.h
  irr/src/CGLTFMeshFileLoader.cpp
  irr/src/CGLTFMeshFileLoader.h
  irr/src/CMakeLists.txt
  irr/src/CMeshManipulator.cpp
  irr/src/CMeshSceneNode.cpp
  irr/src/CSceneManager.cpp
  irr/src/CSceneManager.h
  irr/src/CXMeshFileLoader.cpp
  irr/src/CXMeshFileLoader.h
  irr/src/SkinnedMesh.cpp
  src/unittest/test_irr_gltf_mesh_loader.cpp
Labels: Maintenance, One approval ✅ ◻️, Code quality

#15310 Allow non-normalized weights in glTF models
  doc/lua_api.md
  irr/src/CGLTFMeshFileLoader.cpp
  irr/src/CGLTFMeshFileLoader.h
Labels: Maintenance, One approval ✅ ◻️

#15513 L-System trees fix fruit node resolver
  src/mapgen/treegen.cpp
  src/script/common/c_content.cpp
Labels: @ Script API, >= Two approvals ✅ ✅, Bugfix 🐛, Regression

#15470 Formspec: Move tooltip above cursor when lacking space
  src/gui/guiFormSpecMenu.cpp
Labels: Trivial, Bugfix 🐛, Formspec

#15459 Fix distorted Sun, Moon and Star visuals based on Orbit Tilt
  src/client/sky.cpp
Labels: @ Client / Audiovisuals, One approval ✅ ◻️, Bugfix 🐛

#15520 Fix mainmenu crash if no servers match search
  builtin/mainmenu/tab_online.lua
Labels: Trivial, Bugfix 🐛, @ Mainmenu

#15415 Add `core.spawn_tree_on_vmanip`
  doc/lua_api.md
  games/devtest/mods/testitems/init.lua
  games/devtest/mods/testitems/textures/testitems_tree_spawner.png
  games/devtest/mods/testitems/textures/testitems_tree_spawner_vmanip.png
  src/mapgen/treegen.cpp
  src/mapgen/treegen.h
  src/script/lua_api/l_env.cpp
  src/script/lua_api/l_mapgen.cpp
  src/script/lua_api/l_mapgen.h
Labels: @ Script API, @ Mapgen, >= Two approvals ✅ ✅, Feature ✨

#15486 Adopt #13446 server favorite button
  builtin/mainmenu/tab_online.lua
Labels: Roadmap, >= Two approvals ✅ ✅, Feature ✨, @ Mainmenu, UI/UX

#15538 Server list over https
  builtin/settingtypes.txt
  src/defaultsettings.cpp
Labels: @ Network, >= Two approvals ✅ ✅, Security

#15530 Main menu: show favorite removal button for offline servers
  builtin/mainmenu/tab_online.lua
Labels: One approval ✅ ◻️, Bugfix 🐛, @ Mainmenu

#15522 Refactor `SkinnedMesh`
  irr/include/SkinnedMesh.h
  irr/src/CAnimatedMeshSceneNode.cpp
  irr/src/CAnimatedMeshSceneNode.h
  irr/src/CB3DMeshFileLoader.cpp
  irr/src/CB3DMeshFileLoader.h
  irr/src/CGLTFMeshFileLoader.cpp
  irr/src/CGLTFMeshFileLoader.h
  irr/src/CXMeshFileLoader.cpp
  irr/src/CXMeshFileLoader.h
  irr/src/SkinnedMesh.cpp
Labels: Maintenance, One approval ✅ ◻️, Code quality, @ Engine Core

#15519 Fixup parsing for `Plural-Forms`
  src/gettext_plural_form.cpp
  src/gettext_plural_form.h
  src/unittest/test_translations.cpp
Labels: @ Translation, One approval ✅ ◻️, Bugfix 🐛, 1 approval rule testing

#15476 Change `NS` symbol for `core.translate_n` to `PS` to avoid clash with old code
  doc/lua_api.md
Labels: @ Documentation, @ Translation, Trivial, >= Two approvals ✅ ✅, Bugfix 🐛

#15233 Performance boost for Raycast
  doc/lua_api.md
  src/environment.cpp
  src/nodedef.cpp
  src/nodedef.h
Labels: @ Script API, Performance, >= Two approvals ✅ ✅

#15542 Test & document conventions used by matrix4::setRotation*
  irr/include/matrix4.h
  src/unittest/CMakeLists.txt
  src/unittest/test_irr_matrix4.cpp
Labels: Maintenance, One approval ✅ ◻️, Code quality

#15540 Get rid of now obsolete workaround for collision detection bugs
  src/client/content_cao.cpp
Labels: Maintenance, Low priority, One approval ✅ ◻️

#15553 Revert "Optimize raycast performance"
  doc/lua_api.md
  src/environment.cpp
  src/nodedef.cpp
  src/nodedef.h
Labels: Trivial, One approval ✅ ◻️, Bugfix 🐛

#15550 Restore `.x` models to working state
  .gitattributes
  games/devtest/mods/testentities/models/LICENSE.txt
  games/devtest/mods/testentities/models/testentities_lava_flan.png
  games/devtest/mods/testentities/models/testentities_lava_flan.x
  games/devtest/mods/testentities/visuals.lua
  irr/src/CXMeshFileLoader.cpp
Labels: One approval ✅ ◻️, Bugfix 🐛, @ Client rendering

#15572 Fix threshold value for imageCleanTransparent
  src/client/imagesource.cpp
Labels: @ Client / Audiovisuals, Trivial, One approval ✅ ◻️, Bugfix 🐛, Textures

#15580 Remove game_ui from Client
  src/client/client.cpp
  src/client/client.h
  src/client/game.cpp
Labels: Maintenance, Trivial, Code quality

#15579 Minor API reference fixes
  doc/lua_api.md
Labels: @ Documentation, Trivial

#15536 Add server url button to main menu
  LICENSE.txt
  builtin/mainmenu/tab_online.lua
  textures/base/pack/server_url.png
Labels: Roadmap, >= Two approvals ✅ ✅, Feature ✨, @ Mainmenu

#15578 Move formspec code from game.cpp to separate file
  src/client/CMakeLists.txt
  src/client/game.cpp
  src/client/game_formspec.cpp
  src/client/game_formspec.h
  src/client/gameui.cpp
  src/client/gameui.h
Labels: Maintenance, Roadmap, One approval ✅ ◻️, Code quality

#15581 IGUIFont / CGUITTFont code cleanups
  irr/include/IGUIFont.h
  irr/include/IGUIFontBitmap.h
  irr/src/CGUIEditBox.cpp
  irr/src/CGUIFont.cpp
  irr/src/CGUIFont.h
  irr/src/CGUIStaticText.cpp
  src/client/fontengine.cpp
  src/gui/guiEditBoxWithScrollbar.cpp
  src/gui/guiFormSpecMenu.cpp
  src/irrlicht_changes/CGUITTFont.cpp
  src/irrlicht_changes/CGUITTFont.h
  src/irrlicht_changes/static_text.cpp
Labels: Maintenance, One approval ✅ ◻️, Code quality

#15554 Reorder client initialization (rebased)
  src/server.cpp
  src/server.h
  src/server/player_sao.h
  src/serverenvironment.cpp
  src/serverenvironment.h
Labels: @ Script API, One approval ✅ ◻️, Bugfix 🐛

#15525 Add glTF STEP interpolation support
  doc/lua_api.md
  games/devtest/mods/gltf/init.lua
  games/devtest/mods/gltf/models/gltf_simple_skin_step.gltf
  irr/src/CGLTFMeshFileLoader.cpp
Labels: @ Script API, One approval ✅ ◻️, Feature ✨

#15596 Fix some compiler warnings
  irr/src/os.cpp
  src/client/content_mapblock.cpp
  src/client/content_mapblock.h
  src/client/mapblock_mesh.cpp
  src/client/wieldmesh.cpp
  src/log.cpp
  src/unittest/test_content_mapblock.cpp
Labels: Maintenance, Trivial, Code quality, 1 approval rule testing

#15591 IrrlichtMt: Move OpenGL 3+ transformation matrix to shaders
  client/shaders/Irrlicht/Renderer2D.vsh
  irr/src/OpenGL/Driver.cpp
  irr/src/OpenGL/Driver.h
  irr/src/OpenGL/Renderer2D.cpp
  irr/src/OpenGL/Renderer2D.h
Labels: Maintenance, >= Two approvals ✅ ✅, @ Client rendering

#15586 Fix situation around aabbox3d default constructor
  irr/include/CMeshBuffer.h
  irr/include/IMeshManipulator.h
  irr/include/SAnimatedMesh.h
  irr/include/SMesh.h
  irr/include/SSkinMeshBuffer.h
  irr/include/SViewFrustum.h
  irr/include/SkinnedMesh.h
  irr/include/aabbox3d.h
  irr/src/CAnimatedMeshSceneNode.h
  irr/src/CBillboardSceneNode.h
  irr/src/CBoneSceneNode.h
  irr/src/CDummyTransformationSceneNode.h
  irr/src/CEmptySceneNode.h
  irr/src/CMeshSceneNode.h
  irr/src/CSceneManager.cpp
  irr/src/SkinnedMesh.cpp
  src/client/activeobjectmgr.cpp
  src/client/clientenvironment.cpp
  src/client/clouds.h
  src/client/game.cpp
  src/client/localplayer.cpp
  src/client/mesh.cpp
  src/client/particles.cpp
  src/client/sky.cpp
  src/client/sky.h
  src/client/wieldmesh.cpp
  src/client/wieldmesh.h
  src/collision.cpp
  src/nodedef.cpp
  src/nodedef.h
  src/pathfinder.cpp
  src/script/common/c_converter.cpp
  src/script/common/c_converter.h
  src/serverenvironment.cpp
Labels: One approval ✅ ◻️, Bugfix 🐛, Code quality

#15602 TouchControls: More methods instead of static functions
  src/gui/touchcontrols.cpp
  src/gui/touchcontrols.h
Labels: Maintenance, Android, One approval ✅ ◻️, @ Client / Controls / Input, Code quality

#15607 Add explanation to touchscreen item tooltip code
  src/gui/guiInventoryList.cpp
Labels: Maintenance, Trivial, One approval ✅ ◻️

#15609 Remove normal map leftovers
  doc/lua_api.md
  src/client/imagesource.cpp
  src/client/texturesource.cpp
  src/client/texturesource.h
Labels: Maintenance, One approval ✅ ◻️, @ Client rendering, Code quality
