Repository luanti-org/luanti, pull requests merged in 2025-06, with the labels that each got.

#16209 Print Luanti version after ascii art
  src/server.cpp
Labels: @ Startup / Config / Util, Maintenance, Trivial, >= Two approvals ✅ ✅

#16204 Don't break when multiple dialogs are shown on startup
  builtin/fstk/ui.lua
  builtin/mainmenu/dlg_rebind_keys.lua
  builtin/mainmenu/dlg_reinstall_mtg.lua
  builtin/mainmenu/init.lua
Labels: One approval ✅ ◻️, Bugfix 🐛, @ Mainmenu

#16160 Avoid signal-unsafe operations in POSIX signal handler
  src/client/clientlauncher.cpp
  src/client/game.cpp
  src/client/game.h
  src/gui/guiEngine.cpp
  src/gui/guiEngine.h
  src/main.cpp
  src/porting.cpp
  src/porting.h
  src/server.cpp
  src/server.h
  src/terminal_chat_console.h
Labels: Linux, One approval ✅ ◻️, Bugfix 🐛, 1 approval rule

#15722 Fix and clean up skeletal animation in Irrlicht
  doc/lua_api.md
  games/devtest/mods/testentities/models/LICENSE.txt
  games/devtest/mods/testentities/models/testentities_cool_guy.png
  games/devtest/mods/testentities/models/testentities_cool_guy.x
  games/devtest/mods/testentities/visuals.lua
  irr/include/IAnimatedMesh.h
  irr/include/IAnimatedMeshSceneNode.h
  irr/include/IBoneSceneNode.h
  irr/include/IMesh.h
  irr/include/IMeshManipulator.h
  irr/include/IMeshSceneNode.h
  irr/include/ISceneNode.h
  irr/include/SAnimatedMesh.h
  irr/include/SMesh.h
  irr/include/SkinnedMesh.h
  irr/include/Transform.h
  irr/include/quaternion.h
  irr/src/CAnimatedMeshSceneNode.cpp
  irr/src/CAnimatedMeshSceneNode.h
  irr/src/CB3DMeshFileLoader.cpp
  irr/src/CBoneSceneNode.cpp
  irr/src/CBoneSceneNode.h
  irr/src/CGLTFMeshFileLoader.cpp
  irr/src/CMakeLists.txt
  irr/src/CMeshCache.cpp
  irr/src/CMeshManipulator.cpp
  irr/src/CMeshManipulator.h
  irr/src/CNullDriver.cpp
  irr/src/COBJMeshFileLoader.cpp
  irr/src/CSceneManager.cpp
  irr/src/CXMeshFileLoader.cpp
  irr/src/SkinnedMesh.cpp
  lib/tiniergltf/tiniergltf.hpp
  src/client/content_cao.cpp
  src/client/content_cao.h
  src/client/mesh.cpp
  src/nodedef.cpp
  src/unittest/CMakeLists.txt
  src/unittest/test_irr_gltf_mesh_loader.cpp
  src/unittest/test_irr_x_mesh_loader.cpp
Labels: Maintenance, Bugfix 🐛, @ Client rendering, Code quality

#16167 Formspec: change tabs with ctrl+tab
  src/gui/guiFormSpecMenu.cpp
  src/gui/guiTable.cpp
Labels: Roadmap, >= Two approvals ✅ ✅, Feature ✨, @ Mainmenu, @ Client / Controls / Input, Formspec, UI/UX

#16230 Don't force-enable tileable_horizontal/vertical for solid nodes
  src/client/content_mapblock.cpp
Labels: Trivial, >= Two approvals ✅ ✅, Bugfix 🐛, @ Client rendering

#16235 Add documentation for ValueNoise during load time
  doc/lua_api.md
Labels: @ Mapgen, @ Documentation, Trivial, One approval ✅ ◻️

#16256 Fix some misinformation in `world_format.md`
  doc/world_format.md
Labels: @ Documentation, Trivial

#16101 Detect mouse moving out of inventory slot
  src/gui/guiInventoryList.cpp
Labels: One approval ✅ ◻️, Bugfix 🐛, @ Client / Controls / Input, Formspec

#16153 Fix in links and names
  .github/CONTRIBUTING.md
  README.md
  builtin/common/settings/generate_from_settingtypes.lua
  doc/android.md
  doc/developing/README.md
  doc/direction.md
  doc/lua_api.md
  irr/README.md
  misc/org.luanti.luanti.metainfo.xml
  misc/redirect.html
  src/CMakeLists.txt
  src/server.cpp
  src/serverenvironment.cpp
Labels: @ Documentation, One approval ✅ ◻️

#16274 Add test benchmark for Map
  src/benchmark/CMakeLists.txt
  src/benchmark/benchmark_map.cpp
Labels: Trivial, One approval ✅ ◻️

#15963 Formspec: Show a player inventory using core.show_formspec
  doc/lua_api.md
  src/client/game.cpp
  src/client/game_formspec.cpp
  src/client/game_formspec.h
  src/client/localplayer.h
  src/network/clientpackethandler.cpp
  src/network/serveropcodes.cpp
  src/remoteplayer.h
  src/script/lua_api/l_object.cpp
  src/server.cpp
Labels: One approval ✅ ◻️, Feature ✨, Formspec, Roadmap: supported by core dev

#16281 Revert "Detect mouse moving out of inventory slot (#16101)"
  src/gui/guiInventoryList.cpp
Labels: One approval ✅ ◻️, Bugfix 🐛

#16253 Add documentation index for `doc/` as `README.md`, and small docs fixes
  doc/README.md
  doc/developing/README.md
  doc/developing/profiling.md
  doc/fst_api.txt
  doc/protocol.txt
Labels: @ Documentation, >= Two approvals ✅ ✅

#16286 Avoid copying empty blocks for mesh-generation
  src/client/mesh_generator_thread.cpp
Labels: Trivial, Performance, One approval ✅ ◻️

#16289 Add core.get_mapgen_chunksize()
  doc/lua_api.md
  games/devtest/mods/unittests/inside_mapgen_env.lua
  src/script/lua_api/l_mapgen.cpp
  src/script/lua_api/l_mapgen.h
Labels: @ Script API, One approval ✅ ◻️, Feature ✨
