Repository luanti-org/luanti, pull requests merged in 2025-01, with the labels that each got.

#15610 Fix MSAA and bloom flashing artifacts
  client/shaders/extract_bloom/opengl_fragment.glsl
  client/shaders/nodes_shader/opengl_fragment.glsl
  client/shaders/nodes_shader/opengl_vertex.glsl
Labels: One approval ✅ ◻️, Bugfix 🐛, @ Client rendering

#15621 Rename getMapSettingNoiseParams to getNoiseParams
  src/map_settings_manager.cpp
  src/map_settings_manager.h
  src/script/lua_api/l_mapgen.cpp
  src/unittest/test_map_settings_manager.cpp
Labels: Trivial, One approval ✅ ◻️, @ Engine Core

#15628 Eliminate superfluous null check in `CGUIEnvironment::getNextElement`
  irr/src/CGUIEnvironment.cpp
Labels: Maintenance, Trivial, One approval ✅ ◻️

#15629 Don't silence errorstream in tests
  src/unittest/test.cpp
Labels: Maintenance, One approval ✅ ◻️

#15625 Reduce irrlicht_extrabloated.h includes in header files
  irr/include/IGUIButton.h
  irr/include/IGUIElement.h
  irr/include/IGUIImage.h
  src/activeobjectmgr.h
  src/chat_interface.h
  src/client/client.cpp
  src/client/content_cao.h
  src/client/inputhandler.h
  src/client/joystick_controller.h
  src/client/mapblock_mesh.h
  src/client/mesh.cpp
  src/client/mesh.h
  src/client/minimap.h
  src/client/particles.cpp
  src/client/particles.h
  src/content/content.h
  src/debug.h
  src/emerge.h
  src/gui/mainmenumanager.h
  src/gui/modalMenu.h
  src/gui/touchscreeneditor.h
  src/network/serverpackethandler.cpp
  src/objdef.cpp
  src/objdef.h
  src/reflowscan.h
  src/server.cpp
  src/server/clientiface.cpp
  src/server/clientiface.h
  src/servermap.h
  src/unittest/test.h
  src/unittest/test_compression.cpp
Labels: Maintenance, One approval ✅ ◻️

#15624 Move `AutoExposure` constructor to header (and make it `constexpr`)
  src/CMakeLists.txt
  src/lighting.cpp
  src/lighting.h
Labels: Maintenance, Trivial, One approval ✅ ◻️

#15636 Fix show_debug setting causing inconsistency between debug control and shown debug info
  src/client/game.cpp
  src/client/gameui.cpp
Labels: Trivial, One approval ✅ ◻️, Bugfix 🐛

#15631 Rename getGameMinetestConfig to getGameConfig
  src/content/subgames.cpp
Labels: Maintenance, Code quality

#15555 Add unit test for raycasts falsely skipping nodes
  games/devtest/mods/unittests/raycast.lua
Labels: Maintenance, One approval ✅ ◻️, @ Devtest Game

#15626 Fix wireframe mode in opengl3 irr driver
  irr/src/OpenGL/Driver.cpp
  src/client/game.cpp
Labels: One approval ✅ ◻️, Bugfix 🐛, @ Client rendering

#15638 Fix falling nodes digging nodes they aren't supposed to
  builtin/game/falling.lua
Labels: @ Server / Client / Env., Bugfix 🐛, @ Builtin, 1 approval rule testing

#15644 Silence failing raycast unit test
  games/devtest/mods/unittests/init.lua
  games/devtest/mods/unittests/raycast.lua
Labels: Bug, One approval ✅ ◻️, Bugfix 🐛, @ Devtest Game

#15656 Fix reduced bloom at 10 bits
  src/client/render/secondstage.cpp
Labels: @ Client / Audiovisuals, Trivial, Bugfix 🐛

#15633 Remove or restrict some client settings
  builtin/settingtypes.txt
  src/client/clientlauncher.cpp
  src/client/clouds.cpp
  src/client/game.cpp
  src/client/game_formspec.cpp
  src/client/guiscalingfilter.cpp
  src/client/mapblock_mesh.cpp
  src/defaultsettings.cpp
  src/gui/guiEngine.cpp
  src/mapblock.cpp
  src/server.cpp
Labels: Maintenance, >= Two approvals ✅ ✅, Bugfix 🐛, @ Client rendering

#15669 Fix CFileSystem::FileSystemType related UB
  irr/src/CFileSystem.h
Labels: Trivial, One approval ✅ ◻️

#15657 VoxelArea: Fix missing cacheExtent calls in helpers
  src/unittest/test_voxelarea.cpp
  src/voxel.h
Labels: Trivial, One approval ✅ ◻️, Bugfix 🐛

#15665 Remove shadow direction quantization, increase shadow frames instead
  builtin/settingtypes.txt
  src/client/shadows/dynamicshadows.cpp
  src/defaultsettings.cpp
Labels: @ Client / Audiovisuals, Performance, One approval ✅ ◻️

#15104 Add chat console scrollbar
  src/chat.h
  src/client/game.cpp
  src/gui/guiChatConsole.cpp
  src/gui/guiChatConsole.h
Labels: Roadmap, >= Two approvals ✅ ✅, Feature ✨, @ Client / Controls / Input, UI/UX

#15648 Improve sleep accuracy on FPS limiter
  src/client/renderingengine.cpp
  src/porting.h
Labels: >= Two approvals ✅ ✅, Bugfix 🐛, @ Client rendering

#15561 Main menu server tab mods button
  LICENSE.txt
  builtin/mainmenu/dlg_server_list_mods.lua
  builtin/mainmenu/init.lua
  builtin/mainmenu/tab_online.lua
  textures/base/pack/server_url_unavailable.png
  textures/base/pack/server_view_clients_unavailable.png
  textures/base/pack/server_view_mods.png
  textures/base/pack/server_view_mods_unavailable.png
Labels: Roadmap, One approval ✅ ◻️, Feature ✨, @ Mainmenu, UI/UX

#15654 Resolve some quirks with (wield) item meshes for nodes
  src/client/content_mapblock.cpp
  src/client/content_mapblock.h
  src/client/mapblock_mesh.cpp
  src/client/mapblock_mesh.h
  src/client/wieldmesh.cpp
  src/client/wieldmesh.h
  src/nodedef.h
  src/voxel.h
Labels: Maintenance, One approval ✅ ◻️, Bugfix 🐛

#15673 Fix always waving semitransparent liquid regression
  client/shaders/nodes_shader/opengl_fragment.glsl
  src/client/shader.cpp
Labels: One approval ✅ ◻️, Bugfix 🐛, @ Client rendering, Regression

#15672 Fix bug memcpy call in a template
  src/util/pointer.h
Labels: >= Two approvals ✅ ✅, Code quality

#15594 Cache grouped sparse buffers
  builtin/settingtypes.txt
  src/client/client.cpp
  src/client/clientmap.cpp
  src/client/clientmap.h
  src/client/mapblock_mesh.h
  src/defaultsettings.cpp
Labels: Performance, One approval ✅ ◻️, @ Client rendering

#15687 Fix CMatrix<T>::getScale returning negative scale
  irr/include/matrix4.h
  src/client/content_cao.cpp
  src/unittest/test_irr_matrix4.cpp
Labels: One approval ✅ ◻️, Bugfix 🐛, @ Client rendering, Code quality

#15686 Remove built-in knockback from `punch()` in next major release
  doc/breakages.md
Labels: @ Documentation, >= Two approvals ✅ ✅

#15614 In-game settings menu using separate Lua env
  .luacheckrc
  builtin/client/init.lua
  builtin/client/register.lua
  builtin/common/register.lua
  builtin/common/settings/components.lua
  builtin/common/settings/dlg_change_mapgen_flags.lua
  builtin/common/settings/dlg_settings.lua
  builtin/common/settings/generate_from_settingtypes.lua
  builtin/common/settings/init.lua
  builtin/common/settings/settingtypes.lua
  builtin/common/settings/shadows_component.lua
  builtin/init.lua
  builtin/mainmenu/init.lua
  builtin/pause_menu/init.lua
  builtin/pause_menu/register.lua
  doc/menu_lua_api.md
  src/client/clientevent.h
  src/client/game.cpp
  src/client/game_formspec.cpp
  src/client/game_formspec.h
  src/gui/mainmenumanager.h
  src/script/CMakeLists.txt
  src/script/cpp_api/CMakeLists.txt
  src/script/cpp_api/s_base.cpp
  src/script/cpp_api/s_base.h
  src/script/cpp_api/s_client.cpp
  src/script/cpp_api/s_client.h
  src/script/cpp_api/s_client_common.cpp
  src/script/cpp_api/s_client_common.h
  src/script/cpp_api/s_pause_menu.cpp
  src/script/cpp_api/s_pause_menu.h
  src/script/lua_api/CMakeLists.txt
  src/script/lua_api/l_client.cpp
  src/script/lua_api/l_client.h
  src/script/lua_api/l_client_common.cpp
  src/script/lua_api/l_client_common.h
  src/script/lua_api/l_mainmenu.cpp
  src/script/lua_api/l_mainmenu.h
  src/script/lua_api/l_menu_common.cpp
  src/script/lua_api/l_menu_common.h
  src/script/lua_api/l_pause_menu.cpp
  src/script/lua_api/l_pause_menu.h
  src/script/lua_api/l_settings.cpp
  src/script/scripting_client.cpp
  src/script/scripting_client.h
  src/script/scripting_mainmenu.cpp
  src/script/scripting_pause_menu.cpp
  src/script/scripting_pause_menu.h
Labels: @ Startup / Config / Util, One approval ✅ ◻️, Feature ✨, UI/UX

#15606 Allow overriding fonts via media files
  doc/lua_api.md
  src/client/client.cpp
  src/client/fontengine.cpp
  src/client/fontengine.h
  src/irrlicht_changes/CGUITTFont.cpp
  src/irrlicht_changes/CGUITTFont.h
  src/server.cpp
  src/server/mods.cpp
Labels: @ Script API, One approval ✅ ◻️, Feature ✨, @ Client rendering

#15699 Fixed serialization_version and version_string key name in docs
  doc/lua_api.md
Labels: @ Documentation, Trivial, >= Two approvals ✅ ✅, Bugfix 🐛

#15705 Update github URL references
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/SECURITY.md
  .github/workflows/lua_api_deploy.yml
  CMakeLists.txt
  README.md
  android/native/build.gradle
  builtin/mainmenu/dlg_reinstall_mtg.lua
  client/shaders/second_stage/opengl_fragment.glsl
  doc/breakages.md
  doc/client_lua_api.md
  doc/compiling/linux.md
  doc/compiling/macos.md
  doc/developing/android.md
  doc/direction.md
  doc/lua_api.md
  doc/lua_api.txt
  doc/luanti.6
  doc/menu_lua_api.md
  irr/src/CIrrDeviceSDL.cpp
  lib/tiniergltf/Readme.md
  misc/net.minetest.minetest.metainfo.xml
  src/client/particles.cpp
  src/database/database-redis.cpp
  src/defaultsettings.cpp
  src/main.cpp
  src/unittest/test_mapblock.cpp
  src/unittest/test_threading.cpp
  util/buildbot/common.sh
  util/gather_git_credits.py
Labels: Maintenance, One approval ✅ ◻️

#15700 Add setting callbacks for Camera and TouchControls
  src/client/camera.cpp
  src/client/camera.h
  src/client/game.cpp
  src/gui/touchcontrols.cpp
  src/gui/touchcontrols.h
  src/gui/touchscreeneditor.cpp
Labels: @ Startup / Config / Util, Maintenance, One approval ✅ ◻️

#15707 Restore proper rollback database indexing
  src/server/rollback.cpp
Labels: Trivial, Performance

#15709 Fix shadow flicker on camera offset update
  src/client/game.cpp
  src/client/shadows/dynamicshadows.cpp
  src/client/shadows/dynamicshadows.h
  src/client/shadows/dynamicshadowsrender.cpp
Labels: Bugfix 🐛, @ Client rendering

#15711 filesys: replace goto by #else to omit compile warning
  src/filesys.cpp
Labels: Maintenance, Trivial, One approval ✅ ◻️

#15697 Restrict relative mouse mode to Wayland users
  irr/include/IrrlichtDevice.h
  irr/src/CIrrDeviceSDL.cpp
  irr/src/CIrrDeviceSDL.h
  src/client/game.cpp
Labels: Bugfix 🐛, @ Client / Controls / Input, 1 approval rule testing

#15715 Lua get_biome_data: calc heat and humidity only once
  src/script/lua_api/l_mapgen.cpp
Labels: @ Script API, Performance, >= Two approvals ✅ ✅

#15713 Fix documentation for the official Docker image after project rename
  doc/docker_server.md
Labels: @ Documentation, One approval ✅ ◻️, Bugfix 🐛

#15718 Rename dev.minetest.net to dev.luanti.org
  .github/CONTRIBUTING.md
  doc/client_lua_api.md
  doc/developing/README.md
  doc/lua_api.md
Labels: @ Documentation, Trivial, >= Two approvals ✅ ✅

#15704 Disable SDL2 for 5.11.0
  .github/workflows/windows.yml
  doc/compiling/linux.md
  doc/compiling/windows.md
  irr/README.md
  irr/src/CMakeLists.txt
  irr/src/COpenGLCoreTexture.h
  util/buildbot/buildwin32.sh
  util/buildbot/buildwin64.sh
  util/buildbot/common.sh
  util/ci/common.sh
Labels: Maintenance, One approval ✅ ◻️
