Repository luanti-org/luanti, pull requests merged in 2025-02, with the labels that each got.

#15680 Propagate peer ID change to outgoing reliables
  src/network/mtp/impl.cpp
  src/network/mtp/impl.h
  src/network/mtp/internal.h
  src/network/mtp/threads.cpp
  src/network/mtp/threads.h
Labels: @ Network, One approval ✅ ◻️, Bugfix 🐛

#15712 Updates some Minetest references to Luanti
  .gitignore
  doc/Doxyfile.in
  doc/compiling/linux.md
  doc/compiling/windows.md
  doc/developing/misc.md
  doc/main_page.dox
Labels: @ Documentation, Trivial, >= Two approvals ✅ ✅

#15716 COSOperator: Use NSPasteboardTypeString instead of NSStringPboardType
  irr/src/COSOperator.cpp
Labels: macOS, Trivial, >= Two approvals ✅ ✅

#15723 Delete irrlichttypes_extrabloated.h
  src/client/content_cao.cpp
  src/client/content_mapblock.cpp
  src/client/joystick_controller.cpp
  src/client/mapblock_mesh.cpp
  src/client/render/anaglyph.cpp
  src/client/render/core.h
  src/client/render/pipeline.h
  src/client/render/plain.cpp
  src/client/render/secondstage.cpp
  src/client/render/sidebyside.cpp
  src/client/renderingengine.h
  src/client/shader.cpp
  src/client/shadows/dynamicshadowsrender.h
  src/client/shadows/shadowsScreenQuad.h
  src/client/shadows/shadowsshadercallbacks.h
  src/client/wieldmesh.cpp
  src/gui/guiAnimatedImage.h
  src/gui/guiBackgroundImage.h
  src/gui/guiBox.cpp
  src/gui/guiBox.h
  src/gui/guiChatConsole.h
  src/gui/guiHyperText.h
  src/gui/guiInventoryList.h
  src/gui/guiItemImage.h
  src/gui/guiKeyChangeMenu.cpp
  src/gui/guiKeyChangeMenu.h
  src/gui/guiMainMenu.h
  src/gui/guiOpenURL.h
  src/gui/guiPasswordChange.h
  src/gui/guiScene.cpp
  src/gui/guiScene.h
  src/gui/guiScrollBar.h
  src/gui/guiScrollContainer.h
  src/gui/guiTable.h
  src/gui/guiVolumeChange.h
  src/gui/touchcontrols.cpp
  src/gui/touchscreeneditor.cpp
  src/irrlichttypes_extrabloated.h
  src/script/lua_api/l_mainmenu.cpp
  src/script/lua_api/l_util.cpp
Labels: Maintenance, >= Two approvals ✅ ✅, Code quality

#15685 Document that object properties `colors` field is unused
  doc/lua_api.md
  src/client/content_cao.cpp
  src/object_properties.cpp
  src/object_properties.h
  src/server/player_sao.cpp
Labels: @ Documentation, Maintenance, >= Two approvals ✅ ✅

#15720 PauseMenuScripting: resolve absolute 'builtin' path before substring check
  src/script/cpp_api/s_security.cpp
  src/script/scripting_pause_menu.cpp
Labels: >= Two approvals ✅ ✅, Bugfix 🐛

#15721 Clamp client-sent movement speed control
  src/network/serverpackethandler.cpp
Labels: Trivial, One approval ✅ ◻️, Bugfix 🐛

#15750 Enable relative mouse mode on Android
  src/client/game.cpp
Labels: Trivial, Bugfix 🐛

#15749 Revert "Prefer GL3 driver over legacy GL driver"
  src/client/renderingengine.cpp
  src/defaultsettings.cpp
Labels: Trivial, >= Two approvals ✅ ✅, Bugfix 🐛

#15748 Change main website domain to `www.luanti.org`
  .github/CONTRIBUTING.md
  builtin/settingtypes.txt
  doc/client_lua_api.md
  minetest.conf.example
  misc/net.minetest.minetest.metainfo.xml
  src/defaultsettings.cpp
Labels: Maintenance, >= Two approvals ✅ ✅

#15763 Rename Minetest to Luanti in CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: @ Documentation, Trivial, >= Two approvals ✅ ✅

#15764 GUI inventory list: Do not render clipped slots at all
  src/gui/guiInventoryList.cpp
Labels: Performance, One approval ✅ ◻️, Bugfix 🐛, @ Client rendering

#15766 Fix macOS signed app reject problem
  misc/macos/Info.plist.in
Labels: @ Build, macOS, Trivial, One approval ✅ ◻️, Bugfix 🐛

#15741 Const correct Thread class
  src/httpfetch.cpp
  src/threading/thread.cpp
  src/threading/thread.h
Labels: Maintenance, >= Two approvals ✅ ✅, Code quality

#15708 Expose client version information in non-debug builds
  builtin/game/misc_s.lua
  doc/lua_api.md
  games/devtest/.luacheckrc
  games/devtest/mods/unittests/get_version.lua
  games/devtest/mods/unittests/init.lua
  games/devtest/mods/unittests/version.lua
  src/network/networkprotocol.cpp
  src/script/lua_api/l_server.cpp
Labels: @ Script API, >= Two approvals ✅ ✅, Feature ✨

#15758 Don't save `load_mod_* = false` lines in `world.mt`
  builtin/mainmenu/dlg_config_world.lua
  src/content/mod_configuration.cpp
Labels: Trivial, One approval ✅ ◻️

#15733 Clean up Irrlicht matrices a bit more
  irr/include/matrix4.h
  src/unittest/test_irr_gltf_mesh_loader.cpp
Labels: Maintenance, >= Two approvals ✅ ✅, Code quality

#15408 Collision: more accurate computation with acceleration and long dtime
  src/collision.cpp
  src/unittest/test_collision.cpp
Labels: @ Server / Client / Env., One approval ✅ ◻️, Bugfix 🐛

#15736 Tweak main menu server list behavior
  builtin/mainmenu/dlg_clients_list.lua
  builtin/mainmenu/tab_online.lua
Labels: Maintenance, >= Two approvals ✅ ✅, Bugfix 🐛, @ Mainmenu, UI/UX

#15739 [no sq] Enable ipv6_server by default
  builtin/settingtypes.txt
  src/defaultsettings.cpp
  src/network/socket.cpp
Labels: @ Server / Client / Env., One approval ✅ ◻️, Feature ✨

#15719 Optimize add_area_node_boxes in collision code
  src/collision.cpp
Labels: @ Server / Client / Env., Performance, One approval ✅ ◻️

#15784 Correct keycode URL in settingtypes.txt/minetest.conf.example
  builtin/common/settings/generate_from_settingtypes.lua
Labels: Maintenance, Trivial, One approval ✅ ◻️

#15810 Prevent accidental wallmounted_to_dir poisoning by mods
  builtin/common/item_s.lua
Labels: >= Two approvals ✅ ✅, Bugfix 🐛, @ Builtin

#15799 Move `clickable_chat_weblinks` to Advanced > Miscellaneous
  builtin/settingtypes.txt
Labels: Maintenance, >= Two approvals ✅ ✅

#15796 Basic camera control API (just the mode)
  doc/lua_api.md
  src/client/camera.cpp
  src/client/camera.h
  src/client/client.h
  src/client/clientevent.h
  src/client/game.cpp
  src/network/clientopcodes.cpp
  src/network/clientpackethandler.cpp
  src/network/networkprotocol.h
  src/network/serveropcodes.cpp
  src/particles.h
  src/player.cpp
  src/player.h
  src/script/lua_api/l_object.cpp
  src/script/lua_api/l_object.h
  src/server.cpp
  src/server.h
  src/util/enum_string.h
Labels: @ Script API, @ Client / Audiovisuals, One approval ✅ ◻️, Feature ✨

#15813 Clang-Tidy config: Ignore performance-avoid-endl and performance-inefficient-string-concatenation
  .clang-tidy
Labels: Maintenance, Trivial, One approval ✅ ◻️

#15815 SDL irr device: Ignore +-0.0f y mouse wheel events
  irr/src/CIrrDeviceSDL.cpp
Labels: One approval ✅ ◻️, Bugfix 🐛, @ Client / Controls / Input

#15771 Implement metadata-aware version of InvRef:remove_item()
  builtin/game/features.lua
  doc/lua_api.md
  games/devtest/mods/unittests/inventory.lua
  src/inventory.cpp
  src/inventory.h
  src/script/lua_api/l_inventory.cpp
Labels: @ Script API, >= Two approvals ✅ ✅, Feature ✨, Roadmap: supported by core dev

#15605 Re-save active entities more often if they move a certain distance
  src/serverenvironment.cpp
Labels: @ Server / Client / Env., One approval ✅ ◻️, Bugfix 🐛, 1 approval rule testing

#15800 TouchControls: touch_use_crosshair, dig/place simulation refactoring
  src/client/game.cpp
  src/gui/touchcontrols.cpp
  src/gui/touchcontrols.h
  src/gui/touchscreenlayout.cpp
  src/gui/touchscreenlayout.h
Labels: Maintenance, Android, Bugfix 🐛, @ Client / Controls / Input, Code quality, 1 approval rule testing

#15787 Update copyright date in README
  README.md
Labels: @ Documentation, Trivial, One approval ✅ ◻️

#15835 Note that `core.hash_node_position` is not a hash function
  doc/lua_api.md
Labels: @ Documentation, Trivial
