Repository luanti-org/luanti, pull requests merged in 2025-09, with the labels that each got.

#16464 Fix macOS workflow homebrew conflict error
  util/ci/common.sh
Labels: Trivial, One approval ✅ ◻️, Bugfix 🐛

#16434 IrrlichtMt: Implement mip-mapping for RTTs
  irr/include/ITexture.h
  irr/src/CNullDriver.cpp
  irr/src/COpenGLCoreTexture.h
  irr/src/COpenGLDriver.cpp
  irr/src/OpenGL/Driver.cpp
Labels: One approval ✅ ◻️, Feature ✨, @ Client rendering

#16457 Lua API: Unify server env checks and fix missing ones
  src/script/lua_api/l_auth.cpp
  src/script/lua_api/l_env.cpp
  src/script/lua_api/l_internal.h
  src/script/lua_api/l_mapgen.cpp
  src/script/lua_api/l_object.cpp
  src/script/lua_api/l_server.cpp
Labels: @ Script API, >= Two approvals ✅ ✅, Bugfix 🐛

#16393 Add direnv
  .envrc
Labels: Trivial

#16438 Add formspec box color documentation to style section
  doc/lua_api.md
Labels: @ Documentation, Trivial, Formspec

#16445 [no squash] Small extension to `core.dynamic_add_media()`
  doc/lua_api.md
  games/devtest/mods/unittests/misc.lua
  src/script/lua_api/l_server.cpp
  src/server.cpp
  src/server.h
Labels: @ Server / Client / Env., Maintenance, One approval ✅ ◻️, Feature ✨

#15035 DOCS: clarify `stepheight` upper limit
  doc/lua_api.md
Labels: @ Documentation, Trivial, One approval ✅ ◻️, Bugfix 🐛

#16485 Add core.strip_escapes()
  builtin/common/misc_helpers.lua
  builtin/profiler/reporter.lua
  doc/lua_api.md
  src/script/lua_api/l_util.cpp
  src/script/lua_api/l_util.h
  src/unittest/test_scriptapi.cpp
  src/unittest/test_utilities.cpp
  src/util/string.h
Labels: @ Script API, >= Two approvals ✅ ✅, Feature ✨

#16502 Add missing chunk size safety checks
  src/mapgen/mapgen_v6.cpp
  src/mapgen/mg_decoration.cpp
Labels: @ Mapgen, Trivial, One approval ✅ ◻️, Bugfix 🐛

#16524 Mapgen: Correct border block criteria
  src/servermap.cpp
Labels: @ Mapgen, One approval ✅ ◻️, Bugfix 🐛
